import { useEffect, useRef, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { SessionApiError, SessionsApi, type Session, type SessionQr } from '../api/sessions';

const api = new SessionsApi();
const labels = { disconnected: 'Desconectada', connecting: 'Conectando', waiting_qr: 'Aguardando QR', connected: 'Conectada', stopped: 'Parada', error: 'Erro' } as const;
const date = (value?: string) => value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Não disponível';

export function App() {
  const [page, setPage] = useState<'dashboard' | 'devices'>('devices'); const [menuOpen, setMenuOpen] = useState(false);
  return <div className="shell"><button className="menu-button" aria-label="Abrir navegação" onClick={() => setMenuOpen(true)}>☰</button><aside className={menuOpen ? 'sidebar open' : 'sidebar'}><div className="brand">Chat<span>Pro</span></div><button className={page === 'dashboard' ? 'nav active' : 'nav'} onClick={() => { setPage('dashboard'); setMenuOpen(false); }}>Dashboard</button><button className={page === 'devices' ? 'nav active' : 'nav'} onClick={() => { setPage('devices'); setMenuOpen(false); }}>Dispositivos</button></aside><main><header><div><p className="eyebrow">PAINEL</p><h1>{page === 'devices' ? 'Dispositivos' : 'Dashboard'}</h1></div><span className="connection-note">Operação controlada</span></header>{page === 'devices' ? <Devices api={api} /> : <section className="empty-page"><h2>Bem-vindo ao ChatPro</h2><p>Use Dispositivos para administrar suas sessões.</p></section>}</main></div>;
}

export function Devices({ api }: { api: SessionsApi }) {
  const [sessions, setSessions] = useState<Session[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [creating, setCreating] = useState(false); const [name, setName] = useState(''); const [busy, setBusy] = useState<string>(); const [qr, setQr] = useState<SessionQr>(); const [confirm, setConfirm] = useState<{ type: 'logout' | 'remove'; session: Session }>(); const closeRef = useRef<HTMLButtonElement>(null);
  const load = async () => { setLoading(true); setError(''); try { setSessions(await api.list()); } catch (e) { setError(message(e)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []); useEffect(() => { if (qr && new Date(qr.expiresAt).getTime() <= Date.now()) setQr(undefined); const delay = qr ? Math.min(2_147_483_647, Math.max(0, new Date(qr.expiresAt).getTime() - Date.now())) : 0; const timeout = qr ? window.setTimeout(() => setQr(undefined), delay) : 0; return () => window.clearTimeout(timeout); }, [qr]); useEffect(() => { if (qr) closeRef.current?.focus(); }, [qr]);
  const update = (session: Session) => setSessions(items => items.map(item => item.id === session.id ? session : item));
  const action = async (id: string, kind: 'connect' | 'refresh' | 'stop' | 'logout' | 'remove' | 'status') => { setBusy(`${kind}-${id}`); setError(''); try { if (kind === 'connect' || kind === 'refresh') { await api.connect(id, kind === 'refresh'); const current = await api.status(id); update(current); if (current.status === 'waiting_qr') setQr(await api.qr(id)); } else if (kind === 'status') { const current = await api.status(id); update(current); if (current.status !== 'waiting_qr') setQr(currentQr => currentQr?.sessionId === id ? undefined : currentQr); } else if (kind === 'stop') { await api.stop(id); setQr(currentQr => currentQr?.sessionId === id ? undefined : currentQr); await action(id, 'status'); } else if (kind === 'logout') { await api.logout(id); setQr(undefined); await action(id, 'status'); } else { await api.remove(id); setQr(currentQr => currentQr?.sessionId === id ? undefined : currentQr); setSessions(items => items.filter(item => item.id !== id)); } } catch (e) { setError(message(e)); } finally { setBusy(undefined); } };
  const create = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return; setCreating(true); setError(''); try { const session = await api.create(name.trim()); setSessions(items => [...items, session]); setName(''); } catch (e) { setError(message(e)); } finally { setCreating(false); } };
  return <section className="devices"><div className="toolbar"><div><h2>Sessões do WhatsApp</h2><p>Gerencie conexões e QR temporários.</p></div><button className="secondary" onClick={() => void load()} disabled={loading}>Atualizar lista</button></div><form className="create" onSubmit={create}><label htmlFor="session-name">Nome do dispositivo</label><input id="session-name" value={name} onChange={e => setName(e.target.value)} maxLength={120} placeholder="Ex.: Atendimento" /><button disabled={creating}>{creating ? 'Criando…' : 'Criar sessão'}</button></form>{error && <div role="alert" className="alert">{error}</div>}{loading ? <p aria-live="polite">Carregando sessões…</p> : sessions.length === 0 ? <div className="empty"><h3>Nenhuma sessão criada</h3><p>Crie uma sessão para começar.</p></div> : <div className="cards">{sessions.map(session => <SessionCard key={session.id} session={session} busy={busy} onAction={action} onConfirm={(type) => setConfirm({ type, session })} />)}</div>}{qr && <QrModal qr={qr} onClose={() => setQr(undefined)} onRefresh={() => void action(qr.sessionId, 'refresh')} closeRef={closeRef} />}{confirm && <ConfirmModal item={confirm} onCancel={() => setConfirm(undefined)} onConfirm={() => { void action(confirm.session.id, confirm.type); setConfirm(undefined); }} />}</section>;
}

function SessionCard({ session, busy, onAction, onConfirm }: { session: Session; busy?: string; onAction: (id: string, kind: 'connect' | 'refresh' | 'stop' | 'status') => Promise<void>; onConfirm: (type: 'logout' | 'remove') => void }) { const pending = (kind: string) => busy === `${kind}-${session.id}`; return <article className="card"><div className="card-head"><div><h3>{session.name}</h3><p className="identifier">{session.id}</p></div><span className={`status ${session.status}`}>{labels[session.status]}</span></div><dl><div><dt>Criada em</dt><dd>{date(session.createdAt)}</dd></div><div><dt>Atualizada em</dt><dd>{date(session.updatedAt)}</dd></div></dl><div className="actions"><button onClick={() => void onAction(session.id, 'status')} disabled={!!busy}>{pending('status') ? 'Consultando…' : 'Status'}</button>{(session.status === 'disconnected' || session.status === 'stopped' || session.status === 'error') && <button onClick={() => void onAction(session.id, 'connect')} disabled={!!busy}>Conectar</button>}{session.status === 'waiting_qr' && <button onClick={() => void onAction(session.id, 'refresh')} disabled={!!busy}>Atualizar QR</button>}{(session.status === 'connecting' || session.status === 'waiting_qr' || session.status === 'connected') && <button onClick={() => void onAction(session.id, 'stop')} disabled={!!busy}>Parar</button>}<button className="danger-outline" onClick={() => onConfirm('logout')} disabled={!!busy}>Desconectar</button><button className="danger" onClick={() => onConfirm('remove')} disabled={!!busy}>Remover</button></div></article>; }
function QrModal({ qr, onClose, onRefresh, closeRef }: { qr: SessionQr; onClose: () => void; onRefresh: () => void; closeRef: React.RefObject<HTMLButtonElement> }) { return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="qr-title"><button ref={closeRef} className="close" onClick={onClose} aria-label="Fechar QR Code">×</button><h2 id="qr-title">Conectar dispositivo</h2><p>Escaneie o QR antes de expirar. Ele não é armazenado.</p><div data-testid="temporary-qr"><QRCodeSVG value={qr.qr} size={220} level="M" includeMargin /></div><p className="expires">Expira em {date(qr.expiresAt)}</p><button className="secondary" onClick={onRefresh}>Solicitar novo QR</button></section></div>; }
function ConfirmModal({ item, onCancel, onConfirm }: { item: { type: 'logout' | 'remove'; session: Session }; onCancel: () => void; onConfirm: () => void }) { const remove = item.type === 'remove'; return <div className="modal-backdrop"><section className="modal small" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title">{remove ? 'Remover sessão?' : 'Desconectar sessão?'}</h2><p>{remove ? `“${item.session.name}” e seus dados de sessão serão removidos.` : `“${item.session.name}” será desconectada.`}</p><div className="confirm-actions"><button className="secondary" autoFocus onClick={onCancel}>Cancelar</button><button className="danger" onClick={onConfirm}>{remove ? 'Remover' : 'Desconectar'}</button></div></section></div>; }
const message = (error: unknown) => error instanceof SessionApiError ? error.message : 'Ocorreu um erro inesperado.';
