import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { Devices } from './App';
import type { SessionsApi } from '../api/sessions';
const session = { id: 'session-1', name: 'Atendimento', status: 'waiting_qr' as const, updatedAt: '2026-07-15T12:00:00.000Z', createdAt: '2026-07-15T10:00:00.000Z' };
const api = (overrides: Partial<SessionsApi> = {}) => ({ list: vi.fn().mockResolvedValue([session]), create: vi.fn(), status: vi.fn().mockResolvedValue(session), qr: vi.fn().mockResolvedValue({ sessionId: session.id, qr: 'fake-qr-value', expiresAt: '2099-07-15T12:00:00.000Z' }), connect: vi.fn().mockResolvedValue(undefined), stop: vi.fn().mockResolvedValue(undefined), logout: vi.fn().mockResolvedValue(undefined), remove: vi.fn().mockResolvedValue(undefined), ...overrides } as unknown as SessionsApi);
describe('Devices', () => {
  it('renderiza QR falso e o limpa ao parar', async () => { const client = api(); render(<Devices api={client} />); await screen.findByText('Atendimento'); fireEvent.click(screen.getByText('Atualizar QR')); await screen.findByRole('dialog', { name: 'Conectar dispositivo' }); expect(screen.getByTestId('temporary-qr')).toBeInTheDocument(); fireEvent.click(screen.getByText('Parar')); await waitFor(() => expect(screen.queryByTestId('temporary-qr')).not.toBeInTheDocument()); expect(client.stop).toHaveBeenCalledWith('session-1'); });
  it('pede confirmação e executa stop, logout e remoção controlados', async () => { const client = api(); render(<Devices api={client} />); await screen.findByText('Atendimento'); fireEvent.click(screen.getByText('Parar')); await waitFor(() => expect(client.stop).toHaveBeenCalled()); fireEvent.click(screen.getByText('Desconectar')); fireEvent.click(within(await screen.findByRole('dialog', { name: 'Desconectar sessão?' })).getByRole('button', { name: 'Desconectar' })); await waitFor(() => expect(client.logout).toHaveBeenCalledWith('session-1')); fireEvent.click(screen.getByText('Remover')); fireEvent.click(within(await screen.findByRole('dialog', { name: 'Remover sessão?' })).getByRole('button', { name: 'Remover' })); await waitFor(() => expect(client.remove).toHaveBeenCalledWith('session-1')); });
  it('mostra erro de API sem iniciar conexão externa', async () => { const client = api({ list: vi.fn().mockRejectedValue(new Error('offline')) }); render(<Devices api={client} />); expect(await screen.findByRole('alert')).toHaveTextContent('Ocorreu um erro inesperado.'); expect(client.connect).not.toHaveBeenCalled(); });
  it('mantém cards empilháveis no modo responsivo', async () => { const client = api(); const { container } = render(<Devices api={client} />); await screen.findByText('Atendimento'); expect(container.querySelector('.cards')).toBeInTheDocument(); });
});
