import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import type { Campaign, Lead, PersistenceContact as Contact, PersistenceTemplate as Template, Pipeline, Stage } from '@chatpro/contracts';
import { ApiError } from '../api/client';
import { DomainApi } from '../api/domain';
import { SessionsApi } from '../api/sessions';

const domain = new DomainApi(); const sessionsApi = new SessionsApi();
const routes = [['/dashboard', 'Dashboard'], ['/devices', 'Dispositivos'], ['/crm', 'CRM'], ['/contacts', 'Contatos'], ['/templates', 'Templates'], ['/campaigns', 'Campanhas'], ['/settings', 'Configurações']] as const;
const message = (error: unknown) => error instanceof ApiError ? error.message : 'Ocorreu um erro inesperado.';
const stableDependencies: unknown[] = [];
function useResource<T>(load: () => Promise<T>, deps: unknown[] = stableDependencies) { const [data, setData] = useState<T>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const refresh = async () => { setLoading(true); setError(''); try { setData(await load()); } catch (e) { setError(message(e)); } finally { setLoading(false); } }; useEffect(() => { void refresh(); }, deps); return { data, error, loading, refresh }; }
const ErrorNotice = ({ error }: { error: string }) => error ? <p className="alert" role="alert">{error}</p> : null;
const Empty = ({ children }: { children: ReactNode }) => <div className="empty">{children}</div>;
const Modal = ({ title, close, children }: { title: string; close: () => void; children: ReactNode }) => <div className="modal-backdrop"><section className="modal form-modal" role="dialog" aria-modal="true" aria-label={title}><button className="close" onClick={close} aria-label="Fechar">×</button><h2>{title}</h2>{children}</section></div>;

export function App() { const [path, setPath] = useState(() => routes.some(([p]) => p === location.pathname) ? location.pathname : '/dashboard'); const [open, setOpen] = useState(false); useEffect(() => { const sync = () => setPath(location.pathname); addEventListener('popstate', sync); return () => removeEventListener('popstate', sync); }, []); const go = (to: string) => { history.pushState({}, '', to); setPath(to); setOpen(false); }; const Page = path === '/dashboard' ? Dashboard : path === '/devices' ? Devices : path === '/crm' ? Crm : path === '/contacts' ? Contacts : path === '/templates' ? Templates : path === '/campaigns' ? Campaigns : Settings; return <div className="shell"><button className="menu-button" onClick={() => setOpen(true)} aria-label="Abrir navegação">☰</button><aside className={open ? 'sidebar open' : 'sidebar'}><div className="brand">Chat<span>Pro</span></div>{routes.map(([to, name]) => <button key={to} className={path === to ? 'nav active' : 'nav'} onClick={() => go(to)}>{name}</button>)}</aside><main><header><div><p className="eyebrow">CHATPRO</p><h1>{routes.find(([to]) => to === path)?.[1]}</h1></div><span className="connection-note">Dados do workspace</span></header><Page /></main></div>; }

function Dashboard() { const { data, error, loading } = useResource(() => domain.dashboard()); if (loading) return <p className="page">Carregando dashboard…</p>; if (error) return <section className="page"><ErrorNotice error={error} /></section>; const d = data!; return <section className="page"><div className="stats">{[['Contatos', d.contacts], ['Opt-outs', d.optOutContacts], ['Tags', d.tags], ['Templates', d.templates], ['Leads', d.leads]].map(([name, total]) => <article className="stat" key={String(name)}><span>{name}</span><strong>{total}</strong></article>)}</div><div className="dashboard-grid"><Panel title="Leads por etapa">{d.leadsByStage.length ? d.leadsByStage.map(x => <p className="metric" key={x.stageId}><span>{x.name}</span><b>{x.total}</b></p>) : <Empty>Nenhuma etapa inicializada.</Empty>}</Panel><Panel title="Atividades recentes">{d.recentActivities.length ? d.recentActivities.map(x => <p key={x.id}>{x.type}</p>) : <Empty>Sem atividades.</Empty>}</Panel><Panel title="Campanhas por status">{d.campaignsByStatus.length ? d.campaignsByStatus.map(x => <p className="metric" key={x.status}><span>{x.status}</span><b>{x.total}</b></p>) : <Empty>Sem campanhas.</Empty>}</Panel><Panel title="Sessões por status">{d.sessionsByStatus.length ? d.sessionsByStatus.map(x => <p className="metric" key={x.status}><span>{x.status}</span><b>{x.total}</b></p>) : <Empty>Sem sessões.</Empty>}</Panel></div></section>; }
const Panel = ({ title, children }: { title: string; children: ReactNode }) => <section className="panel"><h2>{title}</h2>{children}</section>;

export function Devices({ api = sessionsApi }: { api?: SessionsApi }) {
  const { data = [], error, loading, refresh } = useResource(() => api.list());
  const [busy, setBusy] = useState<string>();
  const [actionError, setActionError] = useState('');
  const [qr, setQr] = useState<{ sessionId: string; name: string; value: string; expiresAt: string }>();
  const [qrRequestedSessionId, setQrRequestedSessionId] = useState<string>();
  useEffect(() => {
    const session = data.find(item => item.status === 'waiting_qr');
    if (!session) { setQr(undefined); setQrRequestedSessionId(undefined); return; }
    if (qr?.sessionId === session.id || qrRequestedSessionId === session.id) return;
    const controller = new AbortController();
    void (async () => {
      try {
        const current = await api.status(session.id, controller.signal);
        if (current.status !== 'waiting_qr') { if (!controller.signal.aborted) setQr(undefined); return; }
        const next = await api.qr(session.id, controller.signal);
        if (!controller.signal.aborted) { setQrRequestedSessionId(session.id); setQr({ sessionId: session.id, name: session.name, value: next.qr, expiresAt: next.expiresAt }); }
      } catch (nextError) {
        if (controller.signal.aborted) return;
        if (nextError instanceof ApiError && nextError.code === 'REQUEST_FAILED' && (nextError.details.status === 404 || nextError.details.status === 409)) { setQr(undefined); setQrRequestedSessionId(session.id); void refresh(); return; }
        setActionError(message(nextError));
      }
    })();
    return () => controller.abort();
  }, [api, data, qr?.sessionId, qrRequestedSessionId]);
  useEffect(() => {
    if (!data.some(session => session.status === 'waiting_qr' || session.status === 'connecting')) return;
    const timer = window.setTimeout(() => void refresh(), 1_000);
    return () => window.clearTimeout(timer);
  }, [api, data]);
  useEffect(() => {
    if (!qr) return;
    const timeout = window.setTimeout(() => setQr(undefined), Math.max(0, new Date(qr.expiresAt).getTime() - Date.now()));
    return () => window.clearTimeout(timeout);
  }, [qr]);
  const execute = async (key: string, action: () => Promise<void>) => {
    setBusy(key); setActionError('');
    try { await action(); await refresh(); } catch (e) { setActionError(message(e)); } finally { setBusy(undefined); }
  };
  const connect = async (id: string, name: string) => execute(`connect-${id}`, async () => {
    await api.connect(id);
    for (let attempt = 0; attempt < 12; attempt += 1) {
      const current = await api.status(id);
      if (current.status !== 'waiting_qr') { if (current.status === 'connecting' || current.status === 'connected') { setQr(undefined); return; } await new Promise(resolve => window.setTimeout(resolve, 500)); continue; }
      try { const next = await api.qr(id); setQrRequestedSessionId(id); setQr({ sessionId: id, name, value: next.qr, expiresAt: next.expiresAt }); return; }
      catch (e) { if (e instanceof ApiError && e.code === 'REQUEST_FAILED' && (e.details.status === 404 || e.details.status === 409)) return; if (!(e instanceof ApiError) || e.code !== 'REQUEST_FAILED') throw e; await new Promise(resolve => window.setTimeout(resolve, 500)); }
    }
    throw new ApiError('REQUEST_FAILED', 'O QR real ainda não foi disponibilizado pelo worker. Atualize a sessão em instantes.');
  });
  return <section className="page devices"><div className="toolbar"><div><h2>Sessões WhatsApp</h2><p>Gerencie sessões reais e exiba o QR fornecido pelo worker.</p></div><button className="secondary" disabled={loading || Boolean(busy)} onClick={() => void refresh()}>Atualizar</button></div><form className="create" onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const name = String(new FormData(form).get('name') ?? '').trim(); if (!name) return; void execute('create', async () => { await api.create(name); form.reset(); }); }}><label>Nome da sessão<input name="name" required maxLength={120} placeholder="Ex.: Atendimento" /></label><button disabled={Boolean(busy)}>{busy === 'create' ? 'Criando…' : 'Nova Sessão'}</button></form><ErrorNotice error={error || actionError} />{loading ? <p>Carregando sessões…</p> : data.length ? <div className="cards">{data.map(s => <article className="card" key={s.id}><div className="card-head"><div><h3>{s.name}</h3><p className="identifier">{s.id}</p></div><span className={`status ${s.status}`}>{s.status}</span></div><dl><div><dt>Atualizada em</dt><dd>{new Date(s.updatedAt).toLocaleString()}</dd></div></dl><div className="actions"><button disabled={Boolean(busy)} onClick={() => void connect(s.id, s.name)}>{busy === `connect-${s.id}` ? 'Solicitando QR…' : 'Conectar'}</button><button className="secondary" disabled={Boolean(busy)} onClick={() => void execute(`status-${s.id}`, async () => { await api.status(s.id); })}>Atualizar</button><button className="secondary" disabled={Boolean(busy)} onClick={() => void execute(`stop-${s.id}`, () => api.stop(s.id))}>Parar</button><button className="danger-outline" disabled={Boolean(busy)} onClick={() => void execute(`logout-${s.id}`, () => api.logout(s.id))}>Logout</button><button className="danger" disabled={Boolean(busy)} onClick={() => { if (confirm(`Remover a sessão ${s.name}?`)) void execute(`remove-${s.id}`, () => api.remove(s.id)); }}>Remover</button></div></article>)}</div> : <Empty>Nenhuma sessão criada.</Empty>}{qr && <Modal title={`QR de ${qr.name}`} close={() => setQr(undefined)}><p>Escaneie no WhatsApp somente quando quiser conectar esta sessão.</p><QRCodeSVG value={qr.value} size={240} level="M" includeMargin /><p className="expires">Expira em {new Date(qr.expiresAt).toLocaleTimeString()}.</p></Modal>}</section>;
}

function Contacts() { const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [draft, setDraft] = useState<Contact>(); const { data: tags = [], refresh: refreshTags } = useResource(() => domain.tags()); const { data, error, loading, refresh } = useResource(() => domain.contacts({ page, pageSize: 20, search }), [page, search]); const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); const body = { displayName: f.get('name'), phoneNumber: f.get('phone'), email: f.get('email') || null, company: f.get('company') || null, tagIds: [...event.currentTarget.querySelectorAll<HTMLInputElement>('input[name=tag]:checked')].map(x => x.value) }; try { draft?.id ? await domain.updateContact(draft.id, body) : await domain.createContact(body); setDraft(undefined); await refresh(); } catch (e) { alert(message(e)); } }; return <section className="page"><div className="toolbar"><input aria-label="Buscar contatos" placeholder="Buscar contatos" value={search} onChange={e => { setPage(1); setSearch(e.target.value); }} /><button onClick={() => setDraft({} as Contact)}>Novo contato</button></div><TagManager tags={tags} refresh={refreshTags} /><ErrorNotice error={error} />{loading ? <p>Carregando…</p> : <><table><thead><tr><th>Nome</th><th>Telefone</th><th>E-mail</th><th>Ações</th></tr></thead><tbody>{data?.items.map(c => <tr key={c.id}><td>{c.displayName}</td><td>{c.phoneNumber}</td><td>{c.email}</td><td><button className="secondary" onClick={() => setDraft(c)}>Editar</button> <button className="secondary" onClick={async () => { const state = await domain.optOutStatus(c.id); state.optedOut ? await domain.removeOptOut(c.id) : await domain.optOut(c.id, { reason: 'manual' }); await refresh(); }}>Opt-out</button></td></tr>)}</tbody></table>{!data?.items.length && <Empty>Nenhum contato encontrado.</Empty>}<Pager page={page} total={data?.total ?? 0} setPage={setPage} /></>}{draft && <Modal title={draft.id ? 'Editar contato' : 'Novo contato'} close={() => setDraft(undefined)}><form onSubmit={save}><label>Nome<input name="name" required defaultValue={draft.displayName} /></label><label>Telefone<input name="phone" required defaultValue={draft.phoneNumber} /></label><label>E-mail<input name="email" type="email" defaultValue={draft.email ?? ''} /></label><label>Empresa<input name="company" defaultValue={draft.company ?? ''} /></label><fieldset><legend>Tags</legend>{tags.map(t => <label key={t.id}><input name="tag" type="checkbox" value={t.id} /> {t.name}</label>)}</fieldset><Actions close={() => setDraft(undefined)} remove={draft.id ? async () => { if (confirm('Excluir contato?')) { await domain.deleteContact(draft.id); setDraft(undefined); await refresh(); } } : undefined} /></form></Modal>}</section>; }
function TagManager({ tags, refresh }: { tags: Array<{ id: string; name: string; color: string | null }>; refresh: () => Promise<void> }) { return <section className="panel"><h2>Tags</h2><button className="secondary" onClick={async () => { const name = prompt('Nome da tag'); if (name) { await domain.createTag({ name, color: null }); await refresh(); } }}>Criar tag</button>{tags.map(tag => <p key={tag.id}>{tag.name} <button className="secondary" onClick={async () => { const name = prompt('Novo nome', tag.name); if (name) { await domain.updateTag(tag.id, { name }); await refresh(); } }}>Editar</button> <button className="danger-outline" onClick={async () => { if (confirm('Excluir tag?')) { try { await domain.deleteTag(tag.id); await refresh(); } catch (e) { alert(message(e)); } } }}>Excluir</button></p>)}</section>; }

function Templates() { const { data = [], error, loading, refresh } = useResource(() => domain.templates()); const [draft, setDraft] = useState<(Template & { active?: boolean | number })>(); const [preview, setPreview] = useState(''); return <section className="page"><div className="toolbar"><h2>Templates</h2><button onClick={() => setDraft({} as Template)}>Novo template</button></div><ErrorNotice error={error} />{loading ? <p>Carregando…</p> : data.length ? <div className="template-list">{data.map(t => <Panel title={t.name} key={t.id}><p>{t.content}</p><p>{t.variables.join(', ') || 'Sem variáveis'} · {t.active ? 'Ativo' : 'Inativo'}</p><button className="secondary" onClick={() => setDraft(t)}>Editar</button> <button className="secondary" onClick={async () => setPreview((await domain.preview(t.id, Object.fromEntries(t.variables.map(v => [v, `[${v}]`])))).content)}>Preview</button> <button className="secondary" onClick={async () => { await domain.active(t.id, !t.active); await refresh(); }}>{t.active ? 'Desativar' : 'Ativar'}</button></Panel>)}</div> : <Empty>Nenhum template.</Empty>}{preview && <Panel title="Preview"><pre>{preview}</pre></Panel>}{draft && <Modal title={draft.id ? 'Editar template' : 'Novo template'} close={() => setDraft(undefined)}><form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); await domain.saveTemplate(draft.id, { name: f.get('name'), content: f.get('content') }); setDraft(undefined); await refresh(); }}><label>Nome<input name="name" required defaultValue={draft.name} /></label><label>Conteúdo<textarea name="content" required defaultValue={draft.content} /></label><Actions close={() => setDraft(undefined)} /></form></Modal>}</section>; }
function Crm() { const { data: pipelines = [], refresh: refreshP } = useResource(() => domain.pipelines()); const [pipeline, setPipeline] = useState<Pipeline>(); useEffect(() => { if (!pipeline && pipelines[0]) setPipeline(pipelines[0]); }, [pipelines, pipeline]); const { data: stages = [] } = useResource(() => pipeline ? domain.stages(pipeline.id) : Promise.resolve([]), [pipeline]); const { data: leads, refresh: refreshL } = useResource(() => pipeline ? domain.leads({ pipelineId: pipeline.id, pageSize: 100 }) : Promise.resolve({ items: [], page: 1, pageSize: 100, total: 0 }), [pipeline]); if (!pipelines.length) return <section className="page"><Empty><p>Nenhum pipeline inicializado.</p><button onClick={async () => { await domain.initialize(); await refreshP(); }}>Inicializar pipeline</button></Empty></section>; return <section className="page"><div className="toolbar"><select aria-label="Pipeline" value={pipeline?.id ?? ''} onChange={e => setPipeline(pipelines.find(p => p.id === e.target.value))}>{pipelines.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><button onClick={async () => { const title = prompt('Título do lead'); if (title && stages[0]) { await domain.saveLead(undefined, { title, stageId: stages[0].id }); await refreshL(); } }}>Novo lead</button></div><div className="kanban">{stages.map(stage => <section className="column" key={stage.id}><h2>{stage.name}</h2>{leads?.items.filter(l => l.stageId === stage.id).map(lead => <article className="lead-card" key={lead.id}><strong>{lead.title}</strong><select aria-label={`Mover ${lead.title}`} value={lead.stageId} onChange={async e => { await domain.moveLead(lead.id, e.target.value); await refreshL(); }}>{stages.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></article>)}</section>)}</div></section>; }
function Campaigns() { const { data: campaigns, refresh } = useResource(() => domain.campaigns({ pageSize: 100 })); const { data: templates = [] } = useResource(() => domain.templates()); const { data: contacts } = useResource(() => domain.contacts({ pageSize: 100 })); const [result, setResult] = useState(''); return <section className="page"><div className="toolbar"><h2>Campanhas</h2><button onClick={async () => { const name = prompt('Nome do rascunho'); if (name) { await domain.saveCampaign(undefined, { name }); await refresh(); } }}>Novo rascunho</button></div>{campaigns?.items.length ? <div className="template-list">{campaigns.items.map(c => <Panel title={c.name} key={c.id}><p>Status: {c.status}</p><button className="secondary" onClick={async () => { const r = await domain.validate(c.id); setResult(r.valid ? 'Campanha válida.' : r.problems.join(', ')); }}>Validar</button> <button className="secondary" onClick={async () => { const r = await domain.prepare(c.id); setResult(`${r.eligibleRecipients} elegíveis; ${r.excludedOptOut} excluídos por opt-out.`); await refresh(); }}>Preparar lote</button> <button className="secondary" onClick={async () => { const when = prompt('Data ISO para agendar'); if (when) { await domain.schedule(c.id, when); await refresh(); } }}>Agendar</button> <button className="danger-outline" onClick={async () => { if (confirm('Cancelar campanha?')) { await domain.cancel(c.id); await refresh(); } }}>Cancelar</button></Panel>)}</div> : <Empty>Nenhuma campanha.</Empty>}<p>{result}</p><Panel title="Destinatários disponíveis"><p>{contacts?.total ?? 0} contatos e {templates.length} templates disponíveis para os rascunhos.</p></Panel></section>; }
function Settings() { const { data, error, refresh } = useResource(() => domain.settings()); const s = data?.settings ?? {}; return <section className="page settings panel"><ErrorNotice error={error} /><form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); await domain.saveSettings({ workspaceName: String(f.get('workspaceName')), locale: String(f.get('locale')), timezone: String(f.get('timezone')), defaultCountryCode: String(f.get('country')), operational: { compact: Boolean(f.get('compact')) } }); await refresh(); }}><label>Nome do workspace<input name="workspaceName" required defaultValue={s.workspaceName ?? ''} /></label><label>Locale<input name="locale" defaultValue={s.locale ?? 'pt-BR'} /></label><label>Fuso horário<input name="timezone" defaultValue={s.timezone ?? 'America/Sao_Paulo'} /></label><label>Código do país<input name="country" pattern="[0-9]{1,3}" defaultValue={s.defaultCountryCode ?? '55'} /></label><label><input name="compact" type="checkbox" defaultChecked={Boolean(s.operational?.compact)} /> Preferência operacional compacta</label><button>Salvar configurações</button></form></section>; }
function Actions({ close, remove }: { close: () => void; remove?: () => Promise<void> }) { return <div className="confirm-actions">{remove && <button type="button" className="danger-outline" onClick={() => void remove()}>Excluir</button>}<button type="button" className="secondary" onClick={close}>Cancelar</button><button>Salvar</button></div>; }
function Pager({ page, total, setPage }: { page: number; total: number; setPage: (page: number) => void }) { return <div className="pager"><button className="secondary" disabled={page === 1} onClick={() => setPage(page - 1)}>Anterior</button><span>Página {page} · {total} registros</span><button className="secondary" disabled={page * 20 >= total} onClick={() => setPage(page + 1)}>Próxima</button></div>; }
