import { useEffect, useState } from 'react';
import type { RoutingQueue, RoutingQueueMember, Team, WorkspaceUser } from '@chatpro/contracts';
import { RoutingApi } from '../api/routing';
import { WorkspaceApi } from '../api/workspace';
import { connectRealtime } from '../api/realtime';
const api = new RoutingApi(); const workspace = new WorkspaceApi();
export default function RoutingQueues() {
  const [queues,setQueues]=useState<RoutingQueue[]>([]); const [users,setUsers]=useState<WorkspaceUser[]>([]); const [teams,setTeams]=useState<Team[]>([]); const [members,setMembers]=useState<Record<string,RoutingQueueMember[]>>({}); const [error,setError]=useState('');
  const refresh=async()=>{ try { const [q,u,t]=await Promise.all([api.queues(),workspace.users(),workspace.teams()]); setQueues(q);setUsers(u);setTeams(t);setMembers(Object.fromEntries(await Promise.all(q.map(async queue=>[queue.id,await api.members(queue.id)] as const))));setError(''); } catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar filas.');} };
  useEffect(()=>{void refresh();return connectRealtime(event=>{if(event.eventType.startsWith('routing.')||event.eventType.startsWith('workspace.'))void refresh();});},[]);
  const create=async(form:HTMLFormElement)=>{const f=new FormData(form);await api.create({name:String(f.get('name')),description:String(f.get('description')||'')||null,teamId:String(f.get('teamId')||'')||null,strategy:String(f.get('strategy')) as RoutingQueue['strategy'],maxOpenConversationsPerAgent:f.get('limit')?Number(f.get('limit')):null});form.reset();await refresh();};
  return <section className="page team-directory"><div className="toolbar"><div><h2>Filas</h2><p>Distribuição auditável por equipe, disponibilidade e carga.</p></div><button className="secondary" onClick={()=>void refresh()}>Atualizar</button></div>{error&&<p className="alert">{error}</p>}<section className="panel"><form className="create" onSubmit={e=>{e.preventDefault();void create(e.currentTarget).catch(x=>setError(x instanceof Error?x.message:'Não foi possível criar a fila.'));}}><label>Nome<input name="name" required maxLength={120}/></label><label>Equipe<select name="teamId"><option value="">Sem equipe vinculada</option>{teams.filter(t=>t.isActive).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Estratégia<select name="strategy" defaultValue="round_robin"><option value="round_robin">Round robin</option><option value="least_loaded">Menor carga</option><option value="manual">Manual</option></select></label><label>Limite por operador<input name="limit" type="number" min="1" placeholder="Sem limite"/></label><label>Descrição<input name="description" maxLength={500}/></label><button>Nova fila</button></form></section><div className="directory-list">{queues.map(queue=>{const queueMembers=members[queue.id]??[];const eligible=users.filter(u=>u.status==='active'&&!queueMembers.some(m=>m.userId===u.id));return <article className="panel" key={queue.id}><div><strong>{queue.name}</strong><small>{queue.strategy==='round_robin'?'Round robin':queue.strategy==='least_loaded'?'Menor carga':'Manual'} · {queue.isActive?'Ativa':'Inativa'} · {queue.maxOpenConversationsPerAgent??'sem'} limite</small>{queue.description&&<small>{queue.description}</small>}<span className="team-members">{queueMembers.map(m=><span key={m.userId}>{users.find(u=>u.id===m.userId)?.displayName??'Operador'} · <button type="button" className="secondary" onClick={()=>void api.saveMember(queue.id,{userId:m.userId,isAvailable:!m.isAvailable,priorityWeight:m.priorityWeight}).then(refresh)}>{m.isAvailable?'Disponível':'Indisponível'}</button> <button type="button" className="secondary" onClick={()=>void api.removeMember(queue.id,m.userId).then(refresh)}>Remover</button></span>)||'Sem operadores'}</span></div><div><select aria-label={`Adicionar operador à fila ${queue.name}`} defaultValue="" onChange={e=>{if(e.target.value)void api.saveMember(queue.id,{userId:e.target.value}).then(refresh)}}><option value="">Adicionar operador</option>{eligible.map(u=><option key={u.id} value={u.id}>{u.displayName}</option>)}</select><button className="secondary" onClick={()=>void api.update(queue.id,{isActive:!queue.isActive}).then(refresh)}>{queue.isActive?'Desativar':'Ativar'}</button></div></article>})}</div></section>;
}
