import { randomUUID } from 'node:crypto';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { RequestContext } from '@chatpro/contracts';
import type { SqliteDatabase } from '../persistence/database.js';
import { AppError } from '../errors.js';
import type { InternalWorkerClient } from '../internal-worker-client.js';

export const TEMPORARY_ATTACHMENT_BUCKET = 'chatpro-temporary-attachments';
export type AttachmentKind = 'image' | 'audio' | 'video' | 'document';
export type OutboxStatus = 'pending' | 'processing' | 'sent' | 'confirmed' | 'failed' | 'cancelled';
export type OutboxJob = { id: string; workspaceId: string; conversationId: string; wahaSession: string; type: AttachmentKind; storageObjectPath: string | null; filename: string | null; mimeType: string | null; sizeBytes: number | null; caption: string | null; status: OutboxStatus; attemptCount: number; externalMessageId: string | null; lastErrorSafe: string | null; createdAt: string; updatedAt: string };
type Conversation = { id: string; whatsappSessionId: string; chatId: string; deliveryChatId?: string };
export type UploadFile = { buffer: Buffer; originalname: string; mimetype: string; size: number };

const policy: Record<AttachmentKind, { mimes: readonly string[]; max: number }> = {
  image: { mimes: ['image/jpeg', 'image/png', 'image/webp'], max: 15 * 1024 * 1024 },
  audio: { mimes: ['audio/ogg', 'audio/mpeg', 'audio/mp4', 'audio/webm'], max: 25 * 1024 * 1024 },
  video: { mimes: ['video/mp4', 'video/webm'], max: 50 * 1024 * 1024 },
  document: { mimes: ['application/pdf', 'text/plain', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'], max: 25 * 1024 * 1024 },
};
export const attachmentPolicy = policy;

export interface TemporaryAttachmentStorage { upload(path: string, file: UploadFile): Promise<void>; signedUrl(path: string, expiresInSeconds: number): Promise<string>; remove(path: string): Promise<void>; }
export interface AttachmentOutboxStore { create(job: OutboxJob): Promise<OutboxJob>; get(workspaceId: string, id: string): Promise<OutboxJob | undefined>; update(workspaceId: string, id: string, changes: Partial<OutboxJob>): Promise<OutboxJob | undefined>; confirm(workspaceId: string, externalMessageId: string): Promise<OutboxJob | undefined>; expired(before: string): Promise<OutboxJob[]>; }

export class SupabaseTemporaryAttachmentStorage implements TemporaryAttachmentStorage {
  constructor(private readonly client: SupabaseClient, private readonly bucket = TEMPORARY_ATTACHMENT_BUCKET) {}
  async upload(path: string, file: UploadFile): Promise<void> { const { error } = await this.client.storage.from(this.bucket).upload(path, file.buffer, { contentType: file.mimetype, upsert: false }); if (error) throw new AppError(503, 'SERVICE_UNAVAILABLE', 'Temporary attachment storage is unavailable'); }
  async signedUrl(path: string, expiresInSeconds: number): Promise<string> { const { data, error } = await this.client.storage.from(this.bucket).createSignedUrl(path, expiresInSeconds); if (error || !data?.signedUrl) throw new AppError(503, 'SERVICE_UNAVAILABLE', 'Temporary attachment storage is unavailable'); return data.signedUrl; }
  async remove(path: string): Promise<void> { const { error } = await this.client.storage.from(this.bucket).remove([path]); if (error) throw new AppError(503, 'SERVICE_UNAVAILABLE', 'Temporary attachment cleanup failed'); }
}
export class UnavailableTemporaryAttachmentStorage implements TemporaryAttachmentStorage { private unavailable(): never { throw new AppError(503, 'SERVICE_UNAVAILABLE', 'Attachment sending requires private Supabase Storage configuration'); } async upload(): Promise<void> { this.unavailable(); } async signedUrl(): Promise<string> { return this.unavailable(); } async remove(): Promise<void> { this.unavailable(); } }

export class SqliteAttachmentOutboxStore implements AttachmentOutboxStore {
  constructor(private readonly db: SqliteDatabase) {}
  async create(job: OutboxJob) { this.db.prepare('INSERT INTO inbox_outbox_jobs (id, workspaceId, conversationId, wahaSession, type, storageObjectPath, filename, mimeType, sizeBytes, caption, status, attemptCount, externalMessageId, lastErrorSafe, createdAt, updatedAt) VALUES (@id,@workspaceId,@conversationId,@wahaSession,@type,@storageObjectPath,@filename,@mimeType,@sizeBytes,@caption,@status,@attemptCount,@externalMessageId,@lastErrorSafe,@createdAt,@updatedAt)').run(job); return job; }
  async get(workspaceId: string, id: string) { const row = this.db.prepare('SELECT * FROM inbox_outbox_jobs WHERE workspaceId = ? AND id = ?').get(workspaceId, id) as Record<string, unknown> | undefined; return row ? sqliteJob(row) : undefined; }
  async update(workspaceId: string, id: string, changes: Partial<OutboxJob>) { const current = await this.get(workspaceId, id); if (!current) return undefined; const next = { ...current, ...changes, workspaceId, id, updatedAt: new Date().toISOString() }; this.db.prepare('UPDATE inbox_outbox_jobs SET type=@type, storageObjectPath=@storageObjectPath, filename=@filename, mimeType=@mimeType, sizeBytes=@sizeBytes, caption=@caption, status=@status, attemptCount=@attemptCount, externalMessageId=@externalMessageId, lastErrorSafe=@lastErrorSafe, updatedAt=@updatedAt WHERE workspaceId=@workspaceId AND id=@id').run(next); return next; }
  async confirm(workspaceId: string, externalMessageId: string) { const row = this.db.prepare("SELECT * FROM inbox_outbox_jobs WHERE workspaceId = ? AND externalMessageId = ? AND status = 'sent'").get(workspaceId, externalMessageId) as Record<string, unknown> | undefined; if (!row) return undefined; return this.update(workspaceId, String(row.id), { status: 'confirmed' }); }
  async expired(before: string) { return (this.db.prepare("SELECT * FROM inbox_outbox_jobs WHERE storageObjectPath IS NOT NULL AND status IN ('pending','processing','sent','failed') AND createdAt < ?").all(before) as Record<string, unknown>[]).map(sqliteJob); }
}
export class SupabaseAttachmentOutboxStore implements AttachmentOutboxStore {
  constructor(private readonly client: SupabaseClient) {}
  async create(job: OutboxJob) { const { error } = await this.client.from('inbox_outbox_jobs').insert(remoteJob(job)); if (error) throw error; return job; }
  async get(workspaceId: string, id: string) { const { data, error } = await this.client.from('inbox_outbox_jobs').select().eq('workspace_id', workspaceId).eq('id', id).maybeSingle(); if (error) throw error; return data ? fromRemote(data) : undefined; }
  async update(workspaceId: string, id: string, changes: Partial<OutboxJob>) { const { data, error } = await this.client.from('inbox_outbox_jobs').update(remoteChanges(changes)).eq('workspace_id', workspaceId).eq('id', id).select().maybeSingle(); if (error) throw error; return data ? fromRemote(data) : undefined; }
  async confirm(workspaceId: string, externalMessageId: string) { const { data, error } = await this.client.from('inbox_outbox_jobs').update({ status: 'confirmed', updated_at: new Date().toISOString() }).eq('workspace_id', workspaceId).eq('external_message_id', externalMessageId).eq('status', 'sent').select().maybeSingle(); if (error) throw error; return data ? fromRemote(data) : undefined; }
  async expired(before: string) { const { data, error } = await this.client.from('inbox_outbox_jobs').select().not('storage_object_path', 'is', null).in('status', ['pending', 'processing', 'sent', 'failed']).lt('created_at', before); if (error) throw error; return (data ?? []).map(fromRemote); }
}

export class AttachmentOutboxService {
  constructor(private readonly conversations: { getConversation(workspaceId: string, conversationId: string): Promise<Conversation | undefined> }, private readonly store: AttachmentOutboxStore, private readonly storage: TemporaryAttachmentStorage, private readonly worker: InternalWorkerClient) {}
  async create(context: RequestContext, conversationId: string, file: UploadFile, caption?: string): Promise<OutboxJob> {
    const conversation = await this.conversations.getConversation(context.workspaceId, conversationId); if (!conversation) throw new AppError(404, 'NOT_FOUND', 'Conversation not found');
    const type = validateFile(file); const id = randomUUID(); const filename = sanitizeFilename(file.originalname); const now = new Date().toISOString(); const path = `${context.workspaceId}/${conversationId}/${id}/${filename}`;
    const job: OutboxJob = { id, workspaceId: context.workspaceId, conversationId, wahaSession: conversation.whatsappSessionId, type, storageObjectPath: path, filename, mimeType: file.mimetype, sizeBytes: file.size, caption: caption?.trim() || null, status: 'pending', attemptCount: 0, externalMessageId: null, lastErrorSafe: null, createdAt: now, updatedAt: now };
    await this.store.create(job);
    try { await this.storage.upload(path, file); } catch (error) { await this.store.update(context.workspaceId, id, { status: 'failed', lastErrorSafe: 'Temporary upload failed' }); throw error; }
    setImmediate(() => { void this.dispatch(context, job.id); });
    return job;
  }
  async get(context: RequestContext, id: string) { const job = await this.store.get(context.workspaceId, id); if (!job) throw new AppError(404, 'NOT_FOUND', 'Outbox job not found'); return job; }
  async cancel(context: RequestContext, id: string) { const job = await this.get(context, id); if (!['pending', 'processing'].includes(job.status)) throw new AppError(409, 'CONFLICT', 'Only pending attachment jobs can be cancelled'); const cancelled = await this.store.update(context.workspaceId, id, { status: 'cancelled', lastErrorSafe: null }); if (job.storageObjectPath) await this.safeRemove(job.storageObjectPath); return cancelled!; }
  async confirm(workspaceId: string, externalMessageId: string) { const job = await this.store.confirm(workspaceId, externalMessageId); if (job?.storageObjectPath) await this.safeRemove(job.storageObjectPath); return job; }
  async cleanupExpired(now = new Date()) { const jobs = await this.store.expired(new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString()); for (const job of jobs) { if (job.storageObjectPath) await this.safeRemove(job.storageObjectPath); await this.store.update(job.workspaceId, job.id, { status: job.status === 'sent' ? 'failed' : job.status, storageObjectPath: null, lastErrorSafe: job.lastErrorSafe ?? 'Temporary upload expired' }); } return jobs.length; }
  private async dispatch(context: RequestContext, id: string): Promise<void> { const job = await this.store.get(context.workspaceId, id); if (!job || job.status !== 'pending' || !job.storageObjectPath || !job.filename || !job.mimeType) return; const processing = await this.store.update(context.workspaceId, id, { status: 'processing', attemptCount: job.attemptCount + 1 }); if (!processing) return; try { const conversation = await this.conversations.getConversation(context.workspaceId, job.conversationId); if (!conversation) throw new AppError(404, 'NOT_FOUND', 'Conversation not found'); const url = await this.storage.signedUrl(job.storageObjectPath, 300); const response = await this.worker.send({ correlationId: context.correlationId, workspaceId: context.workspaceId, command: { type: 'message.sendAttachment', payload: { wahaSession: job.wahaSession, chatId: conversation.deliveryChatId ?? conversation.chatId, type: job.type, url, filename: job.filename, mimeType: job.mimeType, ...(job.caption ? { caption: job.caption } : {}) } } }); if (!response.success) throw new AppError(workerStatus(response.error.code), response.error.code, response.error.message); const sent = response.data as { sentMessage?: { id?: string } }; await this.store.update(context.workspaceId, id, { status: 'sent', externalMessageId: sent.sentMessage?.id ?? null, lastErrorSafe: null }); } catch (error) { const retry = transient(error) && processing.attemptCount < 3; await this.store.update(context.workspaceId, id, { status: retry ? 'pending' : 'failed', lastErrorSafe: safeError(error) }); if (retry) setTimeout(() => { void this.dispatch(context, id); }, 1_000 * processing.attemptCount); } }
  private async safeRemove(path: string) { try { await this.storage.remove(path); } catch { /* cleanup is retried by the scheduled sweep; never expose storage diagnostics */ } }
}
function validateFile(file: UploadFile): AttachmentKind { const type = (Object.keys(policy) as AttachmentKind[]).find(kind => policy[kind].mimes.includes(file.mimetype)); if (!type) throw new AppError(400, 'VALIDATION_ERROR', 'This attachment type is not allowed'); if (!Number.isSafeInteger(file.size) || file.size < 1 || file.size > policy[type].max) throw new AppError(400, 'VALIDATION_ERROR', `Attachment exceeds the ${Math.floor(policy[type].max / 1024 / 1024)} MB limit`); if (!magicMatches(file.buffer, file.mimetype)) throw new AppError(400, 'VALIDATION_ERROR', 'Attachment content does not match its declared type'); return type; }
function magicMatches(data: Buffer, mime: string) { const start = data.subarray(0, 12); const zip = start[0] === 0x50 && start[1] === 0x4b; if (mime === 'image/jpeg') return start[0] === 0xff && start[1] === 0xd8 && start[2] === 0xff; if (mime === 'image/png') return start.subarray(0, 8).equals(Buffer.from([137,80,78,71,13,10,26,10])); if (mime === 'image/webp') return start.subarray(0, 4).toString() === 'RIFF' && data.subarray(8, 12).toString() === 'WEBP'; if (mime === 'audio/ogg') return start.subarray(0, 4).toString() === 'OggS'; if (mime === 'audio/mpeg') return start.subarray(0, 3).toString() === 'ID3' || start[0] === 0xff; if (mime === 'audio/mp4' || mime === 'video/mp4') return data.subarray(4, 8).toString() === 'ftyp'; if (mime === 'audio/webm' || mime === 'video/webm') return start.subarray(0, 4).equals(Buffer.from([0x1a,0x45,0xdf,0xa3])); if (mime === 'application/pdf') return start.subarray(0, 5).toString() === '%PDF-'; if (mime.includes('openxmlformats')) return zip; if (mime === 'text/plain') return !data.subarray(0, Math.min(data.length, 8_192)).includes(0); return false; }
function sanitizeFilename(value: string) { const name = value.normalize('NFKD').replace(/[^A-Za-z0-9._-]+/g, '-').replace(/^[._-]+|[._-]+$/g, '').slice(0, 180); return name || 'attachment'; }
function workerStatus(code: string) { return ({ VALIDATION_ERROR: 400, NOT_FOUND: 404, CONFLICT: 409, TIMEOUT: 504, SERVICE_UNAVAILABLE: 503, PROVIDER_CONTRACT_ERROR: 502 }[code] ?? 503); }
function transient(error: unknown) { return error instanceof AppError && [503, 504].includes(error.status); }
function safeError(error: unknown) { return error instanceof AppError ? error.status >= 500 ? 'Temporary delivery failure' : error.message.slice(0, 240) : 'Temporary delivery failure'; }
function sqliteJob(row: Record<string, unknown>): OutboxJob { return { id: String(row.id), workspaceId: String(row.workspaceId), conversationId: String(row.conversationId), wahaSession: String(row.wahaSession), type: row.type as AttachmentKind, storageObjectPath: row.storageObjectPath as string | null, filename: row.filename as string | null, mimeType: row.mimeType as string | null, sizeBytes: row.sizeBytes as number | null, caption: row.caption as string | null, status: row.status as OutboxStatus, attemptCount: Number(row.attemptCount), externalMessageId: row.externalMessageId as string | null, lastErrorSafe: row.lastErrorSafe as string | null, createdAt: String(row.createdAt), updatedAt: String(row.updatedAt) }; }
function remoteJob(job: OutboxJob) { return { id: job.id, workspace_id: job.workspaceId, conversation_id: job.conversationId, waha_session: job.wahaSession, type: job.type, storage_object_path: job.storageObjectPath, filename: job.filename, mime_type: job.mimeType, size_bytes: job.sizeBytes, caption: job.caption, status: job.status, attempt_count: job.attemptCount, external_message_id: job.externalMessageId, last_error_safe: job.lastErrorSafe, created_at: job.createdAt, updated_at: job.updatedAt }; }
function remoteChanges(changes: Partial<OutboxJob>) { const map: Record<string, string> = { storageObjectPath: 'storage_object_path', mimeType: 'mime_type', sizeBytes: 'size_bytes', attemptCount: 'attempt_count', externalMessageId: 'external_message_id', lastErrorSafe: 'last_error_safe', updatedAt: 'updated_at' }; return Object.fromEntries(Object.entries(changes).filter(([key]) => !['id', 'workspaceId', 'conversationId', 'wahaSession', 'createdAt'].includes(key)).map(([key, value]) => [map[key] ?? key.replace(/[A-Z]/g, item => `_${item.toLowerCase()}`), value]).concat([['updated_at', new Date().toISOString()]])); }
function fromRemote(row: Record<string, unknown>): OutboxJob { return { id: String(row.id), workspaceId: String(row.workspace_id), conversationId: String(row.conversation_id), wahaSession: String(row.waha_session), type: row.type as AttachmentKind, storageObjectPath: row.storage_object_path as string | null, filename: row.filename as string | null, mimeType: row.mime_type as string | null, sizeBytes: row.size_bytes as number | null, caption: row.caption as string | null, status: row.status as OutboxStatus, attemptCount: Number(row.attempt_count), externalMessageId: row.external_message_id as string | null, lastErrorSafe: row.last_error_safe as string | null, createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
