import type { DomainRepository } from '../persistence/domain.repository.js';

/** Validation lives in the provider during this compatibility refactor; this
 * service is now exclusively an asynchronous repository consumer. */
export class DomainService {
  constructor(private readonly repository: DomainRepository) {}
  contacts(w:string,q:Record<string,unknown>){return this.repository.contacts(w,q)} contact(w:string,id:string){return this.repository.contact(w,id)} createContact(w:string,b:unknown){return this.repository.createContact(w,b)} updateContact(w:string,id:string,b:unknown){return this.repository.updateContact(w,id,b)} deleteContact(w:string,id:string){return this.repository.deleteContact(w,id)} importContacts(w:string,b:unknown){return this.repository.importContacts(w,b)} exportContacts(w:string){return this.repository.exportContacts(w)}
  tags(w:string){return this.repository.tags(w)} createTag(w:string,b:unknown){return this.repository.createTag(w,b)} updateTag(w:string,id:string,b:unknown){return this.repository.updateTag(w,id,b)} deleteTag(w:string,id:string){return this.repository.deleteTag(w,id)}
  templates(w:string){return this.repository.templates(w)} template(w:string,id:string){return this.repository.template(w,id)} saveTemplate(w:string,id:string|undefined,b:unknown){return this.repository.saveTemplate(w,id,b)} templateActive(w:string,id:string,a:boolean){return this.repository.templateActive(w,id,a)} deleteTemplate(w:string,id:string){return this.repository.deleteTemplate(w,id)} preview(w:string,id:string,b:unknown){return this.repository.preview(w,id,b)}
  pipelines(w:string){return this.repository.pipelines(w)} savePipeline(w:string,id:string|undefined,b:unknown){return this.repository.savePipeline(w,id,b)} deletePipeline(w:string,id:string){return this.repository.deletePipeline(w,id)} initPipeline(w:string,b:unknown){return this.repository.initPipeline(w,b)} stages(w:string,id:string){return this.repository.stages(w,id)} saveStage(w:string,id:string|undefined,b:unknown){return this.repository.saveStage(w,id,b)} reorderStages(w:string,id:string,b:unknown){return this.repository.reorderStages(w,id,b)} deleteStage(w:string,id:string){return this.repository.deleteStage(w,id)}
  leads(w:string,q:Record<string,unknown>){return this.repository.leads(w,q)} saveLead(w:string,id:string|undefined,b:unknown){return this.repository.saveLead(w,id,b)} deleteLead(w:string,id:string){return this.repository.deleteLead(w,id)} moveLead(w:string,id:string,b:unknown){return this.repository.moveLead(w,id,b)} leadTag(w:string,id:string,t:string,a:boolean){return this.repository.leadTag(w,id,t,a)} note(w:string,id:string,b:unknown){return this.repository.note(w,id,b)} notes(w:string,id:string){return this.repository.notes(w,id)} activities(w:string,id:string){return this.repository.activities(w,id)} funnel(w:string){return this.repository.funnel(w)}
  optOut(w:string,id:string,b:unknown){return this.repository.optOut(w,id,b)} optOutStatus(w:string,id:string){return this.repository.optOutStatus(w,id)} removeOptOut(w:string,id:string){return this.repository.removeOptOut(w,id)} optOutContacts(w:string,q:Record<string,unknown>){return this.repository.optOutContacts(w,q)}
  campaigns(w:string,q:Record<string,unknown>={}){return this.repository.campaigns(w,q)} campaign(w:string,id:string){return this.repository.campaign(w,id)} saveCampaign(w:string,id:string|undefined,b:unknown){return this.repository.saveCampaign(w,id,b)} deleteCampaign(w:string,id:string){return this.repository.deleteCampaign(w,id)} validateCampaign(w:string,id:string){return this.repository.validateCampaign(w,id)} prepareCampaign(w:string,id:string){return this.repository.prepareCampaign(w,id)} scheduleCampaign(w:string,id:string,b:unknown){return this.repository.scheduleCampaign(w,id,b)} cancelCampaign(w:string,id:string){return this.repository.cancelCampaign(w,id)}
  settings(w:string){return this.repository.settings(w)} saveSettings(w:string,b:unknown){return this.repository.saveSettings(w,b)} dashboard(w:string,s:unknown[]=[]){return this.repository.dashboard(w,s)}
}
