import { randomUUID } from 'node:crypto';
import type { SqliteDatabase } from '../persistence/database.js';
import type { RealtimeHub } from '../realtime.js';
import type { SlaService } from './sla.service.js';
import { AppError } from '../errors.js';
import type { KanbanAutomationRequest, KanbanAutomationResult } from './kanban-automation.service.js';

export type KanbanSource = 'manual'|'automation'|'inbound'|'outbound'|'system';
export type KanbanFilters = { assignedUserId?:string; assignedTeamId?:string; queueId?:string; tag?:string; sla?:string; unread?:boolean; type?:'direct'|'group'; search?:string; from?:string; to?:string };
const defaults = [['new','Novo'],['in_progress','Em atendimento'],['waiting_customer','Aguardando cliente'],['waiting_operator','Aguardando operador'],['resolved','Resolvido'],['archived','Arquivado']] as const;
const statusStage: Record<string,string> = { resolved:'resolved', archived:'archived', waiting_customer:'waiting_customer', in_progress:'in_progress', open:'new' };

export class KanbanService {
  constructor(private readonly db: SqliteDatabase, private readonly realtime: RealtimeHub, private readonly sla: SlaService) {}
  async boards(workspaceId:string) { const board = this.ensure(workspaceId); return [this.board(board.id)]; }
  async detail(workspaceId:string, id:string) { const board=this.requireBoard(workspaceId,id); return this.board(board.id); }
  async createBoard(workspaceId:string,name:string) { const now=new Date().toISOString(), id=randomUUID(); this.db.prepare('INSERT INTO kanban_boards (id,workspaceId,name,isDefault,createdAt,updatedAt) VALUES (?,?,?,0,?,?)').run(id,workspaceId,name,now,now); return this.board(id); }
  async createStage(workspaceId:string,boardId:string,input:{key:string;name:string;isTerminal?:boolean;isArchivedStage?:boolean}) { this.requireBoard(workspaceId,boardId); const now=new Date().toISOString(), id=randomUUID(), pos=Number((this.db.prepare('SELECT MAX(position) max FROM kanban_stages WHERE boardId=?').get(boardId) as any).max ?? 0)+1; this.db.prepare('INSERT INTO kanban_stages (id,boardId,key,name,position,isTerminal,isArchivedStage,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?)').run(id,boardId,input.key,input.name,pos,input.isTerminal?1:0,input.isArchivedStage?1:0,now,now); const stage=this.stage(id); this.realtime.publish(workspaceId,'kanban.stage.created',{boardId,stage}); return stage; }
  async updateStage(workspaceId:string,stageId:string,input:{name?:string;isTerminal?:boolean;isArchivedStage?:boolean}) { const stage=this.stage(stageId); this.requireBoard(workspaceId,stage.boardId); const now=new Date().toISOString(); this.db.prepare('UPDATE kanban_stages SET name=?,isTerminal=?,isArchivedStage=?,updatedAt=? WHERE id=?').run(input.name??stage.name,input.isTerminal===undefined?stage.isTerminal:Number(input.isTerminal),input.isArchivedStage===undefined?stage.isArchivedStage:Number(input.isArchivedStage),now,stageId); const next=this.stage(stageId); this.realtime.publish(workspaceId,'kanban.stage.updated',{boardId:stage.boardId,stage:next}); return next; }
  async reorder(workspaceId:string,stageIds:string[]) { if(!stageIds.length) throw new AppError(400,'VALIDATION_ERROR','Stages are required'); const stages=stageIds.map(id=>this.stage(id)); const boardId=stages[0].boardId; this.requireBoard(workspaceId,boardId); if(stages.some(s=>s.boardId!==boardId)) throw new AppError(400,'VALIDATION_ERROR','Stages must belong to the same board'); const now=new Date().toISOString(), run=this.db.transaction(()=>stageIds.forEach((id,i)=>this.db.prepare('UPDATE kanban_stages SET position=?,updatedAt=? WHERE id=?').run(i+1,now,id))); run(); this.realtime.publish(workspaceId,'kanban.stage.reordered',{boardId,stageIds}); }
  async conversations(workspaceId:string,boardId:string,stageId:string,page:number,pageSize:number,filters:KanbanFilters) { this.requireBoard(workspaceId,boardId); const stage=this.stage(stageId); if(stage.boardId!==boardId) throw new AppError(404,'NOT_FOUND','Stage not found'); const states=this.db.prepare(`SELECT s.*, c.lastMessage,c.lastMessageAt,c.unreadCount,c.conversationType,c.assignedUserId,c.assignedTeamId,c.routingQueueId,c.status,c.updatedAt,c.chatId, m.tagsJson, sm.slaStatus FROM conversation_kanban_state s JOIN conversations c ON c.id=s.conversationId AND c.workspaceId=s.workspaceId LEFT JOIN conversation_metadata m ON m.conversationId=c.id AND m.workspaceId=c.workspaceId LEFT JOIN conversation_sla_metrics sm ON sm.conversationId=c.id AND sm.workspaceId=c.workspaceId WHERE s.workspaceId=? AND s.boardId=? AND s.stageId=? AND c.visibilityState='visible' ORDER BY s.position DESC LIMIT ? OFFSET ?`).all(workspaceId,boardId,stageId,pageSize,(page-1)*pageSize) as any[]; const filtered=states.filter(x=>this.filter(x,filters)); const total=Number((this.db.prepare(`SELECT count(*) total FROM conversation_kanban_state s JOIN conversations c ON c.id=s.conversationId AND c.workspaceId=s.workspaceId WHERE s.workspaceId=? AND s.boardId=? AND s.stageId=? AND c.visibilityState='visible'`).get(workspaceId,boardId,stageId) as any).total); return {items:filtered.map(x=>this.card(x)),page,pageSize,total}; }
  async move(workspaceId:string,actorId:string,conversationId:string,input:{boardId:string;stageId:string;beforeConversationId?:string;afterConversationId?:string;source:KanbanSource;expectedUpdatedAt?:string}) { const board=this.requireBoard(workspaceId,input.boardId), stage=this.stage(input.stageId); if(stage.boardId!==board.id) throw new AppError(400,'VALIDATION_ERROR','Stage does not belong to board'); const convo=this.db.prepare("SELECT * FROM conversations WHERE workspaceId=? AND id=? AND visibilityState='visible'").get(workspaceId,conversationId) as any; if(!convo) throw new AppError(404,'NOT_FOUND','Visible conversation not found'); const current=this.db.prepare('SELECT * FROM conversation_kanban_state WHERE workspaceId=? AND conversationId=? AND boardId=?').get(workspaceId,conversationId,board.id) as any; if(input.expectedUpdatedAt && current && current.updatedAt!==input.expectedUpdatedAt) throw new AppError(409,'CONFLICT','Conversation was moved by another operator'); const now=new Date().toISOString(), position=this.position(workspaceId,board.id,stage.id,input.beforeConversationId,input.afterConversationId); const source=input.source; const run=this.db.transaction(()=>{ if(current) this.db.prepare('UPDATE conversation_kanban_state SET stageId=?,position=?,manualOverride=?,lastTransitionSource=?,lastTransitionBy=?,lastTransitionAt=?,updatedAt=? WHERE conversationId=? AND boardId=?').run(stage.id,position,source==='manual'?1:current.manualOverride,source,actorId,now,now,conversationId,board.id); else this.db.prepare('INSERT INTO conversation_kanban_state (workspaceId,conversationId,boardId,stageId,position,manualOverride,lastTransitionSource,lastTransitionBy,lastTransitionAt,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(workspaceId,conversationId,board.id,stage.id,position,source==='manual'?1:0,source,actorId,now,now,now); this.db.prepare('INSERT INTO conversation_kanban_events (id,workspaceId,conversationId,boardId,fromStageId,toStageId,source,actorId,metadataSafe,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),workspaceId,conversationId,board.id,current?.stageId??null,stage.id,source,actorId,'{}',now); }); run(); if(stage.key==='resolved'||stage.key==='archived') await this.sla.status(workspaceId,conversationId,stage.key); const state=this.db.prepare('SELECT * FROM conversation_kanban_state WHERE conversationId=? AND boardId=?').get(conversationId,board.id); this.realtime.publish(workspaceId,'conversation.kanban.moved',{conversationId,boardId:board.id,fromStageId:current?.stageId??null,toStageId:stage.id,state}); return state; }
  async history(workspaceId:string,conversationId:string) { return this.db.prepare('SELECT * FROM conversation_kanban_events WHERE workspaceId=? AND conversationId=? ORDER BY createdAt DESC').all(workspaceId,conversationId); }
  async automated(request: KanbanAutomationRequest): Promise<KanbanAutomationResult> { if (request.historical || request.imported || request.replay || request.technical || request.quarantined || !request.visible) return { status:'skipped', reason:'ineligible_origin' }; const board=this.ensure(request.workspaceId); const current=this.db.prepare('SELECT s.*, k.key stageKey FROM conversation_kanban_state s JOIN kanban_stages k ON k.id=s.stageId WHERE s.workspaceId=? AND s.conversationId=? AND s.boardId=?').get(request.workspaceId,request.conversationId,board.id) as any; if(!current || current.manualOverride) return { status:'skipped', reason:current?.manualOverride?'manual_override':'missing_state' }; const target=request.direction==='inbound'&&current.stageKey==='waiting_customer'?'waiting_operator':request.direction==='outbound'&&['new','waiting_operator','in_progress'].includes(current.stageKey)?'waiting_customer':undefined; if(!target) return { status:'skipped', reason:'stage_rule' }; const claimed=this.db.prepare('INSERT OR IGNORE INTO kanban_automation_deliveries (workspaceId,conversationId,messageId,direction,createdAt) VALUES (?,?,?,?,?)').run(request.workspaceId,request.conversationId,request.messageId,request.direction,new Date().toISOString()); if(!claimed.changes) return { status:'skipped', reason:'duplicate' }; const stage=this.db.prepare('SELECT id FROM kanban_stages WHERE boardId=? AND key=?').get(board.id,target) as {id:string}; await this.move(request.workspaceId,'system:kanban-automation',request.conversationId,{boardId:board.id,stageId:stage.id,source:request.direction}); return { status:'moved' }; }
  private ensure(workspaceId:string) { let board=this.db.prepare('SELECT * FROM kanban_boards WHERE workspaceId=? AND isDefault=1').get(workspaceId) as any; if(board) return board; const now=new Date().toISOString(), id=randomUUID(); const run=this.db.transaction(()=>{ this.db.prepare('INSERT INTO kanban_boards (id,workspaceId,name,isDefault,createdAt,updatedAt) VALUES (?,?,?,1,?,?)').run(id,workspaceId,'Operação',now,now); defaults.forEach(([key,name],i)=>this.db.prepare('INSERT INTO kanban_stages (id,boardId,key,name,position,isTerminal,isArchivedStage,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?)').run(randomUUID(),id,key,name,i+1,key==='resolved'||key==='archived'?1:0,key==='archived'?1:0,now,now)); const stages=this.db.prepare('SELECT id,key FROM kanban_stages WHERE boardId=?').all(id) as any[]; const byKey=Object.fromEntries(stages.map(s=>[s.key,s.id])); const conversations=this.db.prepare("SELECT id,status,workspaceId FROM conversations WHERE workspaceId=? AND visibilityState='visible'").all(workspaceId) as any[]; conversations.forEach((c,i)=>this.db.prepare('INSERT INTO conversation_kanban_state (workspaceId,conversationId,boardId,stageId,position,manualOverride,lastTransitionSource,lastTransitionBy,lastTransitionAt,createdAt,updatedAt) VALUES (?,?,?,?,?,0,\'system\',NULL,?,?,?)').run(workspaceId,c.id,id,byKey[statusStage[c.status]??'new'],i+1,now,now,now)); }); run(); return this.db.prepare('SELECT * FROM kanban_boards WHERE id=?').get(id) as any; }
  private board(id:string) { const board=this.db.prepare('SELECT * FROM kanban_boards WHERE id=?').get(id) as any; const stages=this.db.prepare('SELECT * FROM kanban_stages WHERE boardId=? ORDER BY position').all(id) as any[]; return {...this.mapBoard(board),stages:stages.map(s=>({...this.mapStage(s),count:Number((this.db.prepare("SELECT count(*) total FROM conversation_kanban_state ks JOIN conversations c ON c.id=ks.conversationId AND c.workspaceId=ks.workspaceId WHERE ks.boardId=? AND ks.stageId=? AND c.visibilityState='visible'").get(id,s.id) as any).total)}))}; }
  private requireBoard(workspaceId:string,id:string) { const row=this.db.prepare('SELECT * FROM kanban_boards WHERE id=? AND workspaceId=?').get(id,workspaceId) as any; if(!row) throw new AppError(404,'NOT_FOUND','Board not found'); return row; }
  private stage(id:string):any { const row=this.db.prepare('SELECT * FROM kanban_stages WHERE id=?').get(id) as any; if(!row) throw new AppError(404,'NOT_FOUND','Stage not found'); return this.mapStage(row); }
  private mapBoard(x:any){return {id:x.id,workspaceId:x.workspaceId,name:x.name,isDefault:Boolean(x.isDefault),createdAt:x.createdAt,updatedAt:x.updatedAt};} private mapStage(x:any){return {id:x.id,boardId:x.boardId,key:x.key,name:x.name,position:x.position,isTerminal:Boolean(x.isTerminal),isArchivedStage:Boolean(x.isArchivedStage),createdAt:x.createdAt,updatedAt:x.updatedAt};}
  private card(x:any){let tags:string[]=[];try{tags=JSON.parse(x.tagsJson??'[]')}catch{} return {conversationId:x.conversationId,lastMessage:(x.lastMessage??'').slice(0,180),lastMessageAt:x.lastMessageAt,unreadCount:x.unreadCount,conversationType:x.conversationType,assignedUserId:x.assignedUserId,assignedTeamId:x.assignedTeamId,routingQueueId:x.routingQueueId,tags,slaStatus:x.slaStatus??null,stageId:x.stageId,position:x.position,updatedAt:x.updatedAt,maskedId:x.chatId.replace(/\d(?=\d{4})/g,'•')};}
  private filter(x:any,f:KanbanFilters){ if(f.assignedUserId&&x.assignedUserId!==f.assignedUserId)return false;if(f.assignedTeamId&&x.assignedTeamId!==f.assignedTeamId)return false;if(f.queueId&&x.routingQueueId!==f.queueId)return false;if(f.sla&&x.slaStatus!==f.sla)return false;if(f.unread&&x.unreadCount<1)return false;if(f.type&&x.conversationType!==f.type)return false;if(f.search&&!`${x.chatId} ${x.lastMessage??''}`.toLowerCase().includes(f.search.toLowerCase()))return false;try{if(f.tag&&!JSON.parse(x.tagsJson??'[]').some((t:string)=>t.toLowerCase()===f.tag!.toLowerCase()))return false}catch{} return true; }
  private position(workspaceId:string,boardId:string,stageId:string,before?:string,after?:string){const get=(id?:string)=>id?this.db.prepare('SELECT position FROM conversation_kanban_state WHERE workspaceId=? AND boardId=? AND conversationId=?').get(workspaceId,boardId,id) as any:undefined;const a=get(after)?.position,b=get(before)?.position;if(a!==undefined&&b!==undefined)return (a+b)/2;if(a!==undefined)return a+1;if(b!==undefined)return b-1;return Number((this.db.prepare('SELECT MAX(position) max FROM conversation_kanban_state WHERE workspaceId=? AND boardId=? AND stageId=?').get(workspaceId,boardId,stageId) as any).max??0)+1;}
}
