import { randomUUID } from 'node:crypto';
import type { SqliteDatabase } from '../persistence/database.js';
import type { RoutingStore } from './routing.service.js';
export type RoutingJobStatus='pending'|'processing'|'completed'|'skipped'|'failed'|'cancelled';
export type RoutingJob={id:string;workspaceId:string;conversationId:string;queueId:string;strategy:'round_robin'|'least_loaded'|'manual';status:RoutingJobStatus;attemptCount:number;availableAt:string;lockedAt:string|null;lockedBy:string|null;assignedUserId:string|null;lastErrorSafe:string|null;createdAt:string;updatedAt:string;completedAt:string|null};
const now=()=>new Date().toISOString();
export class SqliteRoutingJobStore {
  constructor(private readonly db:SqliteDatabase){}
  enqueue(workspaceId:string,conversationId:string,queueId:string,strategy:RoutingJob['strategy']){const timestamp=now();const existing=this.db.prepare("SELECT * FROM routing_jobs WHERE workspaceId=? AND conversationId=? AND status IN ('pending','processing')").get(workspaceId,conversationId) as RoutingJob|undefined;if(existing)return existing;const job:RoutingJob={id:randomUUID(),workspaceId,conversationId,queueId,strategy,status:'pending',attemptCount:0,availableAt:timestamp,lockedAt:null,lockedBy:null,assignedUserId:null,lastErrorSafe:null,createdAt:timestamp,updatedAt:timestamp,completedAt:null};this.db.prepare('INSERT INTO routing_jobs (id,workspaceId,conversationId,queueId,strategy,status,attemptCount,availableAt,lockedAt,lockedBy,assignedUserId,lastErrorSafe,createdAt,updatedAt,completedAt) VALUES (@id,@workspaceId,@conversationId,@queueId,@strategy,@status,@attemptCount,@availableAt,@lockedAt,@lockedBy,@assignedUserId,@lastErrorSafe,@createdAt,@updatedAt,@completedAt)').run(job);return job;}
  get(workspaceId:string,id:string){return this.db.prepare('SELECT * FROM routing_jobs WHERE workspaceId=? AND id=?').get(workspaceId,id) as RoutingJob|undefined;}
  cancel(workspaceId:string,conversationId:string,reason='manual_override'){const timestamp=now();this.db.prepare("UPDATE routing_jobs SET status='cancelled',lastErrorSafe=?,updatedAt=?,completedAt=? WHERE workspaceId=? AND conversationId=? AND status IN ('pending','processing')").run(reason,timestamp,timestamp,workspaceId,conversationId);}
  claim(workerId:string,limit:number,lockTimeoutMs:number){const timestamp=now(),expired=new Date(Date.now()-lockTimeoutMs).toISOString();return this.db.transaction(()=>{const jobs=this.db.prepare("SELECT * FROM routing_jobs WHERE (status='pending' AND availableAt<=?) OR (status='processing' AND lockedAt<?) ORDER BY availableAt,id LIMIT ?").all(timestamp,expired,limit) as RoutingJob[];const claim=this.db.prepare("UPDATE routing_jobs SET status='processing',lockedAt=?,lockedBy=?,attemptCount=attemptCount+1,updatedAt=? WHERE id=? AND ((status='pending' AND availableAt<=?) OR (status='processing' AND lockedAt<?))");return jobs.filter(job=>claim.run(timestamp,workerId,timestamp,job.id,timestamp,expired).changes>0).map(job=>({...job,status:'processing' as const,lockedAt:timestamp,lockedBy:workerId,attemptCount:job.attemptCount+1,updatedAt:timestamp}));})();}
  finish(job:RoutingJob,status:Extract<RoutingJobStatus,'completed'|'skipped'|'failed'>,assignedUserId:string|null,lastErrorSafe:string|null){const timestamp=now();this.db.prepare("UPDATE routing_jobs SET status=?,assignedUserId=?,lastErrorSafe=?,updatedAt=?,completedAt=?,lockedAt=NULL,lockedBy=NULL WHERE id=? AND status='processing' AND lockedBy=?").run(status,assignedUserId,lastErrorSafe,timestamp,timestamp,job.id,job.lockedBy);}
  retry(job:RoutingJob,error:string){const timestamp=now();if(job.attemptCount>=3)return this.finish(job,'failed',null,error);const delay=1_000*2**(job.attemptCount-1);this.db.prepare("UPDATE routing_jobs SET status='pending',availableAt=?,lastErrorSafe=?,updatedAt=?,lockedAt=NULL,lockedBy=NULL WHERE id=? AND status='processing' AND lockedBy=?").run(new Date(Date.now()+delay).toISOString(),error,timestamp,job.id,job.lockedBy);}
}
export class RoutingJobProcessor {
  constructor(private readonly jobs:SqliteRoutingJobStore,private readonly routing:RoutingStore){}
  async process(job:RoutingJob){try{const result=await this.routing.distribute(job.workspaceId,job.conversationId,job.queueId);this.jobs.finish(job,result.event.result==='assigned'?'completed':'skipped',result.assignedUserId,result.reasonSafe);return result;}catch(error){const safe=error instanceof Error?error.message.slice(0,240):'routing_worker_error';this.jobs.retry(job,safe);throw error;}}
}
