import { randomUUID } from 'node:crypto';
import type { RequestContext, RoutingEvent, RoutingQueue, RoutingQueueMember } from '@chatpro/contracts';
import type { SupabaseClient } from '@supabase/supabase-js';
import { AppError } from '../errors.js';
import type { SqliteDatabase } from '../persistence/database.js';
import type { RealtimeHub } from '../realtime.js';
import type { ConversationStore } from './waha-webhook.service.js';
import type { WorkspaceDirectoryService } from './workspace-directory.service.js';

export type RoutingDecision = { event: RoutingEvent; assignedUserId: string | null; reasonSafe: string | null };
export type QueueInput = { name: string; description?: string | null; teamId?: string | null; isActive?: boolean; strategy?: RoutingQueue['strategy']; maxOpenConversationsPerAgent?: number | null };
export type MemberInput = { userId: string; priorityWeight?: number; isAvailable?: boolean };
export interface RoutingStore {
  listQueues(workspaceId: string): Promise<RoutingQueue[]>; getQueue(workspaceId: string, queueId: string): Promise<RoutingQueue | undefined>; saveQueue(queue: RoutingQueue): Promise<RoutingQueue>;
  listMembers(workspaceId: string, queueId: string): Promise<RoutingQueueMember[]>; saveMember(workspaceId: string, member: RoutingQueueMember): Promise<RoutingQueueMember>; removeMember(workspaceId: string, queueId: string, userId: string): Promise<boolean>;
  setConversationQueue(workspaceId: string, conversationId: string, queueId: string | null): Promise<boolean>; distribute(workspaceId: string, conversationId: string, queueId: string, force?: boolean): Promise<RoutingDecision>;
}
const stamp = () => new Date().toISOString();
export class RoutingService {
  constructor(private readonly store: RoutingStore, private readonly conversations: ConversationStore, private readonly directory: WorkspaceDirectoryService, private readonly realtime: RealtimeHub) {}
  async list(context: RequestContext) { await this.directory.requireRoutingAdmin(context); return this.store.listQueues(context.workspaceId); }
  async create(context: RequestContext, input: QueueInput) { await this.directory.requireRoutingAdmin(context); if (input.teamId) await this.directory.requireAssignableTeam(context, input.teamId); const now = stamp(); const queue = await this.store.saveQueue({ id: randomUUID(), workspaceId: context.workspaceId, name: input.name, description: input.description ?? null, teamId: input.teamId ?? null, isActive: input.isActive ?? true, strategy: input.strategy ?? 'round_robin', maxOpenConversationsPerAgent: input.maxOpenConversationsPerAgent ?? null, createdAt: now, updatedAt: now }); this.realtime.publish(context.workspaceId, 'routing.queue.created', { queue }); return queue; }
  async update(context: RequestContext, queueId: string, input: Partial<QueueInput>) { await this.directory.requireRoutingAdmin(context); const current = await this.requireQueue(context.workspaceId, queueId); if (input.teamId) await this.directory.requireAssignableTeam(context, input.teamId); const queue = await this.store.saveQueue({ ...current, ...input, updatedAt: stamp() }); this.realtime.publish(context.workspaceId, 'routing.queue.updated', { queue }); return queue; }
  async members(context: RequestContext, queueId: string) { await this.directory.requireRoutingAdmin(context); await this.requireQueue(context.workspaceId, queueId); return this.store.listMembers(context.workspaceId, queueId); }
  async saveMember(context: RequestContext, queueId: string, input: MemberInput) { await this.directory.requireRoutingAdmin(context); const queue = await this.requireQueue(context.workspaceId, queueId); await this.directory.requireAssignableUser(context, input.userId); if (queue.teamId && !(await this.directory.members(context, queue.teamId)).some(member => member.userId === input.userId)) throw new AppError(409, 'CONFLICT', 'Queue members must belong to the linked team'); const existing = (await this.store.listMembers(context.workspaceId, queueId)).find(member => member.userId === input.userId); const now = stamp(); const member = await this.store.saveMember(context.workspaceId, { queueId, userId: input.userId, priorityWeight: input.priorityWeight ?? existing?.priorityWeight ?? 1, isAvailable: input.isAvailable ?? existing?.isAvailable ?? true, lastAssignedAt: existing?.lastAssignedAt ?? null, createdAt: existing?.createdAt ?? now, updatedAt: now }); this.realtime.publish(context.workspaceId, 'routing.queue.members.updated', { queueId, member }); return member; }
  async removeMember(context: RequestContext, queueId: string, userId: string) { await this.directory.requireRoutingAdmin(context); await this.requireQueue(context.workspaceId, queueId); if (!await this.store.removeMember(context.workspaceId, queueId, userId)) throw new AppError(404, 'NOT_FOUND', 'Queue member not found'); this.realtime.publish(context.workspaceId, 'routing.queue.members.updated', { queueId, userId, removed: true }); }
  async moveConversation(context: RequestContext, conversationId: string, queueId: string | null) { await this.directory.requireAssignableUser(context, null); if (queueId) await this.requireQueue(context.workspaceId, queueId); if (!await this.store.setConversationQueue(context.workspaceId, conversationId, queueId)) throw new AppError(404, 'NOT_FOUND', 'Conversation not found'); if (!queueId) return this.publishDecision(context.workspaceId, conversationId, { event: this.event(context.workspaceId, conversationId, null, 'manual', 'manual_override', 'queue_removed'), assignedUserId: null, reasonSafe: 'queue_removed' }); return this.distribute(context, conversationId, queueId); }
  async distribute(context: RequestContext, conversationId: string, queueId: string) { await this.directory.requireAssignableUser(context, null); await this.requireQueue(context.workspaceId, queueId); return this.publishDecision(context.workspaceId, conversationId, await this.store.distribute(context.workspaceId, conversationId, queueId)); }
  async redistribute(context: RequestContext, conversationId: string) { await this.directory.requireAssignableUser(context, null); const conversation = await this.conversations.getConversation(context.workspaceId, conversationId); if (!conversation) throw new AppError(404, 'NOT_FOUND', 'Conversation not found'); if (!conversation.routingQueueId) throw new AppError(409, 'CONFLICT', 'Conversation is not in a routing queue'); return this.publishDecision(context.workspaceId, conversationId, await this.store.distribute(context.workspaceId, conversationId, conversation.routingQueueId, true)); }
  private async publishDecision(workspaceId: string, conversationId: string, decision: RoutingDecision) { const conversation = await this.conversations.getConversation(workspaceId, conversationId); this.realtime.publish(workspaceId, 'conversation.routing.updated', { conversationId, conversation, routing: decision.event }); if (conversation) this.realtime.publish(workspaceId, 'conversation.management.updated', { conversationId, conversation, event: null }); return { conversation, ...decision }; }
  private async requireQueue(workspaceId: string, queueId: string) { const queue = await this.store.getQueue(workspaceId, queueId); if (!queue) throw new AppError(404, 'NOT_FOUND', 'Routing queue not found'); return queue; }
  private event(workspaceId: string, conversationId: string, queueId: string | null, strategy: RoutingQueue['strategy'], result: RoutingEvent['result'], reasonSafe: string | null): RoutingEvent { return { id: randomUUID(), workspaceId, conversationId, queueId, assignedUserId: null, strategy, result, reasonSafe, createdAt: stamp() }; }
}

export class SqliteRoutingStore implements RoutingStore {
  constructor(private readonly db: SqliteDatabase) {}
  async listQueues(workspaceId: string) { return this.db.prepare('SELECT id,workspaceId,teamId,name,description,isActive,strategy,maxOpenConversationsPerAgent,createdAt,updatedAt FROM routing_queues WHERE workspaceId=? ORDER BY name').all(workspaceId).map(queueFromSqlite); }
  async getQueue(workspaceId: string, queueId: string) { const row = this.db.prepare('SELECT id,workspaceId,teamId,name,description,isActive,strategy,maxOpenConversationsPerAgent,createdAt,updatedAt FROM routing_queues WHERE workspaceId=? AND id=?').get(workspaceId, queueId); return row ? queueFromSqlite(row) : undefined; }
  async saveQueue(queue: RoutingQueue) { this.db.prepare('INSERT INTO routing_queues (id,workspaceId,teamId,name,description,isActive,strategy,maxOpenConversationsPerAgent,createdAt,updatedAt) VALUES (@id,@workspaceId,@teamId,@name,@description,@isActive,@strategy,@maxOpenConversationsPerAgent,@createdAt,@updatedAt) ON CONFLICT(id) DO UPDATE SET teamId=excluded.teamId,name=excluded.name,description=excluded.description,isActive=excluded.isActive,strategy=excluded.strategy,maxOpenConversationsPerAgent=excluded.maxOpenConversationsPerAgent,updatedAt=excluded.updatedAt').run({ ...queue, isActive: queue.isActive ? 1 : 0 }); return (await this.getQueue(queue.workspaceId, queue.id))!; }
  async listMembers(workspaceId: string, queueId: string) { return this.db.prepare('SELECT m.queueId,m.userId,m.priorityWeight,m.isAvailable,m.lastAssignedAt,m.createdAt,m.updatedAt FROM routing_queue_members m JOIN routing_queues q ON q.id=m.queueId WHERE q.workspaceId=? AND m.queueId=? ORDER BY m.userId').all(workspaceId, queueId).map(memberFromSqlite); }
  async saveMember(workspaceId: string, member: RoutingQueueMember) { if (!await this.getQueue(workspaceId, member.queueId)) throw new AppError(404, 'NOT_FOUND', 'Routing queue not found'); this.db.prepare('INSERT INTO routing_queue_members (queueId,userId,priorityWeight,isAvailable,lastAssignedAt,createdAt,updatedAt) VALUES (@queueId,@userId,@priorityWeight,@isAvailable,@lastAssignedAt,@createdAt,@updatedAt) ON CONFLICT(queueId,userId) DO UPDATE SET priorityWeight=excluded.priorityWeight,isAvailable=excluded.isAvailable,lastAssignedAt=excluded.lastAssignedAt,updatedAt=excluded.updatedAt').run({ ...member, isAvailable: member.isAvailable ? 1 : 0 }); return member; }
  async removeMember(workspaceId: string, queueId: string, userId: string) { return this.db.prepare('DELETE FROM routing_queue_members WHERE queueId=? AND userId=? AND EXISTS(SELECT 1 FROM routing_queues WHERE id=? AND workspaceId=?)').run(queueId, userId, queueId, workspaceId).changes > 0; }
  async setConversationQueue(workspaceId: string, conversationId: string, queueId: string | null) { return this.db.prepare('UPDATE conversations SET routingQueueId=?, updatedAt=? WHERE workspaceId=? AND id=?').run(queueId, stamp(), workspaceId, conversationId).changes > 0; }
  async distribute(workspaceId: string, conversationId: string, queueId: string, force = false): Promise<RoutingDecision> { return this.db.transaction(() => this.distributeLocked(workspaceId, conversationId, queueId, force))(); }
  private distributeLocked(workspaceId: string, conversationId: string, queueId: string, force: boolean): RoutingDecision {
    const queue = this.db.prepare('SELECT id,workspaceId,teamId,name,description,isActive,strategy,maxOpenConversationsPerAgent,createdAt,updatedAt FROM routing_queues WHERE workspaceId=? AND id=?').get(workspaceId, queueId); const timestamp = stamp();
    if (!queue) return this.record(workspaceId, conversationId, null, queueId, 'round_robin', 'failed', 'queue_not_found', timestamp);
    const q = queueFromSqlite(queue); const conversation = this.db.prepare('SELECT assignedUserId,operationalStatus,routingLockedAt FROM conversations WHERE workspaceId=? AND id=?').get(workspaceId, conversationId) as { assignedUserId: string | null; operationalStatus: string; routingLockedAt: string | null } | undefined;
    if (!conversation) return this.record(workspaceId, conversationId, null, queueId, q.strategy, 'failed', 'conversation_not_found', timestamp);
    if (force) this.db.prepare('UPDATE conversations SET assignedUserId=NULL,assignedAt=NULL,routingLockedAt=NULL,updatedAt=? WHERE workspaceId=? AND id=?').run(timestamp, workspaceId, conversationId);
    const active = force ? { ...conversation, assignedUserId: null, routingLockedAt: null } : conversation;
    if (!q.isActive) return this.record(workspaceId, conversationId, null, queueId, q.strategy, 'skipped', 'queue_inactive', timestamp);
    if (q.strategy === 'manual') return this.record(workspaceId, conversationId, null, queueId, q.strategy, 'skipped', 'manual_strategy', timestamp);
    if (active.assignedUserId || active.routingLockedAt) return this.record(workspaceId, conversationId, active.assignedUserId, queueId, q.strategy, 'skipped', active.assignedUserId ? 'already_assigned' : 'manual_assignment_locked', timestamp);
    if (active.operationalStatus === 'archived' || active.operationalStatus === 'resolved') return this.record(workspaceId, conversationId, null, queueId, q.strategy, 'skipped', 'conversation_not_routable', timestamp);
    const order = q.strategy === 'least_loaded' ? 'openCount ASC, CASE WHEN lastAssignedAt IS NULL THEN 0 ELSE 1 END, lastAssignedAt ASC, userId ASC' : 'CASE WHEN lastAssignedAt IS NULL THEN 0 ELSE 1 END, lastAssignedAt ASC, userId ASC';
    const candidates = this.db.prepare(`SELECT m.userId,m.lastAssignedAt,COUNT(c.id) openCount FROM routing_queue_members m JOIN workspace_users u ON u.id=m.userId AND u.workspaceId=? LEFT JOIN conversations c ON c.workspaceId=? AND c.assignedUserId=m.userId AND c.operationalStatus IN ('open','in_progress','waiting_customer') WHERE m.queueId=? AND m.isAvailable=1 AND u.status='active' ${q.teamId ? 'AND EXISTS (SELECT 1 FROM team_members tm WHERE tm.teamId=? AND tm.userId=m.userId)' : ''} GROUP BY m.userId,m.lastAssignedAt HAVING ? IS NULL OR COUNT(c.id) < ? ORDER BY ${order} LIMIT 1`).all(...(q.teamId ? [workspaceId, workspaceId, queueId, q.teamId, q.maxOpenConversationsPerAgent, q.maxOpenConversationsPerAgent] : [workspaceId, workspaceId, queueId, q.maxOpenConversationsPerAgent, q.maxOpenConversationsPerAgent])) as Array<{ userId: string }>;
    const selected = candidates[0]; if (!selected) return this.record(workspaceId, conversationId, null, queueId, q.strategy, 'skipped', 'no_eligible_agent', timestamp);
    const changed = this.db.prepare("UPDATE conversations SET assignedUserId=?,assignedAt=?,autoAssignedAt=?,routingLockedAt=NULL,updatedAt=? WHERE workspaceId=? AND id=? AND assignedUserId IS NULL AND routingLockedAt IS NULL AND operationalStatus NOT IN ('archived','resolved')").run(selected.userId, timestamp, timestamp, timestamp, workspaceId, conversationId).changes;
    if (!changed) return this.record(workspaceId, conversationId, null, queueId, q.strategy, 'skipped', 'assignment_raced', timestamp);
    this.db.prepare('UPDATE routing_queue_members SET lastAssignedAt=?,updatedAt=? WHERE queueId=? AND userId=?').run(timestamp, timestamp, queueId, selected.userId);
    return this.record(workspaceId, conversationId, selected.userId, queueId, q.strategy, 'assigned', null, timestamp);
  }
  private record(workspaceId: string, conversationId: string, assignedUserId: string | null, queueId: string | null, strategy: RoutingQueue['strategy'], result: RoutingEvent['result'], reasonSafe: string | null, createdAt: string): RoutingDecision { const event: RoutingEvent = { id: randomUUID(), workspaceId, conversationId, queueId, assignedUserId, strategy, result, reasonSafe, createdAt }; this.db.prepare('INSERT INTO routing_events (id,workspaceId,conversationId,queueId,assignedUserId,strategy,result,reasonSafe,createdAt) VALUES (@id,@workspaceId,@conversationId,@queueId,@assignedUserId,@strategy,@result,@reasonSafe,@createdAt)').run(event); return { event, assignedUserId, reasonSafe }; }
}

export class SupabaseRoutingStore implements RoutingStore {
  constructor(private readonly client: SupabaseClient) {}
  async listQueues(workspaceId: string) { const { data, error } = await this.client.from('routing_queues').select('*').eq('workspace_id', workspaceId).order('name'); if (error) throw error; return (data ?? []).map(queueFromRemote); }
  async getQueue(workspaceId: string, queueId: string) { const { data, error } = await this.client.from('routing_queues').select('*').eq('workspace_id', workspaceId).eq('id', queueId).maybeSingle(); if (error) throw error; return data ? queueFromRemote(data) : undefined; }
  async saveQueue(queue: RoutingQueue) { const { error } = await this.client.from('routing_queues').upsert(queueToRemote(queue)); if (error) throw error; return (await this.getQueue(queue.workspaceId, queue.id))!; }
  async listMembers(workspaceId: string, queueId: string) { if (!await this.getQueue(workspaceId, queueId)) return []; const { data, error } = await this.client.from('routing_queue_members').select('*').eq('queue_id', queueId).order('user_id'); if (error) throw error; return (data ?? []).map(memberFromRemote); }
  async saveMember(workspaceId: string, member: RoutingQueueMember) { if (!await this.getQueue(workspaceId, member.queueId)) throw new AppError(404, 'NOT_FOUND', 'Routing queue not found'); const { error } = await this.client.from('routing_queue_members').upsert(memberToRemote(member)); if (error) throw error; return member; }
  async removeMember(workspaceId: string, queueId: string, userId: string) { if (!await this.getQueue(workspaceId, queueId)) return false; const { data, error } = await this.client.from('routing_queue_members').delete().eq('queue_id', queueId).eq('user_id', userId).select('user_id'); if (error) throw error; return Boolean(data?.length); }
  async setConversationQueue(workspaceId: string, conversationId: string, queueId: string | null) { const { data, error } = await this.client.from('conversations').update({ routing_queue_id: queueId, updated_at: stamp() }).eq('workspace_id', workspaceId).eq('id', conversationId).select('id'); if (error) throw error; return Boolean(data?.length); }
  async distribute(workspaceId: string, conversationId: string, queueId: string, force = false): Promise<RoutingDecision> { const { data, error } = await this.client.rpc('chatpro_distribute_conversation', { p_workspace_id: workspaceId, p_conversation_id: conversationId, p_queue_id: queueId, p_force: force }); if (error) throw error; const value = data as { event: Record<string, unknown>; assigned_user_id: string | null; reason_safe: string | null }; return { event: routingEventFromRemote(value.event), assignedUserId: value.assigned_user_id, reasonSafe: value.reason_safe }; }
}
const queueFromSqlite = (row: any): RoutingQueue => ({ ...row, isActive: Boolean(row.isActive), maxOpenConversationsPerAgent: row.maxOpenConversationsPerAgent ?? null });
const memberFromSqlite = (row: any): RoutingQueueMember => ({ ...row, isAvailable: Boolean(row.isAvailable), lastAssignedAt: row.lastAssignedAt ?? null });
const queueFromRemote = (row: any): RoutingQueue => ({ id: row.id, workspaceId: row.workspace_id, teamId: row.team_id, name: row.name, description: row.description, isActive: row.is_active, strategy: row.strategy, maxOpenConversationsPerAgent: row.max_open_conversations_per_agent, createdAt: row.created_at, updatedAt: row.updated_at });
const queueToRemote = (queue: RoutingQueue) => ({ id: queue.id, workspace_id: queue.workspaceId, team_id: queue.teamId, name: queue.name, description: queue.description, is_active: queue.isActive, strategy: queue.strategy, max_open_conversations_per_agent: queue.maxOpenConversationsPerAgent, created_at: queue.createdAt, updated_at: queue.updatedAt });
const memberFromRemote = (row: any): RoutingQueueMember => ({ queueId: row.queue_id, userId: row.user_id, priorityWeight: row.priority_weight, isAvailable: row.is_available, lastAssignedAt: row.last_assigned_at, createdAt: row.created_at, updatedAt: row.updated_at });
const memberToRemote = (member: RoutingQueueMember) => ({ queue_id: member.queueId, user_id: member.userId, priority_weight: member.priorityWeight, is_available: member.isAvailable, last_assigned_at: member.lastAssignedAt, created_at: member.createdAt, updated_at: member.updatedAt });
const routingEventFromRemote = (row: any): RoutingEvent => ({ id: row.id, workspaceId: row.workspace_id, conversationId: row.conversation_id, queueId: row.queue_id, assignedUserId: row.assigned_user_id, strategy: row.strategy, result: row.result, reasonSafe: row.reason_safe, createdAt: row.created_at });
