import type { SupabaseClient } from '@supabase/supabase-js';
import type { SqliteDatabase } from '../persistence/database.js';
import type { RealtimeHub } from '../realtime.js';

export type SlaStatus = 'waiting_operator' | 'waiting_customer' | 'answered' | 'resolved' | 'expired' | 'archived';
export type SlaConfig = { firstResponseThresholdMs: number; operatorWaitingThresholdMs: number; customerWaitingThresholdMs: number; warningRatio: number };
export type SlaMetrics = { conversationId: string; status: SlaStatus; firstInboundAt: string; firstResponseAt: string | null; lastInboundAt: string; lastOutboundAt: string | null; lastActivityAt: string; firstResponseTime: number | null; averageResponseTime: number | null; waitingTime: number; conversationDuration: number; idleTime: number; slaIndicator: 'green' | 'yellow' | 'red'; frozenAt: string | null };
type Row = { workspaceId: string; conversationId: string; slaStatus: SlaStatus; firstInboundAt: string; firstResponseAt: string | null; lastInboundAt: string; lastOutboundAt: string | null; lastActivityAt: string; waitingSinceAt: string | null; operatorWaitingMs: number; customerWaitingMs: number; totalResponseMs: number; responseCount: number; resolvedAt: string | null; archivedAt: string | null; frozenAt: string | null; updatedAt: string };
export interface SlaStore { getConfig(workspaceId: string): Promise<SlaConfig>; saveConfig(workspaceId: string, input: SlaConfig): Promise<SlaConfig>; get(workspaceId: string, conversationId: string): Promise<Row | undefined>; save(row: Row): Promise<void>; listDue(workspaceId?: string): Promise<Row[]>; conversationIdForMessage(workspaceId: string, session: string, messageId: string): Promise<string | undefined>; }
const defaults: SlaConfig = { firstResponseThresholdMs: 300000, operatorWaitingThresholdMs: 900000, customerWaitingThresholdMs: 86400000, warningRatio: .8 };
const ms = (a: string, b: string) => Math.max(0, new Date(a).getTime() - new Date(b).getTime());
export function projectSla(row: Row, config: SlaConfig, now = new Date().toISOString()): SlaMetrics {
  const live = !row.frozenAt && row.waitingSinceAt ? ms(now, row.waitingSinceAt) : 0;
  const operator = row.operatorWaitingMs + (row.slaStatus === 'waiting_operator' || row.slaStatus === 'expired' ? live : 0);
  const customer = row.customerWaitingMs + (row.slaStatus === 'waiting_customer' ? live : 0);
  const waiting = row.slaStatus === 'waiting_customer' ? customer : operator;
  const threshold = row.slaStatus === 'waiting_customer' ? config.customerWaitingThresholdMs : !row.firstResponseAt ? config.firstResponseThresholdMs : config.operatorWaitingThresholdMs;
  const indicator = row.slaStatus === 'expired' || waiting >= threshold ? 'red' : waiting >= threshold * config.warningRatio ? 'yellow' : 'green';
  return { conversationId: row.conversationId, status: row.slaStatus, firstInboundAt: row.firstInboundAt, firstResponseAt: row.firstResponseAt, lastInboundAt: row.lastInboundAt, lastOutboundAt: row.lastOutboundAt, lastActivityAt: row.lastActivityAt, firstResponseTime: row.firstResponseAt ? ms(row.firstResponseAt, row.firstInboundAt) : null, averageResponseTime: row.responseCount ? Math.round(row.totalResponseMs / row.responseCount) : null, waitingTime: waiting, conversationDuration: ms(row.frozenAt ?? now, row.firstInboundAt), idleTime: ms(now, row.lastActivityAt), slaIndicator: indicator, frozenAt: row.frozenAt };
}
export class SlaService {
  constructor(private readonly store: SlaStore, private readonly realtime: RealtimeHub) {}
  async message(workspaceId: string, conversationId: string, direction: 'inbound' | 'outbound', occurredAt: string, historical: boolean) {
    if (historical) return;
    const now = new Date().toISOString(); let row = await this.store.get(workspaceId, conversationId);
    if (!row && direction === 'outbound') return;
    if (!row) row = { workspaceId, conversationId, slaStatus: 'waiting_operator', firstInboundAt: occurredAt, firstResponseAt: null, lastInboundAt: occurredAt, lastOutboundAt: null, lastActivityAt: occurredAt, waitingSinceAt: occurredAt, operatorWaitingMs: 0, customerWaitingMs: 0, totalResponseMs: 0, responseCount: 0, resolvedAt: null, archivedAt: null, frozenAt: null, updatedAt: now };
    if (row.frozenAt) return;
    const elapsed = row.waitingSinceAt ? ms(occurredAt, row.waitingSinceAt) : 0;
    if (direction === 'inbound') { if (row.slaStatus === 'waiting_customer') row.customerWaitingMs += elapsed; else if (row.slaStatus === 'waiting_operator' || row.slaStatus === 'expired') row.operatorWaitingMs += elapsed; row.slaStatus = 'waiting_operator'; row.lastInboundAt = occurredAt; row.waitingSinceAt = occurredAt; }
    else { if (row.slaStatus === 'waiting_operator' || row.slaStatus === 'expired') { row.operatorWaitingMs += elapsed; row.totalResponseMs += ms(occurredAt, row.lastInboundAt); row.responseCount++; if (!row.firstResponseAt) row.firstResponseAt = occurredAt; } row.slaStatus = 'waiting_customer'; row.lastOutboundAt = occurredAt; row.waitingSinceAt = occurredAt; }
    row.lastActivityAt = occurredAt; row.updatedAt = now; await this.store.save(row); await this.publish(workspaceId, row);
  }
  async status(workspaceId: string, conversationId: string, status: 'resolved' | 'archived') { const row = await this.store.get(workspaceId, conversationId); if (!row || row.frozenAt) return; const now = new Date().toISOString(); const elapsed = row.waitingSinceAt ? ms(now, row.waitingSinceAt) : 0; if (row.slaStatus === 'waiting_customer') row.customerWaitingMs += elapsed; else row.operatorWaitingMs += elapsed; row.slaStatus = status; row.waitingSinceAt = null; row.frozenAt = now; row.resolvedAt = status === 'resolved' ? now : null; row.archivedAt = status === 'archived' ? now : null; row.updatedAt = now; await this.store.save(row); await this.publish(workspaceId, row); }
  async metrics(workspaceId: string, conversationId: string) { const row = await this.store.get(workspaceId, conversationId); return row ? projectSla(row, await this.store.getConfig(workspaceId)) : undefined; }
  async summary(workspaceId: string) { const rows = await this.store.listDue(workspaceId); const config = await this.store.getConfig(workspaceId); const values = rows.map(row => projectSla(row, config)); return { total: values.length, waitingOperator: values.filter(x => x.status === 'waiting_operator' || x.status === 'expired').length, waitingCustomer: values.filter(x => x.status === 'waiting_customer').length, expired: values.filter(x => x.slaIndicator === 'red').length, metrics: values }; }
  async config(workspaceId: string, input?: Partial<SlaConfig>) { if (!input) return this.store.getConfig(workspaceId); return this.store.saveConfig(workspaceId, { ...await this.store.getConfig(workspaceId), ...input }); }
  async tick() { for (const row of await this.store.listDue()) { const config = await this.store.getConfig(row.workspaceId); const projected = projectSla(row, config); if (projected.slaIndicator === 'red' && row.slaStatus !== 'expired') { row.slaStatus = 'expired'; row.updatedAt = new Date().toISOString(); await this.store.save(row); await this.publish(row.workspaceId, row); } } }
  private async publish(workspaceId: string, row: Row) { this.realtime.publish(workspaceId, 'conversation.sla.updated', { conversationId: row.conversationId, metrics: projectSla(row, await this.store.getConfig(workspaceId)) }); }
}
export class SqliteSlaStore implements SlaStore {
  constructor(private readonly db: SqliteDatabase) {}
  async getConfig(workspaceId: string) { const row = this.db.prepare('SELECT * FROM workspace_sla_config WHERE workspaceId = ?').get(workspaceId) as Record<string, unknown> | undefined; if (!row) return defaults; return { firstResponseThresholdMs: Number(row.firstResponseThresholdMs), operatorWaitingThresholdMs: Number(row.operatorWaitingThresholdMs), customerWaitingThresholdMs: Number(row.customerWaitingThresholdMs), warningRatio: Number(row.warningRatio) }; }
  async saveConfig(workspaceId: string, input: SlaConfig) { this.db.prepare('INSERT INTO workspace_sla_config (workspaceId, firstResponseThresholdMs, operatorWaitingThresholdMs, customerWaitingThresholdMs, warningRatio, updatedAt) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(workspaceId) DO UPDATE SET firstResponseThresholdMs=excluded.firstResponseThresholdMs, operatorWaitingThresholdMs=excluded.operatorWaitingThresholdMs, customerWaitingThresholdMs=excluded.customerWaitingThresholdMs, warningRatio=excluded.warningRatio, updatedAt=excluded.updatedAt').run(workspaceId, input.firstResponseThresholdMs, input.operatorWaitingThresholdMs, input.customerWaitingThresholdMs, input.warningRatio, new Date().toISOString()); return input; }
  async get(workspaceId: string, conversationId: string) { return this.db.prepare('SELECT * FROM conversation_sla_metrics WHERE workspaceId=? AND conversationId=?').get(workspaceId, conversationId) as Row | undefined; }
  async save(row: Row) { const keys = Object.keys(row); this.db.prepare(`INSERT INTO conversation_sla_metrics (${keys.join(',')}) VALUES (${keys.map(k => '@' + k).join(',')}) ON CONFLICT(workspaceId,conversationId) DO UPDATE SET ${keys.filter(k => !['workspaceId','conversationId'].includes(k)).map(k => `${k}=excluded.${k}`).join(',')}`).run(row); }
  async listDue(workspaceId?: string) { return this.db.prepare(`SELECT * FROM conversation_sla_metrics WHERE frozenAt IS NULL${workspaceId ? ' AND workspaceId = ?' : ''}`).all(...(workspaceId ? [workspaceId] : [])) as Row[]; }
  async conversationIdForMessage(workspaceId: string, session: string, messageId: string) { const row = this.db.prepare('SELECT c.id FROM whatsapp_messages m JOIN conversations c ON c.workspaceId=m.workspaceId AND c.wahaSession=m.wahaSession AND c.chatId=m.chatId WHERE m.workspaceId=? AND m.wahaSession=? AND m.externalMessageId=?').get(workspaceId, session, messageId) as { id: string } | undefined; return row?.id; }
}
export class SupabaseSlaStore implements SlaStore {
  constructor(private readonly client: SupabaseClient) {}
  async getConfig(workspaceId: string) { const { data, error } = await this.client.from('workspace_sla_config').select('*').eq('workspace_id', workspaceId).maybeSingle(); if (error) throw error; return data ? { firstResponseThresholdMs: Number(data.first_response_threshold_ms), operatorWaitingThresholdMs: Number(data.operator_waiting_threshold_ms), customerWaitingThresholdMs: Number(data.customer_waiting_threshold_ms), warningRatio: Number(data.warning_ratio) } : defaults; }
  async saveConfig(workspaceId: string, input: SlaConfig) { const { error } = await this.client.from('workspace_sla_config').upsert({ workspace_id: workspaceId, first_response_threshold_ms: input.firstResponseThresholdMs, operator_waiting_threshold_ms: input.operatorWaitingThresholdMs, customer_waiting_threshold_ms: input.customerWaitingThresholdMs, warning_ratio: input.warningRatio, updated_at: new Date().toISOString() }); if (error) throw error; return input; }
  async get(workspaceId: string, conversationId: string) { const { data, error } = await this.client.from('conversation_sla_metrics').select('*').eq('workspace_id', workspaceId).eq('conversation_id', conversationId).maybeSingle(); if (error) throw error; return data ? fromRemote(data) : undefined; }
  async save(row: Row) { const { error } = await this.client.from('conversation_sla_metrics').upsert(toRemote(row)); if (error) throw error; }
  async listDue(workspaceId?: string) { let q = this.client.from('conversation_sla_metrics').select('*').is('frozen_at', null); if (workspaceId) q = q.eq('workspace_id', workspaceId); const { data, error } = await q; if (error) throw error; return (data ?? []).map(fromRemote); }
  async conversationIdForMessage(workspaceId: string, session: string, messageId: string) { const { data: message, error } = await this.client.from('whatsapp_messages').select('chat_id').eq('workspace_id', workspaceId).eq('waha_session', session).eq('external_message_id', messageId).maybeSingle(); if (error) throw error; if (!message) return undefined; const { data, error: conversationError } = await this.client.from('conversations').select('id').eq('workspace_id', workspaceId).eq('waha_session', session).eq('chat_id', message.chat_id).maybeSingle(); if (conversationError) throw conversationError; return data?.id; }
}
function toRemote(r: Row) { return { workspace_id:r.workspaceId, conversation_id:r.conversationId, sla_status:r.slaStatus, first_inbound_at:r.firstInboundAt, first_response_at:r.firstResponseAt, last_inbound_at:r.lastInboundAt, last_outbound_at:r.lastOutboundAt, last_activity_at:r.lastActivityAt, waiting_since_at:r.waitingSinceAt, operator_waiting_ms:r.operatorWaitingMs, customer_waiting_ms:r.customerWaitingMs, total_response_ms:r.totalResponseMs, response_count:r.responseCount, resolved_at:r.resolvedAt, archived_at:r.archivedAt, frozen_at:r.frozenAt, updated_at:r.updatedAt }; }
function fromRemote(r: Record<string, unknown>): Row { return { workspaceId:r.workspace_id as string, conversationId:r.conversation_id as string, slaStatus:r.sla_status as SlaStatus, firstInboundAt:r.first_inbound_at as string, firstResponseAt:r.first_response_at as string | null, lastInboundAt:r.last_inbound_at as string, lastOutboundAt:r.last_outbound_at as string | null, lastActivityAt:r.last_activity_at as string, waitingSinceAt:r.waiting_since_at as string | null, operatorWaitingMs:Number(r.operator_waiting_ms), customerWaitingMs:Number(r.customer_waiting_ms), totalResponseMs:Number(r.total_response_ms), responseCount:Number(r.response_count), resolvedAt:r.resolved_at as string | null, archivedAt:r.archived_at as string | null, frozenAt:r.frozen_at as string | null, updatedAt:r.updated_at as string }; }
