import { randomUUID } from 'node:crypto';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { RealtimeHub } from '../realtime.js';
import { projectSlaCard, type SlaService } from './sla.service.js';
import { AppError } from '../errors.js';
import type { KanbanFilters, KanbanSource } from './kanban.service.js';
import type { KanbanAutomationRequest, KanbanAutomationResult } from './kanban-automation.service.js';
import { isKanbanConflict, kanbanRetry, kanbanRetryDelayMs, type KanbanRetry } from './kanban-conflict.js';

const defaults = [['new', 'Novo'], ['in_progress', 'Em atendimento'], ['waiting_customer', 'Aguardando cliente'], ['waiting_operator', 'Aguardando operador'], ['resolved', 'Resolvido'], ['archived', 'Arquivado']] as const;
const mapped: Record<string, string> = { open: 'new', in_progress: 'in_progress', waiting_customer: 'waiting_customer', resolved: 'resolved', archived: 'archived' };
const fail = (error: any) => { throw new AppError(error?.code === '40001' ? 409 : 500, error?.code === '40001' ? 'CONFLICT' : 'SERVICE_UNAVAILABLE', error?.message ?? 'Kanban persistence failed'); };

export class SupabaseKanbanService {
  constructor(private readonly client: SupabaseClient, private readonly realtime: RealtimeHub, private readonly sla: SlaService, private readonly retry: KanbanRetry = kanbanRetry()) {}
  async boards(workspaceId: string) { return [await this.ensure(workspaceId)]; }
  async detail(workspaceId: string, id: string) { const board = await this.board(workspaceId, id); if (!board) throw new AppError(404, 'NOT_FOUND', 'Board not found'); return board; }
  async createBoard(workspaceId: string, name: string) { const now = new Date().toISOString(), id = randomUUID(); const { error } = await this.client.from('kanban_boards').insert({ id, workspace_id: workspaceId, name, is_default: false, created_at: now, updated_at: now }); if (error) fail(error); return this.detail(workspaceId, id); }
  async createStage(workspaceId: string, boardId: string, input: any) { await this.detail(workspaceId, boardId); const { data, error } = await this.client.from('kanban_stages').select('position').eq('board_id', boardId).order('position', { ascending: false }).limit(1); if (error) fail(error); const stage = { id: randomUUID(), board_id: boardId, key: input.key, name: input.name, position: Number(data?.[0]?.position ?? 0) + 1, is_terminal: !!input.isTerminal, is_archived_stage: !!input.isArchivedStage, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }; const result = await this.client.from('kanban_stages').insert(stage); if (result.error) fail(result.error); const output = this.stage(stage); this.realtime.publish(workspaceId, 'kanban.stage.created', { boardId, stage: output }); return output; }
  async updateStage(workspaceId: string, stageId: string, input: any) { const stage = await this.requireStage(workspaceId, stageId); const { error } = await this.client.from('kanban_stages').update({ name: input.name ?? stage.name, is_terminal: input.isTerminal ?? stage.isTerminal, is_archived_stage: input.isArchivedStage ?? stage.isArchivedStage, updated_at: new Date().toISOString() }).eq('id', stageId); if (error) fail(error); const output = { ...stage, ...input }; this.realtime.publish(workspaceId, 'kanban.stage.updated', { boardId: stage.boardId, stage: output }); return output; }
  async reorder(workspaceId: string, stageIds: string[]) { const stages = await Promise.all(stageIds.map((id) => this.requireStage(workspaceId, id))); if (!stages.length || stages.some((stage) => stage.boardId !== stages[0].boardId)) throw new AppError(400, 'VALIDATION_ERROR', 'Invalid stages'); for (const [index, id] of stageIds.entries()) { const { error } = await this.client.from('kanban_stages').update({ position: index + 1, updated_at: new Date().toISOString() }).eq('id', id); if (error) fail(error); } this.realtime.publish(workspaceId, 'kanban.stage.reordered', { boardId: stages[0].boardId, stageIds }); }
  async conversations(workspaceId: string, boardId: string, stageId: string, page: number, pageSize: number, filters: KanbanFilters) {
    await this.detail(workspaceId, boardId); const stage = await this.requireStage(workspaceId, stageId); if (stage.boardId !== boardId) throw new AppError(404, 'NOT_FOUND', 'Stage not found');
    const from = (page - 1) * pageSize;
    let query = this.client.from('conversation_kanban_state').select('conversation_id,stage_id,position,updated_at,conversations!inner(id,workspace_id,visibility_state,chat_id,last_message,last_message_at,unread_count,conversation_type,assigned_user_id,assigned_team_id,routing_queue_id,priority),conversation_metadata(tags),conversation_sla_metrics(sla_status,waiting_since_at,first_response_at,frozen_at)', { count: 'exact' }).eq('workspace_id', workspaceId).eq('board_id', boardId).eq('stage_id', stageId).eq('conversations.visibility_state', 'visible').order('position', { ascending: false }).range(from, from + pageSize - 1);
    if (filters.unread) query = query.gt('conversations.unread_count', 0); if (filters.type) query = query.eq('conversations.conversation_type', filters.type);
    const { data, error, count } = await query; if (error) fail(error);
    const rows = (data ?? []).filter((row: any) => !filters.search || `${row.conversations.chat_id} ${row.conversations.last_message ?? ''}`.toLowerCase().includes(filters.search.toLowerCase()));
    const config = rows.some((row: any) => row.conversation_sla_metrics) ? await this.sla.config(workspaceId) : undefined;
    return { items: rows.map((row: any) => { const metric = Array.isArray(row.conversation_sla_metrics) ? row.conversation_sla_metrics[0] : row.conversation_sla_metrics; return { conversationId: row.conversation_id, stageId: row.stage_id, position: Number(row.position), updatedAt: row.updated_at, maskedId: row.conversations.chat_id.replace(/\d(?=\d{4})/g, '•'), lastMessage: (row.conversations.last_message ?? '').slice(0, 180), lastMessageAt: row.conversations.last_message_at, unreadCount: row.conversations.unread_count, conversationType: row.conversations.conversation_type, assignedUserId: row.conversations.assigned_user_id, assignedTeamId: row.conversations.assigned_team_id, routingQueueId: row.conversations.routing_queue_id, priority: row.conversations.priority, tags: row.conversation_metadata?.tags ?? [], slaStatus: metric?.sla_status ?? null, sla: metric && config ? projectSlaCard({ slaStatus: metric.sla_status, waitingSinceAt: metric.waiting_since_at, firstResponseAt: metric.first_response_at, frozenAt: metric.frozen_at }, config) : null }; }), page, pageSize, total: count ?? 0 };
  }
  async move(workspaceId: string, actorId: string, conversationId: string, input: any) { const stage = await this.requireStage(workspaceId, input.stageId); const position = await this.position(workspaceId, input.boardId, stage.id, input.beforeConversationId, input.afterConversationId); const { data, error } = await this.client.rpc('chatpro_kanban_move', { p_workspace_id: workspaceId, p_conversation_id: conversationId, p_board_id: input.boardId, p_stage_id: input.stageId, p_position: position, p_source: input.source as KanbanSource, p_actor_id: actorId, p_expected_updated_at: input.expectedUpdatedAt ?? null }); if (error) fail(error); await this.sla.applyOperationalStatus(workspaceId, conversationId, stage.key); const row = Array.isArray(data) ? data[0] : data; this.realtime.publish(workspaceId, 'conversation.kanban.moved', { conversationId, boardId: input.boardId, fromStageId: row?.from_stage_id ?? null, toStageId: stage.id, state: { updatedAt: row?.updated_at } }); return row; }
  async history(workspaceId: string, conversationId: string) { const { data, error } = await this.client.from('conversation_kanban_events').select('*').eq('workspace_id', workspaceId).eq('conversation_id', conversationId).order('created_at', { ascending: false }); if (error) fail(error); return data ?? []; }
  async automated(request: KanbanAutomationRequest): Promise<KanbanAutomationResult> {
    if (request.historical || request.imported || request.replay || request.technical || request.quarantined || !request.visible) return { status: 'skipped', reason: 'ineligible_origin' };
    const board = (await this.boards(request.workspaceId))[0];
    let claimed = false;
    // Each attempt re-reads the state, so the retry asks a fresh question. The
    // message is claimed once: it is the same delivery being settled, not a new one.
    for (let attempt = 1; attempt <= this.retry.attempts; attempt += 1) {
      const { data, error } = await this.client.from('conversation_kanban_state').select('stage_id,manual_override,updated_at,kanban_stages!inner(key)').eq('workspace_id', request.workspaceId).eq('conversation_id', request.conversationId).eq('board_id', board.id).maybeSingle(); if (error) fail(error);
      if (!data || data.manual_override) return { status: 'skipped', reason: data?.manual_override ? 'manual_override' : 'missing_state' };
      const key = (data.kanban_stages as any).key, target = request.direction === 'inbound' && key === 'waiting_customer' ? 'waiting_operator' : request.direction === 'outbound' && ['new', 'waiting_operator', 'in_progress'].includes(key) ? 'waiting_customer' : undefined;
      if (!target) return { status: 'skipped', reason: 'stage_rule' };
      if (!claimed) { const claim = await this.client.from('kanban_automation_deliveries').insert({ workspace_id: request.workspaceId, conversation_id: request.conversationId, message_id: request.messageId, direction: request.direction }); if (claim.error?.code === '23505') return { status: 'skipped', reason: 'duplicate' }; if (claim.error) fail(claim.error); claimed = true; }
      const next = board.stages.find((item: any) => item.key === target);
      if (!next) return { status: 'skipped', reason: 'missing_target' };
      try { await this.move(request.workspaceId, '00000000-0000-4000-8000-000000000001', request.conversationId, { boardId: board.id, stageId: next.id, source: request.direction, expectedUpdatedAt: data.updated_at }); return { status: 'moved' }; }
      catch (moveError) { if (!isKanbanConflict(moveError) || attempt === this.retry.attempts) throw moveError; await this.retry.sleep(kanbanRetryDelayMs(attempt, this.retry.random)); }
    }
    return { status: 'failed', reason: 'conflict_exhausted' };
  }
  private async ensure(workspaceId: string): Promise<any> { const now = new Date().toISOString(); const { data: existing, error: findError } = await this.client.from('kanban_boards').select('*').eq('workspace_id', workspaceId).eq('is_default', true).maybeSingle(); if (findError) fail(findError); let id = existing?.id; if (!id) { id = randomUUID(); const result = await this.client.from('kanban_boards').insert({ id, workspace_id: workspaceId, name: 'Operação', is_default: true, created_at: now, updated_at: now }); if (result.error) { const retry = await this.client.from('kanban_boards').select('*').eq('workspace_id', workspaceId).eq('is_default', true).single(); if (retry.error) fail(retry.error); id = retry.data.id; } } const found = await this.client.from('kanban_stages').select('id,key,position').eq('board_id', id); if (found.error) fail(found.error); const known = new Set((found.data ?? []).map((stage: any) => stage.key)); let position = Math.max(0, ...(found.data ?? []).map((stage: any) => Number(stage.position))); const missing = defaults.filter(([key]) => !known.has(key)).map(([key, name]) => ({ id: randomUUID(), board_id: id!, key, name, position: ++position, is_terminal: key === 'resolved' || key === 'archived', is_archived_stage: key === 'archived', created_at: now, updated_at: now })); if (missing.length) { const inserted = await this.client.from('kanban_stages').insert(missing); if (inserted.error) fail(inserted.error); } const stages = await this.client.from('kanban_stages').select('id,key').eq('board_id', id); if (stages.error) fail(stages.error); const byKey = Object.fromEntries((stages.data ?? []).map((stage: any) => [stage.key, stage.id])); const visible = await this.client.from('conversations').select('id,status').eq('workspace_id', workspaceId).eq('visibility_state', 'visible'); if (visible.error) fail(visible.error); const states = (visible.data ?? []).map((conversation: any, index: number) => ({ workspace_id: workspaceId, conversation_id: conversation.id, board_id: id, stage_id: byKey[mapped[conversation.status] ?? 'new'], position: index + 1, manual_override: false, last_transition_source: 'system', last_transition_by: null, last_transition_at: now, created_at: now, updated_at: now })); if (states.length) { const inserted = await this.client.from('conversation_kanban_state').upsert(states, { onConflict: 'conversation_id,board_id', ignoreDuplicates: true }); if (inserted.error) fail(inserted.error); } return this.detail(workspaceId, id); }
  private async board(workspaceId: string, id: string) { const { data, error } = await this.client.from('kanban_boards').select('*,kanban_stages(*)').eq('workspace_id', workspaceId).eq('id', id).maybeSingle(); if (error) fail(error); if (!data) return undefined; const stages = await Promise.all((data.kanban_stages ?? []).sort((a: any, b: any) => Number(a.position) - Number(b.position)).map(async (stage: any) => { const result = await this.client.from('conversation_kanban_state').select('conversation_id', { count: 'exact', head: true }).eq('workspace_id', workspaceId).eq('board_id', id).eq('stage_id', stage.id); if (result.error) fail(result.error); return { ...this.stage(stage), count: result.count ?? 0 }; })); return { id: data.id, workspaceId: data.workspace_id, name: data.name, isDefault: data.is_default, createdAt: data.created_at, updatedAt: data.updated_at, stages }; }
  private async requireStage(workspaceId: string, id: string) { const { data, error } = await this.client.from('kanban_stages').select('*,kanban_boards!inner(workspace_id)').eq('id', id).maybeSingle(); if (error) fail(error); if (!data || (data.kanban_boards as any).workspace_id !== workspaceId) throw new AppError(404, 'NOT_FOUND', 'Stage not found'); return this.stage(data); }
  private stage(value: any) { return { id: value.id, boardId: value.board_id, key: value.key, name: value.name, position: Number(value.position), isTerminal: !!value.is_terminal, isArchivedStage: !!value.is_archived_stage, createdAt: value.created_at, updatedAt: value.updated_at }; }
  private async position(workspaceId: string, boardId: string, stageId: string, before?: string, after?: string) { const get = async (id?: string) => { if (!id) return undefined; const { data, error } = await this.client.from('conversation_kanban_state').select('position').eq('workspace_id', workspaceId).eq('board_id', boardId).eq('conversation_id', id).maybeSingle(); if (error) fail(error); return data; }; const [afterRow, beforeRow] = await Promise.all([get(after), get(before)]); if (afterRow?.position !== undefined && beforeRow?.position !== undefined) return (Number(afterRow.position) + Number(beforeRow.position)) / 2; if (afterRow?.position !== undefined) return Number(afterRow.position) + 1; if (beforeRow?.position !== undefined) return Number(beforeRow.position) - 1; const { data, error } = await this.client.from('conversation_kanban_state').select('position').eq('workspace_id', workspaceId).eq('board_id', boardId).eq('stage_id', stageId).order('position', { ascending: false }).limit(1); if (error) fail(error); return Number(data?.[0]?.position ?? 0) + 1; }
}
