import { randomUUID } from 'node:crypto';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { RealtimeHub } from '../realtime.js';
import type { SlaService } from './sla.service.js';
import { AppError } from '../errors.js';
import type { KanbanFilters, KanbanSource } from './kanban.service.js';
import type { KanbanAutomationRequest, KanbanAutomationResult } from './kanban-automation.service.js';
const defaults=[['new','Novo'],['in_progress','Em atendimento'],['waiting_customer','Aguardando cliente'],['waiting_operator','Aguardando operador'],['resolved','Resolvido'],['archived','Arquivado']] as const;
const mapped:Record<string,string>={open:'new',in_progress:'in_progress',waiting_customer:'waiting_customer',resolved:'resolved',archived:'archived'};
const fail=(e:any)=>{throw new AppError(e?.code==='40001'?409:500,e?.code==='40001'?'CONFLICT':'SERVICE_UNAVAILABLE',e?.message??'Kanban persistence failed');};
export class SupabaseKanbanService {
  constructor(private readonly client:SupabaseClient,private readonly realtime:RealtimeHub,private readonly sla:SlaService){}
  async boards(workspaceId:string){return [await this.ensure(workspaceId)];}
  async detail(workspaceId:string,id:string){const board=await this.board(workspaceId,id);if(!board)throw new AppError(404,'NOT_FOUND','Board not found');return board;}
  async createBoard(workspaceId:string,name:string){const now=new Date().toISOString(),id=randomUUID();const {error}=await this.client.from('kanban_boards').insert({id,workspace_id:workspaceId,name,is_default:false,created_at:now,updated_at:now});if(error)fail(error);return this.detail(workspaceId,id);}
  async createStage(workspaceId:string,boardId:string,input:any){await this.detail(workspaceId,boardId);const {data,error}=await this.client.from('kanban_stages').select('position').eq('board_id',boardId).order('position',{ascending:false}).limit(1);if(error)fail(error);const stage={id:randomUUID(),board_id:boardId,key:input.key,name:input.name,position:Number(data?.[0]?.position??0)+1,is_terminal:!!input.isTerminal,is_archived_stage:!!input.isArchivedStage,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};const result=await this.client.from('kanban_stages').insert(stage);if(result.error)fail(result.error);const output=this.stage(stage);this.realtime.publish(workspaceId,'kanban.stage.created',{boardId,stage:output});return output;}
  async updateStage(workspaceId:string,stageId:string,input:any){const stage=await this.requireStage(workspaceId,stageId);const {error}=await this.client.from('kanban_stages').update({name:input.name??stage.name,is_terminal:input.isTerminal??stage.isTerminal,is_archived_stage:input.isArchivedStage??stage.isArchivedStage,updated_at:new Date().toISOString()}).eq('id',stageId);if(error)fail(error);const output={...stage,...input};this.realtime.publish(workspaceId,'kanban.stage.updated',{boardId:stage.boardId,stage:output});return output;}
  async reorder(workspaceId:string,stageIds:string[]){const stages=await Promise.all(stageIds.map(id=>this.requireStage(workspaceId,id)));if(!stages.length||stages.some(x=>x.boardId!==stages[0].boardId))throw new AppError(400,'VALIDATION_ERROR','Invalid stages');for(const [i,id] of stageIds.entries()){const {error}=await this.client.from('kanban_stages').update({position:i+1,updated_at:new Date().toISOString()}).eq('id',id);if(error)fail(error);}this.realtime.publish(workspaceId,'kanban.stage.reordered',{boardId:stages[0].boardId,stageIds});}
  async conversations(workspaceId:string,boardId:string,stageId:string,page:number,pageSize:number,filters:KanbanFilters){await this.detail(workspaceId,boardId);const stage=await this.requireStage(workspaceId,stageId);if(stage.boardId!==boardId)throw new AppError(404,'NOT_FOUND','Stage not found');const from=(page-1)*pageSize;let q=this.client.from('conversation_kanban_state').select('conversation_id,stage_id,position,updated_at,conversations!inner(id,workspace_id,visibility_state,chat_id,last_message,last_message_at,unread_count,conversation_type,assigned_user_id,assigned_team_id,routing_queue_id),conversation_metadata(tags),conversation_sla_metrics(sla_status)',{count:'exact'}).eq('workspace_id',workspaceId).eq('board_id',boardId).eq('stage_id',stageId).eq('conversations.visibility_state','visible').order('position',{ascending:false}).range(from,from+pageSize-1);if(filters.unread)q=q.gt('conversations.unread_count',0);if(filters.type)q=q.eq('conversations.conversation_type',filters.type);const {data,error,count}=await q;if(error)fail(error);const items=(data??[]).filter((x:any)=>!filters.search||`${x.conversations.chat_id} ${x.conversations.last_message??''}`.toLowerCase().includes(filters.search.toLowerCase())).map((x:any)=>({conversationId:x.conversation_id,stageId:x.stage_id,position:Number(x.position),updatedAt:x.updated_at,maskedId:x.conversations.chat_id.replace(/\d(?=\d{4})/g,'•'),lastMessage:(x.conversations.last_message??'').slice(0,180),lastMessageAt:x.conversations.last_message_at,unreadCount:x.conversations.unread_count,conversationType:x.conversations.conversation_type,assignedUserId:x.conversations.assigned_user_id,assignedTeamId:x.conversations.assigned_team_id,routingQueueId:x.conversations.routing_queue_id,tags:x.conversation_metadata?.tags??[],slaStatus:x.conversation_sla_metrics?.sla_status??null}));return {items,page,pageSize,total:count??0};}
  async move(workspaceId:string,actorId:string,conversationId:string,input:any){const stage=await this.requireStage(workspaceId,input.stageId);const position=await this.nextPosition(workspaceId,input.boardId,stage.id);const {data,error}=await this.client.rpc('chatpro_kanban_move',{p_workspace_id:workspaceId,p_conversation_id:conversationId,p_board_id:input.boardId,p_stage_id:input.stageId,p_position:position,p_source:input.source as KanbanSource,p_actor_id:actorId,p_expected_updated_at:input.expectedUpdatedAt??null});if(error)fail(error);if(stage.key==='resolved'||stage.key==='archived')await this.sla.status(workspaceId,conversationId,stage.key);const row=Array.isArray(data)?data[0]:data;this.realtime.publish(workspaceId,'conversation.kanban.moved',{conversationId,boardId:input.boardId,fromStageId:row?.from_stage_id??null,toStageId:stage.id,state:{updatedAt:row?.updated_at}});return row;}
  async history(workspaceId:string,conversationId:string){const {data,error}=await this.client.from('conversation_kanban_events').select('*').eq('workspace_id',workspaceId).eq('conversation_id',conversationId).order('created_at',{ascending:false});if(error)fail(error);return data??[];}
  async automated(request:KanbanAutomationRequest):Promise<KanbanAutomationResult>{if(request.historical||request.imported||request.replay||request.technical||request.quarantined||!request.visible)return {status:'skipped',reason:'ineligible_origin'};const boards=await this.boards(request.workspaceId),board=boards[0];const {data,error}=await this.client.from('conversation_kanban_state').select('stage_id,manual_override,updated_at,kanban_stages!inner(key)').eq('workspace_id',request.workspaceId).eq('conversation_id',request.conversationId).eq('board_id',board.id).maybeSingle();if(error)fail(error);if(!data||data.manual_override)return {status:'skipped',reason:data?.manual_override?'manual_override':'missing_state'};const key=(data.kanban_stages as any).key,target=request.direction==='inbound'&&key==='waiting_customer'?'waiting_operator':request.direction==='outbound'&&['new','waiting_operator','in_progress'].includes(key)?'waiting_customer':undefined;if(!target)return {status:'skipped',reason:'stage_rule'};const claim=await this.client.from('kanban_automation_deliveries').insert({workspace_id:request.workspaceId,conversation_id:request.conversationId,message_id:request.messageId,direction:request.direction});if(claim.error?.code==='23505')return {status:'skipped',reason:'duplicate'};if(claim.error)fail(claim.error);const next=board.stages.find((x:any)=>x.key===target);if(!next)return {status:'skipped',reason:'missing_target'};await this.move(request.workspaceId,'00000000-0000-4000-8000-000000000001',request.conversationId,{boardId:board.id,stageId:next.id,source:request.direction,expectedUpdatedAt:data.updated_at});return {status:'moved'};}
  private async ensure(workspaceId:string):Promise<any>{const {data:existing,error:findError}=await this.client.from('kanban_boards').select('*').eq('workspace_id',workspaceId).eq('is_default',true).maybeSingle();if(findError)fail(findError);let id=existing?.id;if(!id){id=randomUUID();const now=new Date().toISOString();const result=await this.client.from('kanban_boards').insert({id,workspace_id:workspaceId,name:'Operação',is_default:true,created_at:now,updated_at:now});if(result.error){const retry=await this.client.from('kanban_boards').select('*').eq('workspace_id',workspaceId).eq('is_default',true).single();if(retry.error)fail(retry.error);id=retry.data.id;}const stages=defaults.map(([key,name],i)=>({id:randomUUID(),board_id:id,key,name,position:i+1,is_terminal:key==='resolved'||key==='archived',is_archived_stage:key==='archived',created_at:now,updated_at:now}));const s=await this.client.from('kanban_stages').upsert(stages,{onConflict:'board_id,key'});if(s.error)fail(s.error);const visible=await this.client.from('conversations').select('id,status').eq('workspace_id',workspaceId).eq('visibility_state','visible');if(visible.error)fail(visible.error);const found=await this.client.from('kanban_stages').select('id,key').eq('board_id',id);if(found.error)fail(found.error);const byKey=Object.fromEntries((found.data??[]).map((x:any)=>[x.key,x.id]));const states=(visible.data??[]).map((c:any,i:number)=>({workspace_id:workspaceId,conversation_id:c.id,board_id:id,stage_id:byKey[mapped[c.status]??'new'],position:i+1,manual_override:false,last_transition_source:'system',last_transition_by:null,last_transition_at:now,created_at:now,updated_at:now}));if(states.length){const inserted=await this.client.from('conversation_kanban_state').upsert(states,{onConflict:'conversation_id,board_id',ignoreDuplicates:true});if(inserted.error)fail(inserted.error);}}return this.detail(workspaceId,id);}
  private async board(workspaceId:string,id:string){const {data,error}=await this.client.from('kanban_boards').select('*,kanban_stages(*)').eq('workspace_id',workspaceId).eq('id',id).maybeSingle();if(error)fail(error);if(!data)return undefined;const stages=await Promise.all((data.kanban_stages??[]).sort((a:any,b:any)=>Number(a.position)-Number(b.position)).map(async(s:any)=>{const c=await this.client.from('conversation_kanban_state').select('conversation_id',{count:'exact',head:true}).eq('workspace_id',workspaceId).eq('board_id',id).eq('stage_id',s.id);if(c.error)fail(c.error);return {...this.stage(s),count:c.count??0};}));return {id:data.id,workspaceId:data.workspace_id,name:data.name,isDefault:data.is_default,createdAt:data.created_at,updatedAt:data.updated_at,stages};}
  private async requireStage(workspaceId:string,id:string){const {data,error}=await this.client.from('kanban_stages').select('*,kanban_boards!inner(workspace_id)').eq('id',id).maybeSingle();if(error)fail(error);if(!data||(data.kanban_boards as any).workspace_id!==workspaceId)throw new AppError(404,'NOT_FOUND','Stage not found');return this.stage(data);}
  private stage(x:any){return {id:x.id,boardId:x.board_id,key:x.key,name:x.name,position:Number(x.position),isTerminal:!!x.is_terminal,isArchivedStage:!!x.is_archived_stage,createdAt:x.created_at,updatedAt:x.updated_at};}
  private async nextPosition(workspaceId:string,boardId:string,stageId:string){const {data,error}=await this.client.from('conversation_kanban_state').select('position').eq('workspace_id',workspaceId).eq('board_id',boardId).eq('stage_id',stageId).order('position',{ascending:false}).limit(1);if(error)fail(error);return Number(data?.[0]?.position??0)+1;}
}
