import { createHmac, randomUUID, timingSafeEqual } from 'node:crypto';
import { z } from 'zod';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { SqliteDatabase } from '../persistence/database.js';

const acceptedEvents = ['message', 'message.any', 'session.status'] as const;
const sensitiveKey = /(api[_-]?key|authorization|credential|token|secret|password|cookie|auth)/i;
const webhookSchema = z.object({ id: z.string().min(1).max(200), timestamp: z.number().int().nonnegative(), event: z.enum(acceptedEvents), session: z.string().min(1).max(200), payload: z.record(z.unknown()) }).passthrough();
export type WahaWebhookEvent = z.infer<typeof webhookSchema>;
type StoredWebhook = { workspaceId: string; wahaSession: string; externalEventId: string; eventType: WahaWebhookEvent['event']; occurredAt: string; payload: Record<string, unknown>; receivedAt: string };
type StoredMessage = StoredWebhook & { externalMessageId: string; chatId: string; conversationType: 'direct' | 'group'; senderWhatsappId: string | null; direction: 'inbound' | 'outbound'; messageType: string; body: string | null };
export interface WahaWebhookStore { ingest(event: StoredWebhook): Promise<{ duplicate: boolean }>; }
export type ConversationSummary = { id: string; workspaceId: string; whatsappSessionId: string; chatId: string; contactId: string | null; status: 'open' | 'closed'; lastMessage: string | null; lastMessageAt: string; unreadCount: number; createdAt: string; updatedAt: string };
export type InboxMessage = { id: string; direction: 'inbound' | 'outbound'; content: string | null; timestamp: string; status: 'received' | 'sent'; messageType: string; chatId: string; metadata: Record<string, unknown> };
export interface ConversationStore { listConversations(workspaceId: string, page: number, pageSize: number): Promise<{ items: ConversationSummary[]; page: number; pageSize: number; total: number }>; getConversation(workspaceId: string, conversationId: string): Promise<ConversationSummary | undefined>; listMessages(workspaceId: string, conversationId: string, page: number, pageSize: number): Promise<{ items: InboxMessage[]; page: number; pageSize: number; total: number }>; markRead(workspaceId: string, conversationId: string): Promise<boolean>; recordOutbound(input: { workspaceId: string; wahaSession: string; chatId: string; externalMessageId: string; text: string; occurredAt: string }): Promise<InboxMessage>; }
export function parseWebhook(value: unknown): WahaWebhookEvent { return webhookSchema.parse(value); }

export function verifyWahaWebhook(rawBody: Buffer, headers: { hmac?: string; algorithm?: string; timestamp?: string }, key?: string): void {
  if (!key) throw new WahaWebhookValidationError(503, 'WAHA webhook authentication is not configured');
  if (headers.algorithm?.toLowerCase() !== 'sha512' || !headers.hmac || !/^[a-f0-9]{128}$/i.test(headers.hmac)) throw new WahaWebhookValidationError(401, 'WAHA webhook signature is invalid');
  const expected = createHmac('sha512', key).update(rawBody).digest(); const provided = Buffer.from(headers.hmac, 'hex');
  if (provided.length !== expected.length || !timingSafeEqual(provided, expected)) throw new WahaWebhookValidationError(401, 'WAHA webhook signature is invalid');
  const sentAt = Number(headers.timestamp);
  if (!Number.isInteger(sentAt) || Math.abs(Date.now() - sentAt) > 10 * 60_000) throw new WahaWebhookValidationError(401, 'WAHA webhook timestamp is invalid');
}
export class WahaWebhookValidationError extends Error { constructor(readonly status: number, message: string) { super(message); this.name = 'WahaWebhookValidationError'; } }

export class SqliteWahaWebhookStore implements WahaWebhookStore, ConversationStore {
  constructor(private readonly database: SqliteDatabase) {}
  async ingest(event: StoredWebhook): Promise<{ duplicate: boolean }> {
    const payloadJson = JSON.stringify(sanitize(event.payload));
    try {
      this.database.transaction(() => {
        this.database.prepare('INSERT INTO waha_webhook_events (workspaceId, wahaSession, externalEventId, eventType, occurredAt, payloadJson, receivedAt) VALUES (?, ?, ?, ?, ?, ?, ?)').run(event.workspaceId, event.wahaSession, event.externalEventId, event.eventType, event.occurredAt, payloadJson, event.receivedAt);
        const message = messageFrom(event); if (message) { const result = this.database.prepare('INSERT OR IGNORE INTO whatsapp_messages (workspaceId, wahaSession, externalMessageId, externalEventId, chatId, senderWhatsappId, senderContactId, direction, messageType, body, occurredAt, payloadJson, receivedAt, status) VALUES (?, ?, ?, ?, ?, ?, NULL, ?, ?, ?, ?, ?, ?, ?)').run(message.workspaceId, message.wahaSession, message.externalMessageId, message.externalEventId, message.chatId, message.senderWhatsappId, message.direction, message.messageType, message.body, message.occurredAt, JSON.stringify(sanitize(message.payload)), message.receivedAt, message.direction === 'inbound' ? 'received' : 'sent'); if (result.changes) this.upsertConversation(message); }
      })();
      return { duplicate: false };
    } catch (error) { if (isUniqueError(error)) return { duplicate: true }; throw error; }
  }
  async listConversations(workspaceId: string, page: number, pageSize: number) { const total = (this.database.prepare('SELECT count(*) AS total FROM conversations WHERE workspaceId = ?').get(workspaceId) as { total: number }).total; const rows = this.database.prepare('SELECT id, workspaceId, wahaSession whatsappSessionId, chatId, contactId, status, lastMessage, lastMessageAt, unreadCount, createdAt, updatedAt FROM conversations WHERE workspaceId = ? ORDER BY lastMessageAt DESC LIMIT ? OFFSET ?').all(workspaceId, pageSize, (page - 1) * pageSize) as ConversationSummary[]; return { items: rows, page, pageSize, total }; }
  async getConversation(workspaceId: string, conversationId: string) { return this.database.prepare('SELECT id, workspaceId, wahaSession whatsappSessionId, chatId, contactId, status, lastMessage, lastMessageAt, unreadCount, createdAt, updatedAt FROM conversations WHERE workspaceId = ? AND id = ?').get(workspaceId, conversationId) as ConversationSummary | undefined; }
  async listMessages(workspaceId: string, conversationId: string, page: number, pageSize: number) { const conversation = this.database.prepare('SELECT wahaSession, chatId FROM conversations WHERE workspaceId = ? AND id = ?').get(workspaceId, conversationId) as { wahaSession: string; chatId: string } | undefined; if (!conversation) return { items: [], page, pageSize, total: 0 }; const total = (this.database.prepare('SELECT count(*) AS total FROM whatsapp_messages WHERE workspaceId = ? AND wahaSession = ? AND chatId = ?').get(workspaceId, conversation.wahaSession, conversation.chatId) as { total: number }).total; const rows = this.database.prepare('SELECT externalMessageId id, direction, body content, occurredAt timestamp, status, messageType, chatId, payloadJson FROM whatsapp_messages WHERE workspaceId = ? AND wahaSession = ? AND chatId = ? ORDER BY occurredAt ASC LIMIT ? OFFSET ?').all(workspaceId, conversation.wahaSession, conversation.chatId, pageSize, (page - 1) * pageSize) as Array<Omit<InboxMessage, 'metadata'> & { payloadJson: string }>; return { items: rows.map(({ payloadJson, ...row }) => ({ ...row, metadata: JSON.parse(payloadJson) as Record<string, unknown> })), page, pageSize, total }; }
  async markRead(workspaceId: string, conversationId: string): Promise<boolean> { return this.database.prepare('UPDATE conversations SET unreadCount = 0, updatedAt = ? WHERE workspaceId = ? AND id = ?').run(new Date().toISOString(), workspaceId, conversationId).changes > 0; }
  async recordOutbound(input: { workspaceId: string; wahaSession: string; chatId: string; externalMessageId: string; text: string; occurredAt: string }): Promise<InboxMessage> { await this.ingest(outboundRecord(input)); return { id: input.externalMessageId, direction: 'outbound', content: input.text, timestamp: input.occurredAt, status: 'sent', messageType: 'text', chatId: input.chatId, metadata: {} }; }
  private upsertConversation(message: StoredMessage): void { const contact = message.conversationType === 'direct' ? this.database.prepare("SELECT id FROM contacts WHERE workspaceId = ? AND phoneNumber = ?").get(message.workspaceId, phoneFromChat(message.chatId)) as { id?: string } | undefined : undefined; const now = message.receivedAt; this.database.prepare("INSERT INTO conversations (id, workspaceId, wahaSession, chatId, contactId, conversationType, status, lastMessage, lastMessageAt, unreadCount, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, 'open', ?, ?, ?, ?, ?) ON CONFLICT(workspaceId, wahaSession, chatId) DO UPDATE SET contactId = COALESCE(conversations.contactId, excluded.contactId), conversationType = excluded.conversationType, lastMessage = excluded.lastMessage, lastMessageAt = excluded.lastMessageAt, unreadCount = conversations.unreadCount + excluded.unreadCount, updatedAt = excluded.updatedAt").run(randomUUID(), message.workspaceId, message.wahaSession, message.chatId, contact?.id ?? null, message.conversationType, message.body, message.occurredAt, message.direction === 'inbound' ? 1 : 0, now, now); }
}
export class SupabaseWahaWebhookStore implements WahaWebhookStore, ConversationStore {
  constructor(private readonly client: SupabaseClient) {}
  async ingest(event: StoredWebhook): Promise<{ duplicate: boolean }> {
    const { error } = await this.client.from('waha_webhook_events').insert({ workspace_id: event.workspaceId, waha_session: event.wahaSession, external_event_id: event.externalEventId, event_type: event.eventType, occurred_at: event.occurredAt, payload_json: sanitize(event.payload), received_at: event.receivedAt });
    if (error) { if (error.code === '23505') return { duplicate: true }; throw error; }
    const message = messageFrom(event); if (!message) return { duplicate: false };
    const { error: messageError } = await this.client.from('whatsapp_messages').insert({ workspace_id: message.workspaceId, waha_session: message.wahaSession, external_message_id: message.externalMessageId, external_event_id: message.externalEventId, chat_id: message.chatId, sender_whatsapp_id: message.senderWhatsappId, sender_contact_id: null, direction: message.direction, message_type: message.messageType, body: message.body, occurred_at: message.occurredAt, payload_json: sanitize(message.payload), received_at: message.receivedAt, status: message.direction === 'inbound' ? 'received' : 'sent' });
    if (messageError && messageError.code !== '23505') throw messageError; if (!messageError) await this.upsertConversation(message); return { duplicate: false };
  }
  async listConversations(workspaceId: string, page: number, pageSize: number) { const from = (page - 1) * pageSize; const { data, error, count } = await this.client.from('conversations').select('id, workspace_id, waha_session, chat_id, contact_id, status, last_message, last_message_at, unread_count, created_at, updated_at', { count: 'exact' }).eq('workspace_id', workspaceId).order('last_message_at', { ascending: false }).range(from, from + pageSize - 1); if (error) throw error; return { items: (data ?? []).map(row => ({ id: row.id, workspaceId: row.workspace_id, whatsappSessionId: row.waha_session, chatId: row.chat_id, contactId: row.contact_id, status: row.status, lastMessage: row.last_message, lastMessageAt: row.last_message_at, unreadCount: row.unread_count, createdAt: row.created_at, updatedAt: row.updated_at })) as ConversationSummary[], page, pageSize, total: count ?? 0 }; }
  async getConversation(workspaceId: string, conversationId: string) { const { data, error } = await this.client.from('conversations').select('id, workspace_id, waha_session, chat_id, contact_id, status, last_message, last_message_at, unread_count, created_at, updated_at').eq('workspace_id', workspaceId).eq('id', conversationId).maybeSingle(); if (error) throw error; return data ? { id: data.id, workspaceId: data.workspace_id, whatsappSessionId: data.waha_session, chatId: data.chat_id, contactId: data.contact_id, status: data.status, lastMessage: data.last_message, lastMessageAt: data.last_message_at, unreadCount: data.unread_count, createdAt: data.created_at, updatedAt: data.updated_at } as ConversationSummary : undefined; }
  async listMessages(workspaceId: string, conversationId: string, page: number, pageSize: number) { const { data: conversation, error: conversationError } = await this.client.from('conversations').select('waha_session, chat_id').eq('workspace_id', workspaceId).eq('id', conversationId).maybeSingle(); if (conversationError) throw conversationError; if (!conversation) return { items: [], page, pageSize, total: 0 }; const from = (page - 1) * pageSize; const { data, error, count } = await this.client.from('whatsapp_messages').select('external_message_id, direction, body, occurred_at, status, message_type, chat_id, payload_json', { count: 'exact' }).eq('workspace_id', workspaceId).eq('waha_session', conversation.waha_session).eq('chat_id', conversation.chat_id).order('occurred_at', { ascending: true }).range(from, from + pageSize - 1); if (error) throw error; return { items: (data ?? []).map(row => ({ id: row.external_message_id, direction: row.direction, content: row.body, timestamp: row.occurred_at, status: row.status, messageType: row.message_type, chatId: row.chat_id, metadata: row.payload_json })) as InboxMessage[], page, pageSize, total: count ?? 0 }; }
  async markRead(workspaceId: string, conversationId: string): Promise<boolean> { const { data, error } = await this.client.from('conversations').update({ unread_count: 0, updated_at: new Date().toISOString() }).eq('workspace_id', workspaceId).eq('id', conversationId).select('id'); if (error) throw error; return (data?.length ?? 0) > 0; }
  async recordOutbound(input: { workspaceId: string; wahaSession: string; chatId: string; externalMessageId: string; text: string; occurredAt: string }): Promise<InboxMessage> { await this.ingest(outboundRecord(input)); return { id: input.externalMessageId, direction: 'outbound', content: input.text, timestamp: input.occurredAt, status: 'sent', messageType: 'text', chatId: input.chatId, metadata: {} }; }
  private async upsertConversation(message: StoredMessage): Promise<void> { const phone = phoneFromChat(message.chatId); const { data: contact, error: contactError } = message.conversationType === 'direct' ? await this.client.from('contacts').select('id').eq('workspace_id', message.workspaceId).eq('phone_number', phone).maybeSingle() : { data: null, error: null }; if (contactError) throw contactError; const { data: existing, error: existingError } = await this.client.from('conversations').select('id, contact_id, unread_count').eq('workspace_id', message.workspaceId).eq('waha_session', message.wahaSession).eq('chat_id', message.chatId).maybeSingle(); if (existingError) throw existingError; const row = { workspace_id: message.workspaceId, waha_session: message.wahaSession, chat_id: message.chatId, contact_id: existing?.contact_id ?? contact?.id ?? null, conversation_type: message.conversationType, status: 'open', last_message: message.body, last_message_at: message.occurredAt, unread_count: (existing?.unread_count ?? 0) + (message.direction === 'inbound' ? 1 : 0), updated_at: message.receivedAt }; const result = existing ? await this.client.from('conversations').update(row).eq('workspace_id', message.workspaceId).eq('id', existing.id) : await this.client.from('conversations').insert({ ...row, id: randomUUID(), created_at: message.receivedAt }); if (result.error) throw result.error; }
}
export function webhookRecord(event: WahaWebhookEvent, workspaceId: string): StoredWebhook { return { workspaceId, wahaSession: event.session, externalEventId: event.id, eventType: event.event, occurredAt: new Date(event.timestamp).toISOString(), payload: event.payload, receivedAt: new Date().toISOString() }; }
function outboundRecord(input: { workspaceId: string; wahaSession: string; chatId: string; externalMessageId: string; text: string; occurredAt: string }): StoredWebhook { return { workspaceId: input.workspaceId, wahaSession: input.wahaSession, externalEventId: `outbound:${input.externalMessageId}`, eventType: 'message.any', occurredAt: input.occurredAt, payload: { id: input.externalMessageId, chatId: input.chatId, body: input.text, type: 'text', fromMe: true }, receivedAt: new Date().toISOString() }; }
function messageFrom(event: StoredWebhook): StoredMessage | undefined { if (event.eventType !== 'message' && event.eventType !== 'message.any') return undefined; const value = event.payload; const id = text(value.id) ?? text(nested(value, 'key', 'id')); const chatId = text(value.chatId) ?? text(value.from) ?? text(nested(value, 'key', 'remoteJid')); if (!id || !chatId) return undefined; const conversationType = chatId.endsWith('@g.us') ? 'group' : 'direct'; return { ...event, externalMessageId: id, chatId, conversationType, senderWhatsappId: conversationType === 'group' ? text(value.participant) ?? null : chatId, direction: value.fromMe === true ? 'outbound' : 'inbound', messageType: text(value.type) ?? 'text', body: text(value.body) ?? text(value.text) ?? null }; }
function nested(value: Record<string, unknown>, key: string, child: string): unknown { const parent = value[key]; return parent && typeof parent === 'object' ? (parent as Record<string, unknown>)[child] : undefined; }
function text(value: unknown): string | undefined { return typeof value === 'string' && value.length > 0 ? value.slice(0, 20_000) : undefined; }
function phoneFromChat(chatId: string): string { return chatId.split('@', 1)[0].replace(/\D/g, ''); }
function isUniqueError(error: unknown): boolean { return error instanceof Error && /unique|constraint/i.test(error.message); }
function sanitize(value: unknown, depth = 0): unknown { if (depth > 12) return '[TRUNCATED]'; if (typeof value === 'string') return value.length > 20_000 ? `${value.slice(0, 20_000)}[TRUNCATED]` : value; if (Array.isArray(value)) return value.slice(0, 200).map(item => sanitize(item, depth + 1)); if (!value || typeof value !== 'object') return value; return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([key, item]) => [key, sensitiveKey.test(key) ? '[REDACTED]' : sanitize(item, depth + 1)])); }
