import { createHmac, randomUUID, timingSafeEqual } from 'node:crypto';
import { z } from 'zod';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { SqliteDatabase } from '../persistence/database.js';
import { resolveConversationIdentity } from './conversation-identity.js';
import type { KanbanAutomationCoordinator } from './kanban-automation.service.js';

const acceptedEvents = ['message', 'message.any', 'session.status'] as const;
const sensitiveKey = /(api[_-]?key|authorization|credential|token|secret|password|cookie|auth)/i;
const webhookSchema = z.object({ id: z.string().min(1).max(200), timestamp: z.number().int().nonnegative(), event: z.enum(acceptedEvents), session: z.string().min(1).max(200), payload: z.record(z.unknown()) }).passthrough();
export type WahaWebhookEvent = z.infer<typeof webhookSchema>;
type StoredWebhook = { workspaceId: string; wahaSession: string; externalEventId: string; eventType: WahaWebhookEvent['event']; occurredAt: string; payload: Record<string, unknown>; receivedAt: string };
type StoredMessage = StoredWebhook & { externalMessageId: string; chatId: string; deliveryChatId: string; conversationType: 'direct' | 'group'; senderWhatsappId: string | null; direction: 'inbound' | 'outbound'; messageType: string; body: string | null; mediaUrl: string | null; mediaMimeType: string | null; mediaFilename: string | null; mediaSize: number | null; thumbnailUrl: string | null; duration: number | null; quotedMessageId: string | null; historical: boolean };
export type IngestResult = { duplicate: boolean; messageInserted: boolean; conversationId?: string; messageId?: string; direction?: 'inbound' | 'outbound'; historical?: boolean; technical?: boolean; quarantined?: boolean };
export type PersistedOutboundMessage = InboxMessage & { persistence: IngestResult };
export interface WahaWebhookStore { ingest(event: StoredWebhook): Promise<IngestResult>; }
export type ConversationIdentity = { displayName: string | null; phone: string | null; pushName: string | null; profileName: string | null; avatarUrl: string | null; lastSyncAt: string | null; syncStatus: 'pending' | 'synced'; knownContact: boolean };
export type ConversationStatus = 'open' | 'in_progress' | 'waiting_customer' | 'resolved' | 'archived';
export type ConversationPriority = 'low' | 'normal' | 'high' | 'urgent';
export type ConversationEventAction = 'assigned' | 'unassigned' | 'status_changed' | 'priority_changed' | 'archived' | 'reopened';
export type ConversationEvent = { id: string; conversationId: string; workspaceId: string; userId: string; action: ConversationEventAction; previousValue: string | null; newValue: string | null; createdAt: string };
export type ConversationSummary = { id: string; workspaceId: string; whatsappSessionId: string; chatId: string; deliveryChatId?: string; contactId: string | null; conversationType: 'direct' | 'group'; assignedUserId: string | null; assignedTeamId: string | null; assignedAt: string | null; routingQueueId: string | null; autoAssignedAt: string | null; routingLockedAt: string | null; status: ConversationStatus; priority: ConversationPriority; lastStatusChange: string | null; lastMessage: string | null; lastMessageAt: string; unreadCount: number; createdAt: string; updatedAt: string; identity: ConversationIdentity };
export type InboxMessage = { id: string; direction: 'inbound' | 'outbound'; content: string | null; timestamp: string; status: 'sending' | 'received' | 'sent' | 'delivered' | 'read' | 'failed'; messageType: string; chatId: string; senderWhatsappId?: string | null; mediaUrl?: string | null; mediaMimeType?: string | null; mediaFilename?: string | null; mediaSize?: number | null; thumbnailUrl?: string | null; duration?: number | null; quotedMessageId?: string | null; metadata: Record<string, unknown> };
export type CursorPage<T> = { items: T[]; page: number; pageSize: number; total: number; nextCursor: string | null; hasMore: boolean };
export interface ConversationStore { listConversations(workspaceId: string, page: number, pageSize: number, cursor?: string, search?: string): Promise<CursorPage<ConversationSummary>>; listQuarantined(workspaceId: string, page: number, pageSize: number): Promise<{ items: ConversationSummary[]; page: number; pageSize: number; total: number }>; restoreConversation(workspaceId: string, conversationId: string): Promise<boolean>; quarantineCount(workspaceId: string): Promise<number>; getConversation(workspaceId: string, conversationId: string): Promise<ConversationSummary | undefined>; listMessages(workspaceId: string, conversationId: string, page: number, pageSize: number, cursor?: string): Promise<CursorPage<InboxMessage>>; getMedia(workspaceId: string, messageId: string): Promise<{ url: string; mimeType: string | null; filename: string | null; storagePath?: string | null } | undefined>; markRead(workspaceId: string, conversationId: string): Promise<boolean>; recordOutbound(input: { workspaceId: string; wahaSession: string; chatId: string; externalMessageId: string; text: string; occurredAt: string }): Promise<PersistedOutboundMessage>; setAssignment(workspaceId: string, conversationId: string, assignedUserId: string | null, actorUserId: string): Promise<ConversationEvent | undefined>; setTeamAssignment(workspaceId: string, conversationId: string, assignedTeamId: string | null, actorUserId: string): Promise<ConversationEvent | undefined>; setStatus(workspaceId: string, conversationId: string, status: ConversationStatus, actorUserId: string): Promise<ConversationEvent | undefined>; setPriority(workspaceId: string, conversationId: string, priority: ConversationPriority, actorUserId: string): Promise<ConversationEvent | undefined>; listActivity(workspaceId: string, conversationId: string): Promise<ConversationEvent[] | undefined>; }
export function parseWebhook(value: unknown): WahaWebhookEvent { return webhookSchema.parse(value); }

export function verifyWahaWebhook(rawBody: Buffer, headers: { hmac?: string; algorithm?: string; timestamp?: string }, key?: string): void {
  if (!key) throw new WahaWebhookValidationError(503, 'WAHA webhook authentication is not configured');
  if (headers.algorithm?.toLowerCase() !== 'sha512' || !headers.hmac || !/^[a-f0-9]{128}$/i.test(headers.hmac)) throw new WahaWebhookValidationError(401, 'WAHA webhook signature is invalid');
  const expected = createHmac('sha512', key).update(rawBody).digest(); const provided = Buffer.from(headers.hmac, 'hex');
  if (provided.length !== expected.length || !timingSafeEqual(provided, expected)) throw new WahaWebhookValidationError(401, 'WAHA webhook signature is invalid');
  const sentAt = Number(headers.timestamp);
  if (!Number.isInteger(sentAt) || Math.abs(Date.now() - sentAt) > 10 * 60_000) throw new WahaWebhookValidationError(401, 'WAHA webhook timestamp is invalid');
}
export class WahaWebhookValidationError extends Error { constructor(readonly status: number, message: string) { super(message); this.name = 'WahaWebhookValidationError'; } }

export class SqliteWahaWebhookStore implements WahaWebhookStore, ConversationStore {
  constructor(private readonly database: SqliteDatabase, private readonly automation?: KanbanAutomationCoordinator) {}
  async ingest(event: StoredWebhook): Promise<IngestResult> {
    const payloadJson = JSON.stringify(sanitize(event.payload));
    try {
      let persisted: IngestResult = { duplicate: false, messageInserted: false };
      this.database.transaction(() => {
        this.database.prepare('INSERT INTO waha_webhook_events (workspaceId, wahaSession, externalEventId, eventType, occurredAt, payloadJson, receivedAt) VALUES (?, ?, ?, ?, ?, ?, ?)').run(event.workspaceId, event.wahaSession, event.externalEventId, event.eventType, event.occurredAt, payloadJson, event.receivedAt);
        const parsed = messageFrom(event); const message = parsed ? this.normalize(parsed) : undefined; if (message) { const result = this.database.prepare('INSERT OR IGNORE INTO whatsapp_messages (workspaceId, wahaSession, externalMessageId, externalEventId, chatId, senderWhatsappId, direction, messageType, body, mediaUrl, mediaMimeType, mediaFilename, mediaSize, thumbnailUrl, duration, quotedMessageId, occurredAt, payloadJson, receivedAt, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(message.workspaceId, message.wahaSession, message.externalMessageId, message.externalEventId, message.chatId, message.senderWhatsappId, message.direction, message.messageType, message.body, message.mediaUrl, message.mediaMimeType, message.mediaFilename, message.mediaSize, message.thumbnailUrl, message.duration, message.quotedMessageId, message.occurredAt, JSON.stringify(sanitize(message.payload)), message.receivedAt, message.direction === 'inbound' ? 'received' : 'sent'); if (result.changes) this.upsertConversation(message); const conversation = this.database.prepare('SELECT id, visibilityState FROM conversations WHERE workspaceId=? AND wahaSession=? AND chatId=?').get(message.workspaceId, message.wahaSession, message.chatId) as { id: string; visibilityState: string } | undefined; persisted = { duplicate: false, messageInserted: result.changes > 0, conversationId: conversation?.id, messageId: message.externalMessageId, direction: message.direction, historical: message.historical, technical: isTechnical(message), quarantined: conversation?.visibilityState === 'quarantined' }; }
      })();
      if (persisted.messageInserted && persisted.direction === 'inbound' && persisted.conversationId) await this.automation?.run({ workspaceId: event.workspaceId, conversationId: persisted.conversationId, messageId: persisted.messageId!, direction: 'inbound', historical: persisted.historical, visible: !persisted.quarantined, technical: persisted.technical, quarantined: persisted.quarantined });
      return persisted;
    } catch (error) { if (isUniqueError(error)) return { duplicate: true, messageInserted: false }; throw error; }
  }
  async listConversations(workspaceId: string, page: number, pageSize: number, cursor?: string, search?: string): Promise<CursorPage<ConversationSummary>> { const limit = Math.min(pageSize, 100); const parsed = cursorValue(cursor); const terms = search?.trim() ? `%${search.trim().replace(/[%_]/g, '\\$&')}%` : undefined; const where = ["c.workspaceId = ?", "c.visibilityState = 'visible'", ...(terms ? ["(c.chatId LIKE ? ESCAPE '\\' OR COALESCE(i.name, i.pushName, c.lastMessage, '') LIKE ? ESCAPE '\\')"] : []), ...(parsed ? ["(c.lastMessageAt < ? OR (c.lastMessageAt = ? AND c.id > ?))"] : [])]; const values = [workspaceId, ...(terms ? [terms, terms] : []), ...(parsed ? [parsed.at, parsed.at, parsed.id] : [])]; const total = (this.database.prepare(`SELECT count(*) AS total FROM conversations c LEFT JOIN whatsapp_identities i ON i.workspaceId=c.workspaceId AND i.wahaSession=c.wahaSession AND i.whatsappId=c.chatId WHERE ${where.slice(0, terms ? 3 : 2).join(' AND ')}`).get(...values.slice(0, terms ? 3 : 1)) as { total: number }).total; const rows = this.rows(`WHERE ${where.join(' AND ')} ORDER BY c.lastMessageAt DESC, c.id ASC LIMIT ?`, ...values, limit + 1); const more = rows.length > limit; const items = rows.slice(0, limit).map(toConversationSummary); const last = items.at(-1); return { items, page, pageSize: limit, total, hasMore: more, nextCursor: more && last ? encodeCursor(last.lastMessageAt, last.id) : null }; }
  async listQuarantined(workspaceId: string, page: number, pageSize: number) { const total = (this.database.prepare("SELECT count(*) AS total FROM conversations WHERE workspaceId = ? AND visibilityState IN ('quarantined', 'technical')").get(workspaceId) as { total: number }).total; const rows = this.rows("WHERE c.workspaceId = ? AND c.visibilityState IN ('quarantined', 'technical') ORDER BY c.lastMessageAt DESC, c.id ASC LIMIT ? OFFSET ?", workspaceId, pageSize, (page - 1) * pageSize); return { items: rows.map(toConversationSummary), page, pageSize, total }; }
  async quarantineCount(workspaceId: string) { return (this.database.prepare("SELECT count(*) total FROM conversations WHERE workspaceId = ? AND visibilityState IN ('quarantined', 'technical')").get(workspaceId) as { total: number }).total; }
  async restoreConversation(workspaceId: string, conversationId: string) { return this.database.prepare("UPDATE conversations SET visibilityState = 'visible', integrityClassification = 'inconclusive', integrityReasonSafe = 'restored_manually', integrityReviewedAt = ?, updatedAt = ? WHERE workspaceId = ? AND id = ? AND visibilityState IN ('quarantined', 'technical')").run(new Date().toISOString(), new Date().toISOString(), workspaceId, conversationId).changes > 0; }
  async getConversation(workspaceId: string, conversationId: string) { const row = this.rows('WHERE c.workspaceId = ? AND c.id = ?', workspaceId, conversationId)[0]; return row ? toConversationSummary(row) : undefined; }
  private rows(where: string, ...values: unknown[]): ConversationRow[] { return this.database.prepare(`SELECT c.id, c.workspaceId, c.wahaSession whatsappSessionId, c.chatId, c.deliveryChatId, c.contactId, c.conversationType, c.assignedUserId, c.assignedTeamId, c.assignedAt, c.routingQueueId, c.autoAssignedAt, c.routingLockedAt, c.operationalStatus status, c.priority, c.lastStatusChange, c.lastMessage, c.lastMessageAt, c.unreadCount, c.createdAt, c.updatedAt, i.phone identityPhone, i.name profileName, i.pushName, i.profilePictureUrl identityAvatarUrl, i.updatedAt identityUpdatedAt, g.name groupName, g.pictureUrl groupPictureUrl, g.updatedAt groupUpdatedAt FROM conversations c LEFT JOIN whatsapp_identities i ON c.conversationType = 'direct' AND i.workspaceId = c.workspaceId AND i.wahaSession = c.wahaSession AND i.whatsappId = c.chatId LEFT JOIN whatsapp_groups g ON c.conversationType = 'group' AND g.workspaceId = c.workspaceId AND g.wahaSession = c.wahaSession AND g.chatId = c.chatId ${where}`).all(...values) as ConversationRow[]; }
  async listMessages(workspaceId: string, conversationId: string, page: number, pageSize: number, cursor?: string): Promise<CursorPage<InboxMessage>> { const conversation = this.database.prepare('SELECT wahaSession, chatId, conversationType FROM conversations WHERE workspaceId = ? AND id = ?').get(workspaceId, conversationId) as { wahaSession: string; chatId: string; conversationType: 'direct' | 'group' } | undefined; const limit = conversation?.conversationType === 'group' ? Math.min(pageSize, 100) : 10_000; if (!conversation) return { items: [], page, pageSize: limit, total: 0, hasMore: false, nextCursor: null }; const parsed = conversation.conversationType === 'group' ? cursorValue(cursor) : undefined; const total = (this.database.prepare('SELECT count(*) AS total FROM whatsapp_messages WHERE workspaceId = ? AND wahaSession = ? AND chatId = ?').get(workspaceId, conversation.wahaSession, conversation.chatId) as { total: number }).total; const rows = this.database.prepare(`SELECT externalMessageId id, direction, body content, occurredAt timestamp, status, messageType, chatId, senderWhatsappId, mediaUrl, mediaMimeType, mediaFilename, mediaSize, thumbnailUrl, duration, quotedMessageId, payloadJson FROM whatsapp_messages WHERE workspaceId = ? AND wahaSession = ? AND chatId = ? ${parsed ? 'AND (occurredAt < ? OR (occurredAt = ? AND externalMessageId < ?))' : ''} ORDER BY occurredAt DESC, externalMessageId DESC LIMIT ?`).all(workspaceId, conversation.wahaSession, conversation.chatId, ...(parsed ? [parsed.at, parsed.at, parsed.id] : []), limit + 1) as Array<Omit<InboxMessage, 'metadata'> & { payloadJson: string }>; const more = conversation.conversationType === 'group' && rows.length > limit; const pageRows = rows.slice(0, limit); const last = pageRows.at(-1); return { items: pageRows.reverse().map(({ payloadJson, ...row }) => ({ ...row, metadata: JSON.parse(payloadJson) as Record<string, unknown> })), page, pageSize: limit, total, hasMore: more, nextCursor: more && last ? encodeCursor(last.timestamp, last.id) : null }; }
  async getMedia(workspaceId: string, messageId: string) { return this.database.prepare('SELECT mediaUrl url, mediaMimeType mimeType, mediaFilename filename, mediaStoragePath storagePath FROM whatsapp_messages WHERE workspaceId = ? AND externalMessageId = ? AND mediaUrl IS NOT NULL').get(workspaceId, messageId) as { url: string; mimeType: string | null; filename: string | null; storagePath?: string | null } | undefined; }
  async persistMedia(input: { workspaceId: string; externalMessageId: string; storagePath: string; checksum: string; size: number; mimeType: string; filename: string }) { this.database.prepare("UPDATE whatsapp_messages SET mediaStoragePath = ?, mediaChecksum = ?, mediaSize = ?, mediaMimeType = ?, mediaFilename = ?, mediaPersistenceStatus = 'stored' WHERE workspaceId = ? AND externalMessageId = ?").run(input.storagePath, input.checksum, input.size, input.mimeType, input.filename, input.workspaceId, input.externalMessageId); }
  async pendingMedia(limit: number) { return this.database.prepare("SELECT workspaceId, externalMessageId, mediaUrl url, mediaMimeType mimeType, mediaFilename filename FROM whatsapp_messages WHERE mediaUrl IS NOT NULL AND mediaStoragePath IS NULL AND mediaPersistenceStatus <> 'unavailable' LIMIT ?").all(limit) as Array<{ workspaceId: string; externalMessageId: string; url: string; mimeType: string | null; filename: string | null }>; }
  async storedMediaWithGenericMime(limit: number) { return this.database.prepare("SELECT workspaceId, externalMessageId, mediaStoragePath storagePath, mediaMimeType mimeType, messageType FROM whatsapp_messages WHERE mediaStoragePath IS NOT NULL AND mediaMimeType IN ('application/mp4', 'application/octet-stream') LIMIT ?").all(limit) as Array<{ workspaceId: string; externalMessageId: string; storagePath: string; mimeType: string | null; messageType: string }>; }
  async updateMediaMime(workspaceId: string, externalMessageId: string, mimeType: string) { this.database.prepare('UPDATE whatsapp_messages SET mediaMimeType = ? WHERE workspaceId = ? AND externalMessageId = ?').run(mimeType, workspaceId, externalMessageId); }
  async markMediaUnavailable(workspaceId: string, externalMessageId: string) { this.database.prepare("UPDATE whatsapp_messages SET mediaPersistenceStatus = 'unavailable' WHERE workspaceId = ? AND externalMessageId = ? AND mediaStoragePath IS NULL").run(workspaceId, externalMessageId); }
  async markRead(workspaceId: string, conversationId: string): Promise<boolean> { return this.database.prepare('UPDATE conversations SET unreadCount = 0, updatedAt = ? WHERE workspaceId = ? AND id = ?').run(new Date().toISOString(), workspaceId, conversationId).changes > 0; }
  async recordOutbound(input: { workspaceId: string; wahaSession: string; chatId: string; externalMessageId: string; text: string; occurredAt: string }): Promise<PersistedOutboundMessage> { const persistence = await this.ingest(outboundRecord(input)); return { id: input.externalMessageId, direction: 'outbound', content: input.text, timestamp: input.occurredAt, status: 'sent', messageType: 'text', chatId: input.chatId, senderWhatsappId: input.chatId, metadata: {}, persistence }; }
  async setAssignment(workspaceId: string, conversationId: string, assignedUserId: string | null, actorUserId: string) { return this.change(workspaceId, conversationId, actorUserId, 'assignedUserId', assignedUserId); }
  async setTeamAssignment(workspaceId: string, conversationId: string, assignedTeamId: string | null, actorUserId: string) { return this.change(workspaceId, conversationId, actorUserId, 'assignedTeamId', assignedTeamId); }
  async setStatus(workspaceId: string, conversationId: string, status: ConversationStatus, actorUserId: string) { return this.change(workspaceId, conversationId, actorUserId, 'operationalStatus', status); }
  async setPriority(workspaceId: string, conversationId: string, priority: ConversationPriority, actorUserId: string) { return this.change(workspaceId, conversationId, actorUserId, 'priority', priority); }
  async listActivity(workspaceId: string, conversationId: string) { if (!this.database.prepare('SELECT 1 FROM conversations WHERE workspaceId = ? AND id = ?').get(workspaceId, conversationId)) return undefined; return this.database.prepare('SELECT id, conversationId, workspaceId, userId, action, previousValue, newValue, createdAt FROM conversation_events WHERE workspaceId = ? AND conversationId = ? ORDER BY createdAt DESC').all(workspaceId, conversationId) as ConversationEvent[]; }
  private change(workspaceId: string, conversationId: string, actorUserId: string, field: 'assignedUserId' | 'assignedTeamId' | 'operationalStatus' | 'priority', value: string | null): ConversationEvent | undefined { return this.database.transaction(() => { const current = this.database.prepare(`SELECT ${field} value FROM conversations WHERE workspaceId = ? AND id = ?`).get(workspaceId, conversationId) as { value: string | null } | undefined; if (!current) return undefined; if (current.value === value) return undefined; const now = new Date().toISOString(); const action: ConversationEventAction = field === 'assignedUserId' || field === 'assignedTeamId' ? (value ? 'assigned' : 'unassigned') : field === 'priority' ? 'priority_changed' : value === 'archived' ? 'archived' : current.value === 'archived' && value === 'open' ? 'reopened' : 'status_changed'; if (field === 'assignedUserId') this.database.prepare('UPDATE conversations SET assignedUserId = ?, assignedAt = ?, routingLockedAt = ?, updatedAt = ? WHERE workspaceId = ? AND id = ?').run(value, value ? now : null, now, now, workspaceId, conversationId); else if (field === 'assignedTeamId') this.database.prepare('UPDATE conversations SET assignedTeamId = ?, updatedAt = ? WHERE workspaceId = ? AND id = ?').run(value, now, workspaceId, conversationId); else if (field === 'operationalStatus') this.database.prepare('UPDATE conversations SET operationalStatus = ?, lastStatusChange = ?, updatedAt = ? WHERE workspaceId = ? AND id = ?').run(value, now, now, workspaceId, conversationId); else this.database.prepare('UPDATE conversations SET priority = ?, updatedAt = ? WHERE workspaceId = ? AND id = ?').run(value, now, workspaceId, conversationId); const event: ConversationEvent = { id: randomUUID(), conversationId, workspaceId, userId: actorUserId, action, previousValue: current.value, newValue: value, createdAt: now }; this.database.prepare('INSERT INTO conversation_events (id, conversationId, workspaceId, userId, action, previousValue, newValue, createdAt) VALUES (@id, @conversationId, @workspaceId, @userId, @action, @previousValue, @newValue, @createdAt)').run(event); return event; })(); }
  private normalize(message: StoredMessage): StoredMessage { if (message.conversationType === 'group') return message; const row = this.database.prepare('SELECT canonicalWhatsappId FROM whatsapp_identities WHERE workspaceId = ? AND wahaSession = ? AND whatsappId = ?').get(message.workspaceId, message.wahaSession, message.chatId) as { canonicalWhatsappId?: string | null } | undefined; const canonical = row?.canonicalWhatsappId || message.chatId; return { ...message, chatId: canonical, deliveryChatId: canonical.endsWith('@c.us') ? canonical : message.deliveryChatId }; }
  private upsertConversation(message: StoredMessage): void { const contact = message.conversationType === 'direct' ? this.database.prepare("SELECT id FROM contacts WHERE workspaceId = ? AND phoneNumber = ?").get(message.workspaceId, phoneFromChat(message.chatId)) as { id?: string } | undefined : undefined; const now = message.receivedAt; this.database.prepare("INSERT INTO conversations (id, workspaceId, wahaSession, chatId, canonicalChatId, deliveryChatId, contactId, conversationType, status, lastMessage, lastMessageAt, unreadCount, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'open', ?, ?, ?, ?, ?) ON CONFLICT(workspaceId, wahaSession, chatId) DO UPDATE SET deliveryChatId = excluded.deliveryChatId, contactId = COALESCE(conversations.contactId, excluded.contactId), conversationType = excluded.conversationType, lastMessage = CASE WHEN excluded.lastMessageAt >= conversations.lastMessageAt THEN excluded.lastMessage ELSE conversations.lastMessage END, lastMessageAt = MAX(conversations.lastMessageAt, excluded.lastMessageAt), unreadCount = conversations.unreadCount + excluded.unreadCount, updatedAt = MAX(conversations.updatedAt, excluded.updatedAt)").run(randomUUID(), message.workspaceId, message.wahaSession, message.chatId, message.chatId, message.deliveryChatId, contact?.id ?? null, message.conversationType, messagePreview(message), message.occurredAt, message.historical ? 0 : message.direction === 'inbound' ? 1 : 0, now, now); }
}
export class SupabaseWahaWebhookStore implements WahaWebhookStore, ConversationStore {
  constructor(private readonly client: SupabaseClient, private readonly automation?: KanbanAutomationCoordinator) {}
  async ingest(event: StoredWebhook): Promise<IngestResult> {
    const { error } = await this.client.from('waha_webhook_events').insert({ workspace_id: event.workspaceId, waha_session: event.wahaSession, external_event_id: event.externalEventId, event_type: event.eventType, occurred_at: event.occurredAt, payload_json: sanitize(event.payload), received_at: event.receivedAt });
    if (error) { if (error.code === '23505') return { duplicate: true, messageInserted: false }; throw error; }
    const parsed = messageFrom(event); const message = parsed ? await this.normalize(parsed) : undefined; if (!message) return { duplicate: false, messageInserted: false };
    const { error: messageError } = await this.client.from('whatsapp_messages').insert({ workspace_id: message.workspaceId, waha_session: message.wahaSession, external_message_id: message.externalMessageId, external_event_id: message.externalEventId, chat_id: message.chatId, sender_whatsapp_id: message.senderWhatsappId, sender_contact_id: null, direction: message.direction, message_type: message.messageType, body: message.body, media_url: message.mediaUrl, media_mime_type: message.mediaMimeType, media_filename: message.mediaFilename, media_size: message.mediaSize, thumbnail_url: message.thumbnailUrl, duration: message.duration, quoted_message_id: message.quotedMessageId, occurred_at: message.occurredAt, payload_json: sanitize(message.payload), received_at: message.receivedAt, status: message.direction === 'inbound' ? 'received' : 'sent' });
    if (messageError && messageError.code !== '23505') throw messageError; if (messageError) return { duplicate: false, messageInserted: false, messageId: message.externalMessageId, direction: message.direction }; await this.upsertConversation(message); const { data: conversation, error: conversationError } = await this.client.from('conversations').select('id,visibility_state').eq('workspace_id', message.workspaceId).eq('waha_session', message.wahaSession).eq('chat_id', message.chatId).maybeSingle(); if (conversationError) throw conversationError; const persisted: IngestResult = { duplicate: false, messageInserted: true, conversationId: conversation?.id, messageId: message.externalMessageId, direction: message.direction, historical: message.historical, technical: isTechnical(message), quarantined: conversation?.visibility_state === 'quarantined' }; if (persisted.direction === 'inbound' && persisted.conversationId) await this.automation?.run({ workspaceId: event.workspaceId, conversationId: persisted.conversationId, messageId: persisted.messageId!, direction: 'inbound', historical: persisted.historical, visible: !persisted.quarantined, technical: persisted.technical, quarantined: persisted.quarantined }); return persisted;
  }
  async listConversations(workspaceId: string, page: number, pageSize: number, cursor?: string, search?: string): Promise<CursorPage<ConversationSummary>> { const limit = Math.min(pageSize, 100); const parsed = cursorValue(cursor); let request = this.client.from('conversations').select('id, workspace_id, waha_session, chat_id, delivery_chat_id, contact_id, conversation_type, assigned_user_id, assigned_team_id, assigned_at, routing_queue_id, auto_assigned_at, routing_locked_at, status, priority, last_status_change, last_message, last_message_at, unread_count, created_at, updated_at', { count: 'exact' }).eq('workspace_id', workspaceId).eq('visibility_state', 'visible').order('last_message_at', { ascending: false }).order('id', { ascending: true }).limit(limit + 1); if (parsed) request = request.or(`last_message_at.lt.${parsed.at},and(last_message_at.eq.${parsed.at},id.gt.${parsed.id})`); if (search?.trim()) request = request.or(`chat_id.ilike.%${search.trim()}%,last_message.ilike.%${search.trim()}%`); const { data, error, count } = await request; if (error) throw error; const rows = (data ?? []) as RemoteConversation[]; const more = rows.length > limit; const items = await this.withIdentities(rows.slice(0, limit)); const last = items.at(-1); return { items, page, pageSize: limit, total: count ?? 0, hasMore: more, nextCursor: more && last ? encodeCursor(last.lastMessageAt, last.id) : null }; }
  async listQuarantined(workspaceId: string, page: number, pageSize: number) { const from = (page - 1) * pageSize; const { data, error, count } = await this.client.from('conversations').select('id, workspace_id, waha_session, chat_id, delivery_chat_id, contact_id, conversation_type, assigned_user_id, assigned_team_id, assigned_at, routing_queue_id, auto_assigned_at, routing_locked_at, status, priority, last_status_change, last_message, last_message_at, unread_count, created_at, updated_at', { count: 'exact' }).eq('workspace_id', workspaceId).in('visibility_state', ['quarantined', 'technical']).order('last_message_at', { ascending: false }).order('id', { ascending: true }).range(from, from + pageSize - 1); if (error) throw error; return { items: await this.withIdentities((data ?? []) as RemoteConversation[]), page, pageSize, total: count ?? 0 }; }
  async quarantineCount(workspaceId: string) { const { count, error } = await this.client.from('conversations').select('id', { count: 'exact', head: true }).eq('workspace_id', workspaceId).in('visibility_state', ['quarantined', 'technical']); if (error) throw error; return count ?? 0; }
  async restoreConversation(workspaceId: string, conversationId: string) { const now = new Date().toISOString(); const { data, error } = await this.client.from('conversations').update({ visibility_state: 'visible', integrity_classification: 'inconclusive', integrity_reason_safe: 'restored_manually', integrity_reviewed_at: now, updated_at: now }).eq('workspace_id', workspaceId).eq('id', conversationId).in('visibility_state', ['quarantined', 'technical']).select('id'); if (error) throw error; return (data?.length ?? 0) > 0; }
  async getConversation(workspaceId: string, conversationId: string) { const { data, error } = await this.client.from('conversations').select('id, workspace_id, waha_session, chat_id, delivery_chat_id, contact_id, conversation_type, assigned_user_id, assigned_team_id, assigned_at, routing_queue_id, auto_assigned_at, routing_locked_at, status, priority, last_status_change, last_message, last_message_at, unread_count, created_at, updated_at').eq('workspace_id', workspaceId).eq('id', conversationId).maybeSingle(); if (error) throw error; return data ? (await this.withIdentities([data as RemoteConversation]))[0] : undefined; }
  private async withIdentities(rows: RemoteConversation[]): Promise<ConversationSummary[]> { if (!rows.length) return []; const sessions = [...new Set(rows.map(row => row.waha_session))]; const chatIds = [...new Set(rows.map(row => row.chat_id))]; const [identityResult, groupResult] = await Promise.all([this.client.from('whatsapp_identities').select('waha_session, whatsapp_id, phone, name, push_name, profile_picture_url, updated_at').in('waha_session', sessions).in('whatsapp_id', chatIds), this.client.from('whatsapp_groups').select('waha_session, chat_id, name, picture_url, updated_at').in('waha_session', sessions).in('chat_id', chatIds)]); if (identityResult.error) throw identityResult.error; if (groupResult.error) throw groupResult.error; const identities = new Map((identityResult.data ?? []).map(row => [`${row.waha_session}:${row.whatsapp_id}`, row])); const groups = new Map((groupResult.data ?? []).map(row => [`${row.waha_session}:${row.chat_id}`, row])); return rows.map(row => toRemoteConversationSummary(row, identities.get(`${row.waha_session}:${row.chat_id}`), groups.get(`${row.waha_session}:${row.chat_id}`))); }
  async listMessages(workspaceId: string, conversationId: string, page: number, pageSize: number, cursor?: string): Promise<CursorPage<InboxMessage>> { const { data: conversation, error: conversationError } = await this.client.from('conversations').select('waha_session, chat_id, conversation_type').eq('workspace_id', workspaceId).eq('id', conversationId).maybeSingle(); if (conversationError) throw conversationError; const limit = conversation?.conversation_type === 'group' ? Math.min(pageSize, 100) : 10_000; if (!conversation) return { items: [], page, pageSize: limit, total: 0, hasMore: false, nextCursor: null }; const parsed = conversation.conversation_type === 'group' ? cursorValue(cursor) : undefined; const result = await this.messageRows(workspaceId, conversation.waha_session, conversation.chat_id, 0, limit + 1, true, parsed); if (result.error && !missingMediaColumns(result.error)) throw result.error; const fallback = result.error ? await this.messageRows(workspaceId, conversation.waha_session, conversation.chat_id, 0, limit + 1, false, parsed) : result; if (fallback.error) throw fallback.error; const rows = (fallback.data ?? []) as unknown as RemoteMessageRow[]; const more = conversation.conversation_type === 'group' && rows.length > limit; const selected = rows.slice(0, limit); const last = selected.at(-1); return { items: selected.reverse().map(row => ({ id: row.external_message_id, direction: row.direction, content: row.body, timestamp: row.occurred_at, status: row.status, messageType: row.message_type, chatId: row.chat_id, senderWhatsappId: row.sender_whatsapp_id, mediaUrl: row.media_url ?? null, mediaMimeType: row.media_mime_type ?? null, mediaFilename: row.media_filename ?? null, mediaSize: row.media_size ?? null, thumbnailUrl: row.thumbnail_url ?? null, duration: row.duration ?? null, quotedMessageId: row.quoted_message_id ?? null, metadata: row.payload_json })) as InboxMessage[], page, pageSize: limit, total: fallback.count ?? 0, hasMore: more, nextCursor: more && last ? encodeCursor(last.occurred_at, last.external_message_id) : null }; }
  async getMedia(workspaceId: string, messageId: string) { const { data, error } = await this.client.from('whatsapp_messages').select('media_url, media_mime_type, media_filename, media_storage_path').eq('workspace_id', workspaceId).eq('external_message_id', messageId).not('media_url', 'is', null).maybeSingle(); if (error) throw error; return data?.media_url ? { url: data.media_url, mimeType: data.media_mime_type, filename: data.media_filename, storagePath: data.media_storage_path } : undefined; }
  async persistMedia(input: { workspaceId: string; externalMessageId: string; storagePath: string; checksum: string; size: number; mimeType: string; filename: string }) { const { error } = await this.client.from('whatsapp_messages').update({ media_storage_path: input.storagePath, media_checksum: input.checksum, media_size: input.size, media_mime_type: input.mimeType, media_filename: input.filename, media_persistence_status: 'stored' }).eq('workspace_id', input.workspaceId).eq('external_message_id', input.externalMessageId); if (error) throw error; }
  async pendingMedia(limit: number) { const { data, error } = await this.client.from('whatsapp_messages').select('workspace_id, external_message_id, media_url, media_mime_type, media_filename').not('media_url', 'is', null).is('media_storage_path', null).neq('media_persistence_status', 'unavailable').limit(limit); if (error) throw error; return (data ?? []).map(row => ({ workspaceId: row.workspace_id, externalMessageId: row.external_message_id, url: row.media_url, mimeType: row.media_mime_type, filename: row.media_filename })); }
  async storedMediaWithGenericMime(limit: number) { const { data, error } = await this.client.from('whatsapp_messages').select('workspace_id, external_message_id, media_storage_path, media_mime_type, message_type').not('media_storage_path', 'is', null).in('media_mime_type', ['application/mp4', 'application/octet-stream']).limit(limit); if (error) throw error; return (data ?? []).map(row => ({ workspaceId: row.workspace_id, externalMessageId: row.external_message_id, storagePath: row.media_storage_path, mimeType: row.media_mime_type, messageType: row.message_type })); }
  async updateMediaMime(workspaceId: string, externalMessageId: string, mimeType: string) { const { error } = await this.client.from('whatsapp_messages').update({ media_mime_type: mimeType }).eq('workspace_id', workspaceId).eq('external_message_id', externalMessageId); if (error) throw error; }
  async markMediaUnavailable(workspaceId: string, externalMessageId: string) { const { error } = await this.client.from('whatsapp_messages').update({ media_persistence_status: 'unavailable' }).eq('workspace_id', workspaceId).eq('external_message_id', externalMessageId).is('media_storage_path', null); if (error) throw error; }
  private messageRows(workspaceId: string, session: string, chatId: string, from: number, pageSize: number, includeMedia: boolean, cursor?: { at: string; id: string }) { let request = this.client.from('whatsapp_messages').select(includeMedia ? 'external_message_id, direction, body, occurred_at, status, message_type, chat_id, sender_whatsapp_id, payload_json, media_url, media_mime_type, media_filename, media_size, thumbnail_url, duration, quoted_message_id' : 'external_message_id, direction, body, occurred_at, status, message_type, chat_id, sender_whatsapp_id, payload_json', { count: 'exact' }).eq('workspace_id', workspaceId).eq('waha_session', session).eq('chat_id', chatId).order('occurred_at', { ascending: false }).order('external_message_id', { ascending: false }).range(from, from + pageSize - 1); if (cursor) request = request.or(`occurred_at.lt.${cursor.at},and(occurred_at.eq.${cursor.at},external_message_id.lt.${cursor.id})`); return request; }
  async markRead(workspaceId: string, conversationId: string): Promise<boolean> { const { data, error } = await this.client.from('conversations').update({ unread_count: 0, updated_at: new Date().toISOString() }).eq('workspace_id', workspaceId).eq('id', conversationId).select('id'); if (error) throw error; return (data?.length ?? 0) > 0; }
  async recordOutbound(input: { workspaceId: string; wahaSession: string; chatId: string; externalMessageId: string; text: string; occurredAt: string }): Promise<PersistedOutboundMessage> { const persistence = await this.ingest(outboundRecord(input)); return { id: input.externalMessageId, direction: 'outbound', content: input.text, timestamp: input.occurredAt, status: 'sent', messageType: 'text', chatId: input.chatId, senderWhatsappId: input.chatId, metadata: {}, persistence }; }
  async setAssignment(workspaceId: string, conversationId: string, assignedUserId: string | null, actorUserId: string) { return this.change(workspaceId, conversationId, actorUserId, 'assigned_user_id', assignedUserId); }
  async setTeamAssignment(workspaceId: string, conversationId: string, assignedTeamId: string | null, actorUserId: string) { return this.change(workspaceId, conversationId, actorUserId, 'assigned_team_id', assignedTeamId); }
  async setStatus(workspaceId: string, conversationId: string, status: ConversationStatus, actorUserId: string) { return this.change(workspaceId, conversationId, actorUserId, 'status', status); }
  async setPriority(workspaceId: string, conversationId: string, priority: ConversationPriority, actorUserId: string) { return this.change(workspaceId, conversationId, actorUserId, 'priority', priority); }
  async listActivity(workspaceId: string, conversationId: string) { const exists = await this.getConversation(workspaceId, conversationId); if (!exists) return undefined; const { data, error } = await this.client.from('conversation_events').select('id, conversation_id, workspace_id, user_id, action, previous_value, new_value, created_at').eq('workspace_id', workspaceId).eq('conversation_id', conversationId).order('created_at', { ascending: false }); if (error) throw error; return (data ?? []).map(row => ({ id: row.id, conversationId: row.conversation_id, workspaceId: row.workspace_id, userId: row.user_id, action: row.action, previousValue: row.previous_value, newValue: row.new_value, createdAt: row.created_at })) as ConversationEvent[]; }
  private async change(workspaceId: string, conversationId: string, actorUserId: string, field: 'assigned_user_id' | 'assigned_team_id' | 'status' | 'priority', value: string | null): Promise<ConversationEvent | undefined> { const { data, error: currentError } = await this.client.from('conversations').select(`id, ${field}`).eq('workspace_id', workspaceId).eq('id', conversationId).maybeSingle(); const current = data as Record<string, unknown> | null; if (currentError) throw currentError; if (!current || current[field] === value) return undefined; const now = new Date().toISOString(); const previousValue = current[field] as string | null; const action: ConversationEventAction = field === 'assigned_user_id' || field === 'assigned_team_id' ? (value ? 'assigned' : 'unassigned') : field === 'priority' ? 'priority_changed' : value === 'archived' ? 'archived' : previousValue === 'archived' && value === 'open' ? 'reopened' : 'status_changed'; const changes: Record<string, unknown> = { [field]: value, updated_at: now }; if (field === 'assigned_user_id') { changes.assigned_at = value ? now : null; changes.routing_locked_at = now; } if (field === 'status') changes.last_status_change = now; const { error } = await this.client.from('conversations').update(changes).eq('workspace_id', workspaceId).eq('id', conversationId); if (error) throw error; const event: ConversationEvent = { id: randomUUID(), conversationId, workspaceId, userId: actorUserId, action, previousValue, newValue: value, createdAt: now }; const { error: eventError } = await this.client.from('conversation_events').insert({ id: event.id, conversation_id: event.conversationId, workspace_id: event.workspaceId, user_id: event.userId, action: event.action, previous_value: event.previousValue, new_value: event.newValue, created_at: event.createdAt }); if (eventError) throw eventError; return event; }
  private async normalize(message: StoredMessage): Promise<StoredMessage> { if (message.conversationType === 'group') return message; const { data, error } = await this.client.from('whatsapp_identities').select('canonical_whatsapp_id').eq('workspace_id', message.workspaceId).eq('waha_session', message.wahaSession).eq('whatsapp_id', message.chatId).maybeSingle(); if (error) throw error; const canonical = data?.canonical_whatsapp_id || message.chatId; return { ...message, chatId: canonical, deliveryChatId: canonical.endsWith('@c.us') ? canonical : message.deliveryChatId }; }
  private async upsertConversation(message: StoredMessage): Promise<void> { const phone = phoneFromChat(message.chatId); const { data: contact, error: contactError } = message.conversationType === 'direct' ? await this.client.from('contacts').select('id').eq('workspace_id', message.workspaceId).eq('phone_number', phone).maybeSingle() : { data: null, error: null }; if (contactError) throw contactError; const { data: existing, error: existingError } = await this.client.from('conversations').select('id, contact_id, unread_count, last_message_at, last_message, last_status_change, updated_at').eq('workspace_id', message.workspaceId).eq('waha_session', message.wahaSession).eq('chat_id', message.chatId).maybeSingle(); if (existingError) throw existingError; const newer = !existing || message.occurredAt >= existing.last_message_at; const row = { workspace_id: message.workspaceId, waha_session: message.wahaSession, chat_id: message.chatId, canonical_chat_id: message.chatId, delivery_chat_id: message.deliveryChatId, contact_id: existing?.contact_id ?? contact?.id ?? null, conversation_type: message.conversationType, status: 'open', last_status_change: existing?.last_status_change ?? message.occurredAt, last_message: newer ? messagePreview(message) : existing.last_message, last_message_at: newer ? message.occurredAt : existing.last_message_at, unread_count: (existing?.unread_count ?? 0) + (message.historical ? 0 : message.direction === 'inbound' ? 1 : 0), updated_at: newer ? message.receivedAt : existing!.updated_at }; const result = existing ? await this.client.from('conversations').update(row).eq('workspace_id', message.workspaceId).eq('id', existing.id) : await this.client.from('conversations').insert({ ...row, id: randomUUID(), created_at: message.receivedAt }); if (result.error) throw result.error; }
}
export function webhookRecord(event: WahaWebhookEvent, workspaceId: string): StoredWebhook { const receivedAt = new Date().toISOString(); return { workspaceId, wahaSession: event.session, externalEventId: event.id, eventType: event.event, occurredAt: timestampFrom(event.payload.timestamp, new Date(event.timestamp).toISOString()), payload: event.payload, receivedAt }; }
export function historyRecord(workspaceId: string, wahaSession: string, payload: Record<string, unknown>, listedChatId?: string): StoredWebhook | undefined { const id = text(payload.id) ?? text(nested(payload, 'key', 'id')); const timestamp = timestampFrom(payload.timestamp, new Date().toISOString()); return id ? { workspaceId, wahaSession, externalEventId: `history:${id}`, eventType: 'message.any', occurredAt: timestamp, payload: { ...payload, ...(listedChatId ? { chatId: listedChatId, _historyChatId: listedChatId } : {}), _history: true }, receivedAt: new Date().toISOString() } : undefined; }
function outboundRecord(input: { workspaceId: string; wahaSession: string; chatId: string; externalMessageId: string; text: string; occurredAt: string }): StoredWebhook { return { workspaceId: input.workspaceId, wahaSession: input.wahaSession, externalEventId: `outbound:${input.externalMessageId}`, eventType: 'message.any', occurredAt: input.occurredAt, payload: { id: input.externalMessageId, chatId: input.chatId, body: input.text, type: 'text', fromMe: true }, receivedAt: new Date().toISOString() }; }
function messageFrom(event: StoredWebhook): StoredMessage | undefined { if (event.eventType !== 'message' && event.eventType !== 'message.any') return undefined; const value = event.payload; const id = text(value.id) ?? text(nested(value, 'key', 'id')); const direction = value.fromMe === true ? 'outbound' : 'inbound'; const lockedHistoryChatId = value._history === true ? text(value._historyChatId) : undefined; const identity = resolveConversationIdentity(lockedHistoryChatId ? { direction, chatId: lockedHistoryChatId } : { direction, chatId: text(value.chatId), from: text(value.from), to: text(value.to), remoteJid: text(nested(value, 'key', 'remoteJid')), participant: text(value.participant) ?? text(nested(value, 'key', 'participant')) }); if (!id || !identity) return undefined; const media = record(value.media); const mime = text(media?.mimetype) ?? text(media?.mimeType); const messageType = mediaType(text(value.type), mime, value.hasMedia === true); return { ...event, externalMessageId: id, chatId: identity.conversationChatId, deliveryChatId: identity.deliveryChatId, conversationType: identity.conversationType, senderWhatsappId: identity.conversationType === 'group' ? text(value.participant) ?? text(nested(value, 'key', 'participant')) ?? null : identity.conversationChatId, direction, messageType, body: text(value.body) ?? text(value.text) ?? null, mediaUrl: safeUrl(text(media?.url) ?? text(value.mediaUrl)), mediaMimeType: mime ?? null, mediaFilename: text(media?.filename) ?? text(value.filename) ?? null, mediaSize: integer(media?.filesize) ?? integer(media?.size) ?? integer(value.mediaSize), thumbnailUrl: safeUrl(text(media?.thumbnailUrl) ?? text(value.thumbnailUrl)), duration: integer(media?.duration) ?? integer(value.duration), quotedMessageId: text(value.replyTo) ?? text(nested(value, 'quoted', 'id')) ?? null, historical: value._history === true }; }
function isTechnical(message: StoredMessage): boolean { const payload = message.payload; const type = text(payload.type)?.toLowerCase() ?? ''; return ['ack', 'receipt', 'reaction', 'status', 'protocol', 'revoked'].includes(type) || message.chatId === 'status@broadcast'; }
function timestampFrom(value: unknown, fallback: string): string { const numeric = typeof value === 'number' ? value : typeof value === 'string' && /^\d+(?:\.\d+)?$/.test(value) ? Number(value) : undefined; if (numeric !== undefined && Number.isFinite(numeric)) return new Date(numeric < 100_000_000_000 ? numeric * 1_000 : numeric).toISOString(); if (typeof value === 'string' && !Number.isNaN(Date.parse(value))) return new Date(value).toISOString(); return fallback; }
function nested(value: Record<string, unknown>, key: string, child: string): unknown { const parent = value[key]; return parent && typeof parent === 'object' ? (parent as Record<string, unknown>)[child] : undefined; }
function text(value: unknown): string | undefined { return typeof value === 'string' && value.length > 0 ? value.slice(0, 20_000) : undefined; }
function record(value: unknown): Record<string, unknown> | undefined { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : undefined; }
function integer(value: unknown): number | null { return typeof value === 'number' && Number.isSafeInteger(value) && value >= 0 ? value : null; }
function safeUrl(value: string | undefined): string | null { if (!value) return null; try { const url = new URL(value); return url.protocol === 'http:' || url.protocol === 'https:' ? url.toString() : null; } catch { return null; } }
function encodeCursor(at: string, id: string) { return Buffer.from(JSON.stringify({ at, id })).toString('base64url'); }
function cursorValue(cursor?: string): { at: string; id: string } | undefined { if (!cursor) return undefined; try { const value = JSON.parse(Buffer.from(cursor, 'base64url').toString('utf8')); return typeof value.at === 'string' && typeof value.id === 'string' && !Number.isNaN(Date.parse(value.at)) && value.id ? value : undefined; } catch { return undefined; } }
function mediaType(type: string | undefined, mime: string | undefined, hasMedia: boolean): string { if (type && type !== 'text') return type.toLowerCase(); if (!hasMedia && !mime) return 'text'; if (mime?.startsWith('image/')) return 'image'; if (mime?.startsWith('video/')) return 'video'; if (mime?.startsWith('audio/')) return 'audio'; return 'document'; }
export function messagePreview(message: Pick<StoredMessage, 'messageType' | 'body' | 'mediaFilename'>): string { const caption = message.body?.trim(); switch (message.messageType) { case 'text': return caption || 'Mensagem'; case 'image': return caption ? `Foto: ${caption}` : 'Foto'; case 'video': return caption ? `Vídeo: ${caption}` : 'Vídeo'; case 'audio': return 'Áudio'; case 'ptt': case 'voice': return 'Mensagem de voz'; case 'document': return message.mediaFilename ? `Documento: ${message.mediaFilename}` : 'Documento'; case 'sticker': return 'Sticker'; case 'contact': return 'Contato'; case 'location': return 'Localização'; default: return caption || 'Mensagem'; } }
function missingMediaColumns(error: { code?: string; message?: string; details?: string }): boolean { return error.code === '42703' || /media_(url|mime_type|filename|size|storage_path|checksum|persistence_status)|thumbnail_url|quoted_message_id/i.test(`${error.message ?? ''} ${error.details ?? ''}`); }
function phoneFromChat(chatId: string): string { return chatId.split('@', 1)[0].replace(/\D/g, ''); }
type ConversationRow = Omit<ConversationSummary, 'identity'> & { identityPhone: string | null; profileName: string | null; pushName: string | null; identityAvatarUrl: string | null; identityUpdatedAt: string | null; groupName: string | null; groupPictureUrl: string | null; groupUpdatedAt: string | null };
type RemoteConversation = { id: string; workspace_id: string; waha_session: string; chat_id: string; delivery_chat_id?: string; contact_id: string | null; conversation_type: 'direct' | 'group'; assigned_user_id: string | null; assigned_team_id: string | null; assigned_at: string | null; routing_queue_id: string | null; auto_assigned_at: string | null; routing_locked_at: string | null; status: ConversationStatus; priority: ConversationPriority; last_status_change: string | null; last_message: string | null; last_message_at: string; unread_count: number; created_at: string; updated_at: string };
type RemoteMessageRow = { external_message_id: string; direction: 'inbound' | 'outbound'; body: string | null; occurred_at: string; status: InboxMessage['status']; message_type: string; chat_id: string; sender_whatsapp_id: string | null; media_url?: string | null; media_mime_type?: string | null; media_filename?: string | null; media_size?: number | null; thumbnail_url?: string | null; duration?: number | null; quoted_message_id?: string | null; payload_json: Record<string, unknown> };
function identityFor(conversation: { chatId: string; contactId: string | null; conversationType: 'direct' | 'group' }, source?: { phone?: string | null; name?: string | null; pushName?: string | null; push_name?: string | null; profilePictureUrl?: string | null; profile_picture_url?: string | null; updatedAt?: string | null; updated_at?: string | null }, group?: { name?: string | null; pictureUrl?: string | null; picture_url?: string | null; updatedAt?: string | null; updated_at?: string | null }): ConversationIdentity { const isGroup = conversation.conversationType === 'group'; const profileName = isGroup ? group?.name ?? null : source?.name ?? null; const pushName = isGroup ? null : source?.pushName ?? source?.push_name ?? null; const phone = isGroup ? null : (source?.phone ?? (phoneFromChat(conversation.chatId) || null)); const avatarUrl = isGroup ? group?.pictureUrl ?? group?.picture_url ?? null : source?.profilePictureUrl ?? source?.profile_picture_url ?? null; const lastSyncAt = isGroup ? group?.updatedAt ?? group?.updated_at ?? null : source?.updatedAt ?? source?.updated_at ?? null; return { displayName: profileName ?? pushName, phone, pushName, profileName, avatarUrl, lastSyncAt, syncStatus: lastSyncAt ? 'synced' : 'pending', knownContact: !isGroup && Boolean(conversation.contactId) }; }
function toConversationSummary(row: ConversationRow): ConversationSummary { const { identityPhone, profileName, pushName, identityAvatarUrl, identityUpdatedAt, groupName, groupPictureUrl, groupUpdatedAt, ...conversation } = row; return { ...conversation, identity: identityFor(conversation, { phone: identityPhone, name: profileName, pushName, profilePictureUrl: identityAvatarUrl, updatedAt: identityUpdatedAt }, { name: groupName, pictureUrl: groupPictureUrl, updatedAt: groupUpdatedAt }) }; }
function toRemoteConversationSummary(row: RemoteConversation, identity?: { phone?: string | null; name?: string | null; push_name?: string | null; profile_picture_url?: string | null; updated_at?: string | null }, group?: { name?: string | null; picture_url?: string | null; updated_at?: string | null }): ConversationSummary { const conversation = { id: row.id, workspaceId: row.workspace_id, whatsappSessionId: row.waha_session, chatId: row.chat_id, ...(row.delivery_chat_id ? { deliveryChatId: row.delivery_chat_id } : {}), contactId: row.contact_id, conversationType: row.conversation_type, assignedUserId: row.assigned_user_id, assignedTeamId: row.assigned_team_id, assignedAt: row.assigned_at, routingQueueId: row.routing_queue_id, autoAssignedAt: row.auto_assigned_at, routingLockedAt: row.routing_locked_at, status: row.status, priority: row.priority, lastStatusChange: row.last_status_change, lastMessage: row.last_message, lastMessageAt: row.last_message_at, unreadCount: row.unread_count, createdAt: row.created_at, updatedAt: row.updated_at }; return { ...conversation, identity: identityFor(conversation, identity, group) }; }
function isUniqueError(error: unknown): boolean { return error instanceof Error && /unique|constraint/i.test(error.message); }
function sanitize(value: unknown, depth = 0): unknown { if (depth > 12) return '[TRUNCATED]'; if (typeof value === 'string') return value.length > 20_000 ? `${value.slice(0, 20_000)}[TRUNCATED]` : value; if (Array.isArray(value)) return value.slice(0, 200).map(item => sanitize(item, depth + 1)); if (!value || typeof value !== 'object') return value; return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([key, item]) => [key, sensitiveKey.test(key) ? '[REDACTED]' : sanitize(item, depth + 1)])); }
