import { randomUUID } from 'node:crypto';
import type { Database as SqliteDatabase } from 'better-sqlite3';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { InternalWorkerClient } from '../internal-worker-client.js';
import { log } from '../logging.js';

const CACHE_TTL_MS = 24 * 60 * 60 * 1_000;
type Identity = { whatsappId: string; canonicalWhatsappId: string; phone: string | null; name: string | null; pushName: string | null; shortName: string | null; profilePictureUrl: string | null };
type Group = { chatId: string; name: string | null; pictureUrl: string | null; metadata: Record<string, unknown>; participants: Array<{ whatsappId: string; role: string | null }> };
type Snapshot = { identity: Identity | null; group: Group | null };
type DirectConversation = { id: string; chatId: string; canonicalChatId: string | null; deliveryChatId: string | null; contactId: string | null; unreadCount: number; lastMessage: string | null; lastMessageAt: string; createdAt: string; updatedAt: string };
export type IdentitySyncTarget = { workspaceId: string; wahaSession: string; chatId: string; senderWhatsappId?: string };
export interface WhatsAppIdentityStore { identityIsStale(target: IdentitySyncTarget): Promise<boolean>; groupIsStale(target: IdentitySyncTarget): Promise<boolean>; persist(target: IdentitySyncTarget, snapshot: Snapshot): Promise<void>; unresolvedDirectAliases(limit: number): Promise<IdentitySyncTarget[]>; }

export class WhatsAppIdentitySyncService {
  private readonly inFlight = new Set<string>();
  constructor(private readonly worker: InternalWorkerClient, private readonly store: WhatsAppIdentityStore, private readonly onSynchronized?: (target: IdentitySyncTarget) => void) {}
  enqueue(target: IdentitySyncTarget): void { const key = `${target.workspaceId}:${target.wahaSession}:${target.chatId}:${target.senderWhatsappId ?? ''}`; if (this.inFlight.has(key)) return; this.inFlight.add(key); setImmediate(() => { void this.run(target).finally(() => this.inFlight.delete(key)); }); }
  enqueueBackfill(): void { setImmediate(() => { void this.store.unresolvedDirectAliases(200).then(items => items.forEach(item => this.enqueue(item))).catch(error => log('error', 'WAHA identity backfill discovery failed', { errorClass: error instanceof Error ? error.name : 'UnknownError' })); }); }
  private async run(target: IdentitySyncTarget): Promise<void> { try { const [refreshIdentity, refreshGroup] = await Promise.all([this.store.identityIsStale(target), isGroup(target.chatId) ? this.store.groupIsStale(target) : Promise.resolve(false)]); if (!refreshIdentity && !refreshGroup) return; const response = await this.worker.send({ correlationId: `identity-sync-${randomUUID()}`, workspaceId: target.workspaceId, timeoutMs: 10_000, command: { type: 'identity.sync', payload: { wahaSession: target.wahaSession, chatId: target.chatId, ...(target.senderWhatsappId ? { senderWhatsappId: target.senderWhatsappId } : {}), refreshIdentity, refreshGroup } } }); if (!response.success) { log('error', 'WAHA identity synchronization failed', { workspaceId: target.workspaceId, wahaSession: target.wahaSession, code: response.error.code }); return; } const snapshot = (response.data as { identitySync?: Snapshot }).identitySync; if (!snapshot) { log('error', 'WAHA identity synchronization returned invalid data', { workspaceId: target.workspaceId, wahaSession: target.wahaSession }); return; } await this.store.persist(target, snapshot); this.onSynchronized?.(target); log('info', 'WAHA identity synchronized', { workspaceId: target.workspaceId, wahaSession: target.wahaSession, kind: isGroup(target.chatId) ? 'group' : 'direct' }); } catch (error) { log('error', 'WAHA identity synchronization failed', { workspaceId: target.workspaceId, wahaSession: target.wahaSession, errorClass: error instanceof Error ? error.name : 'UnknownError' }); } }
}

export class SqliteWhatsAppIdentityStore implements WhatsAppIdentityStore {
  constructor(private readonly database: SqliteDatabase) {}
  async identityIsStale(target: IdentitySyncTarget): Promise<boolean> { return stale(this.database.prepare('SELECT updatedAt FROM whatsapp_identities WHERE workspaceId = ? AND wahaSession = ? AND whatsappId = ?').get(target.workspaceId, target.wahaSession, target.senderWhatsappId ?? target.chatId) as { updatedAt?: string } | undefined); }
  async groupIsStale(target: IdentitySyncTarget): Promise<boolean> { return stale(this.database.prepare('SELECT updatedAt FROM whatsapp_groups WHERE workspaceId = ? AND wahaSession = ? AND chatId = ?').get(target.workspaceId, target.wahaSession, target.chatId) as { updatedAt?: string } | undefined); }
  async unresolvedDirectAliases(limit: number): Promise<IdentitySyncTarget[]> { return this.database.prepare("SELECT DISTINCT workspaceId, wahaSession, chatId FROM conversations WHERE conversationType = 'direct' AND chatId LIKE '%@lid' AND NOT EXISTS (SELECT 1 FROM whatsapp_identities i WHERE i.workspaceId = conversations.workspaceId AND i.wahaSession = conversations.wahaSession AND i.whatsappId = conversations.chatId AND i.canonicalWhatsappId IS NOT NULL AND i.canonicalWhatsappId <> i.whatsappId) LIMIT ?").all(limit) as IdentitySyncTarget[]; }
  async persist(target: IdentitySyncTarget, snapshot: Snapshot): Promise<void> { const now = new Date().toISOString(); const transaction = this.database.transaction(() => { if (snapshot.identity) { const identity = snapshot.identity; this.database.prepare("INSERT INTO whatsapp_identities (id, workspaceId, wahaSession, whatsappId, canonicalWhatsappId, phone, name, pushName, shortName, profilePictureUrl, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(workspaceId, wahaSession, whatsappId) DO UPDATE SET canonicalWhatsappId = excluded.canonicalWhatsappId, phone = COALESCE(excluded.phone, whatsapp_identities.phone), name = COALESCE(excluded.name, whatsapp_identities.name), pushName = COALESCE(excluded.pushName, whatsapp_identities.pushName), shortName = COALESCE(excluded.shortName, whatsapp_identities.shortName), profilePictureUrl = COALESCE(excluded.profilePictureUrl, whatsapp_identities.profilePictureUrl), updatedAt = excluded.updatedAt").run(randomUUID(), target.workspaceId, target.wahaSession, identity.whatsappId, identity.canonicalWhatsappId, identity.phone, identity.name, identity.pushName, identity.shortName, identity.profilePictureUrl, now, now); if (identity.canonicalWhatsappId !== identity.whatsappId) this.database.prepare("INSERT INTO whatsapp_identities (id, workspaceId, wahaSession, whatsappId, canonicalWhatsappId, phone, name, pushName, shortName, profilePictureUrl, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(workspaceId, wahaSession, whatsappId) DO UPDATE SET canonicalWhatsappId = excluded.canonicalWhatsappId, updatedAt = excluded.updatedAt").run(randomUUID(), target.workspaceId, target.wahaSession, identity.canonicalWhatsappId, identity.canonicalWhatsappId, identity.phone, identity.name, identity.pushName, identity.shortName, identity.profilePictureUrl, now, now); this.reconcile(target.workspaceId, target.wahaSession, identity.canonicalWhatsappId); } if (snapshot.group) this.persistGroup(target, snapshot.group, now); }); transaction(); }
  private persistGroup(target: IdentitySyncTarget, group: Group, now: string): void { this.database.prepare("INSERT INTO whatsapp_groups (id, workspaceId, wahaSession, chatId, name, pictureUrl, metadataJson, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(workspaceId, wahaSession, chatId) DO UPDATE SET name = COALESCE(excluded.name, whatsapp_groups.name), pictureUrl = COALESCE(excluded.pictureUrl, whatsapp_groups.pictureUrl), metadataJson = excluded.metadataJson, updatedAt = excluded.updatedAt").run(randomUUID(), target.workspaceId, target.wahaSession, group.chatId, group.name, group.pictureUrl, JSON.stringify(group.metadata), now, now); const stored = this.database.prepare('SELECT id FROM whatsapp_groups WHERE workspaceId = ? AND wahaSession = ? AND chatId = ?').get(target.workspaceId, target.wahaSession, group.chatId) as { id: string }; const participant = this.database.prepare("INSERT INTO whatsapp_group_participants (id, groupId, participantWhatsappId, role, createdAt) VALUES (?, ?, ?, ?, ?) ON CONFLICT(groupId, participantWhatsappId) DO UPDATE SET role = excluded.role"); for (const item of group.participants) participant.run(randomUUID(), stored.id, item.whatsappId, item.role, now); }
  private reconcile(workspaceId: string, wahaSession: string, canonical: string): void { const aliases = [canonical, ...(this.database.prepare('SELECT whatsappId FROM whatsapp_identities WHERE workspaceId = ? AND wahaSession = ? AND canonicalWhatsappId = ?').all(workspaceId, wahaSession, canonical) as Array<{ whatsappId: string }>).map(row => row.whatsappId)]; const placeholders = aliases.map(() => '?').join(','); const conversations = this.database.prepare(`SELECT id, chatId, canonicalChatId, deliveryChatId, contactId, unreadCount, lastMessage, lastMessageAt, createdAt, updatedAt FROM conversations WHERE workspaceId = ? AND wahaSession = ? AND conversationType = 'direct' AND chatId IN (${placeholders})`).all(workspaceId, wahaSession, ...aliases) as DirectConversation[]; if (!conversations.length) return; const primary = [...conversations].sort((a, b) => Number(b.chatId === canonical || b.canonicalChatId === canonical) - Number(a.chatId === canonical || a.canonicalChatId === canonical) || a.createdAt.localeCompare(b.createdAt))[0]; const latest = [...conversations].sort((a, b) => b.lastMessageAt.localeCompare(a.lastMessageAt))[0]; const unread = conversations.reduce((total, conversation) => total + conversation.unreadCount, 0); const earliest = conversations.reduce((value, conversation) => value < conversation.createdAt ? value : conversation.createdAt, primary.createdAt); const updated = conversations.reduce((value, conversation) => value > conversation.updatedAt ? value : conversation.updatedAt, primary.updatedAt); this.database.prepare(`UPDATE whatsapp_messages SET chatId = ? WHERE workspaceId = ? AND wahaSession = ? AND chatId IN (${placeholders})`).run(canonical, workspaceId, wahaSession, ...aliases); const duplicates = conversations.filter(conversation => conversation.id !== primary.id); if (duplicates.length) this.database.prepare(`DELETE FROM conversations WHERE workspaceId = ? AND id IN (${duplicates.map(() => '?').join(',')})`).run(workspaceId, ...duplicates.map(conversation => conversation.id)); this.database.prepare('UPDATE conversations SET chatId = ?, canonicalChatId = ?, deliveryChatId = ?, unreadCount = ?, lastMessage = ?, lastMessageAt = ?, createdAt = ?, updatedAt = ? WHERE workspaceId = ? AND id = ?').run(canonical, canonical, canonical.endsWith('@c.us') ? canonical : primary.deliveryChatId ?? canonical, unread, latest.lastMessage, latest.lastMessageAt, earliest, updated, workspaceId, primary.id); }
}

export class SupabaseWhatsAppIdentityStore implements WhatsAppIdentityStore {
  constructor(private readonly client: SupabaseClient) {}
  async identityIsStale(target: IdentitySyncTarget): Promise<boolean> { const { data, error } = await this.client.from('whatsapp_identities').select('updated_at').eq('workspace_id', target.workspaceId).eq('waha_session', target.wahaSession).eq('whatsapp_id', target.senderWhatsappId ?? target.chatId).maybeSingle(); if (error) throw error; return stale(data ? { updatedAt: data.updated_at } : undefined); }
  async groupIsStale(target: IdentitySyncTarget): Promise<boolean> { const { data, error } = await this.client.from('whatsapp_groups').select('updated_at').eq('workspace_id', target.workspaceId).eq('waha_session', target.wahaSession).eq('chat_id', target.chatId).maybeSingle(); if (error) throw error; return stale(data ? { updatedAt: data.updated_at } : undefined); }
  async unresolvedDirectAliases(limit: number): Promise<IdentitySyncTarget[]> { const { data, error } = await this.client.from('conversations').select('workspace_id, waha_session, chat_id').eq('conversation_type', 'direct').like('chat_id', '%@lid').limit(limit); if (error) throw error; return (data ?? []).map(row => ({ workspaceId: row.workspace_id, wahaSession: row.waha_session, chatId: row.chat_id })); }
  async persist(target: IdentitySyncTarget, snapshot: Snapshot): Promise<void> { const now = new Date().toISOString(); if (snapshot.identity) { const identity = snapshot.identity; const rows = [identity, ...(identity.canonicalWhatsappId === identity.whatsappId ? [] : [{ ...identity, whatsappId: identity.canonicalWhatsappId, canonicalWhatsappId: identity.canonicalWhatsappId }])].map(item => ({ id: randomUUID(), workspace_id: target.workspaceId, waha_session: target.wahaSession, whatsapp_id: item.whatsappId, canonical_whatsapp_id: item.canonicalWhatsappId, phone: item.phone, name: item.name, push_name: item.pushName, short_name: item.shortName, profile_picture_url: item.profilePictureUrl, created_at: now, updated_at: now })); const { error } = await this.client.from('whatsapp_identities').upsert(rows, { onConflict: 'workspace_id,waha_session,whatsapp_id' }); if (error) throw error; await this.reconcile(target.workspaceId, target.wahaSession, identity.canonicalWhatsappId); } if (snapshot.group) { const group = snapshot.group; const { error } = await this.client.from('whatsapp_groups').upsert({ id: randomUUID(), workspace_id: target.workspaceId, waha_session: target.wahaSession, chat_id: group.chatId, name: group.name, picture_url: group.pictureUrl, metadata: group.metadata, created_at: now, updated_at: now }, { onConflict: 'workspace_id,waha_session,chat_id' }); if (error) throw error; const { data: stored, error: lookupError } = await this.client.from('whatsapp_groups').select('id').eq('workspace_id', target.workspaceId).eq('waha_session', target.wahaSession).eq('chat_id', group.chatId).single(); if (lookupError || !stored) throw lookupError ?? new Error('WAHA group was not persisted'); if (group.participants.length) { const { error: participantError } = await this.client.from('whatsapp_group_participants').upsert(group.participants.map(item => ({ id: randomUUID(), group_id: stored.id, participant_whatsapp_id: item.whatsappId, role: item.role, created_at: now })), { onConflict: 'group_id,participant_whatsapp_id' }); if (participantError) throw participantError; } } }
  private async reconcile(workspaceId: string, wahaSession: string, canonical: string): Promise<void> { const { data: identityRows, error: identityError } = await this.client.from('whatsapp_identities').select('whatsapp_id').eq('workspace_id', workspaceId).eq('waha_session', wahaSession).eq('canonical_whatsapp_id', canonical); if (identityError) throw identityError; const aliases = [canonical, ...(identityRows ?? []).map(row => row.whatsapp_id)]; const { data, error } = await this.client.from('conversations').select('id, chat_id, canonical_chat_id, delivery_chat_id, contact_id, unread_count, last_message, last_message_at, created_at, updated_at').eq('workspace_id', workspaceId).eq('waha_session', wahaSession).eq('conversation_type', 'direct').in('chat_id', aliases); if (error) throw error; const conversations = (data ?? []).map(row => ({ id: row.id, chatId: row.chat_id, canonicalChatId: row.canonical_chat_id, deliveryChatId: row.delivery_chat_id, contactId: row.contact_id, unreadCount: row.unread_count, lastMessage: row.last_message, lastMessageAt: row.last_message_at, createdAt: row.created_at, updatedAt: row.updated_at })) as DirectConversation[]; if (!conversations.length) return; const primary = [...conversations].sort((a, b) => Number(b.chatId === canonical || b.canonicalChatId === canonical) - Number(a.chatId === canonical || a.canonicalChatId === canonical) || a.createdAt.localeCompare(b.createdAt))[0]; const latest = [...conversations].sort((a, b) => b.lastMessageAt.localeCompare(a.lastMessageAt))[0]; const unread = conversations.reduce((total, conversation) => total + conversation.unreadCount, 0); const earliest = conversations.reduce((value, conversation) => value < conversation.createdAt ? value : conversation.createdAt, primary.createdAt); const updated = conversations.reduce((value, conversation) => value > conversation.updatedAt ? value : conversation.updatedAt, primary.updatedAt); const { error: messagesError } = await this.client.from('whatsapp_messages').update({ chat_id: canonical }).eq('workspace_id', workspaceId).eq('waha_session', wahaSession).in('chat_id', aliases); if (messagesError) throw messagesError; const duplicates = conversations.filter(conversation => conversation.id !== primary.id); if (duplicates.length) { const { error: deleteError } = await this.client.from('conversations').delete().eq('workspace_id', workspaceId).in('id', duplicates.map(conversation => conversation.id)); if (deleteError) throw deleteError; } const { error: updateError } = await this.client.from('conversations').update({ chat_id: canonical, canonical_chat_id: canonical, delivery_chat_id: canonical.endsWith('@c.us') ? canonical : primary.deliveryChatId ?? canonical, unread_count: unread, last_message: latest.lastMessage, last_message_at: latest.lastMessageAt, created_at: earliest, updated_at: updated }).eq('workspace_id', workspaceId).eq('id', primary.id); if (updateError) throw updateError; }
}

function stale(row: { updatedAt?: string } | undefined): boolean { return !row?.updatedAt || Number.isNaN(Date.parse(row.updatedAt)) || Date.now() - Date.parse(row.updatedAt) >= CACHE_TTL_MS; }
function isGroup(chatId: string): boolean { return chatId.endsWith('@g.us'); }
