import { randomUUID } from 'node:crypto';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { SqliteDatabase } from '../persistence/database.js';
import { InternalWorkerClient } from '../internal-worker-client.js';
import type { RealtimeHub } from '../realtime.js';
import { historyRecord, type WahaWebhookStore } from './waha-webhook.service.js';

export type SyncJob = { id: string; workspaceId: string; wahaSession: string; status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled'; currentChatId: string | null; chatCursor: string | null; messageCursor: string | null; chatsProcessed: number; messagesProcessed: number; startedAt: string; completedAt: string | null; lastErrorSafe: string | null; updatedAt: string };
type Store = { get(workspaceId: string, wahaSession: string): Promise<SyncJob | undefined>; save(job: SyncJob): Promise<void> };

export class WhatsAppHistorySyncService {
  private readonly active = new Set<string>();
  constructor(private readonly worker: InternalWorkerClient, private readonly messages: WahaWebhookStore, private readonly jobs: Store, private readonly realtime: RealtimeHub) {}
  async start(workspaceId: string, wahaSession: string): Promise<SyncJob> { await this.page({ workspaceId, wahaSession } as SyncJob, undefined, 0, 1); const previous = await this.jobs.get(workspaceId, wahaSession); const now = new Date().toISOString(); const job: SyncJob = previous && !['completed', 'cancelled'].includes(previous.status) ? { ...previous, status: 'pending', lastErrorSafe: null, updatedAt: now } : { id: previous?.id ?? randomUUID(), workspaceId, wahaSession, status: 'pending', currentChatId: previous?.currentChatId ?? null, chatCursor: previous?.chatCursor ?? '0', messageCursor: previous?.messageCursor ?? '0', chatsProcessed: previous?.chatsProcessed ?? 0, messagesProcessed: previous?.messagesProcessed ?? 0, startedAt: previous?.startedAt ?? now, completedAt: null, lastErrorSafe: null, updatedAt: now }; await this.jobs.save(job); this.launch(job); return job; }
  async status(workspaceId: string, wahaSession: string): Promise<SyncJob | undefined> { return this.jobs.get(workspaceId, wahaSession); }
  async cancel(workspaceId: string, wahaSession: string): Promise<SyncJob | undefined> { const job = await this.jobs.get(workspaceId, wahaSession); if (!job) return undefined; const cancelled = { ...job, status: 'cancelled' as const, updatedAt: new Date().toISOString() }; await this.jobs.save(cancelled); this.publish(cancelled); return cancelled; }
  private launch(job: SyncJob): void { const key = `${job.workspaceId}:${job.wahaSession}`; if (this.active.has(key)) return; this.active.add(key); setImmediate(() => { void this.run(job.workspaceId, job.wahaSession).finally(() => this.active.delete(key)); }); }
  private async run(workspaceId: string, wahaSession: string): Promise<void> { let job = await this.jobs.get(workspaceId, wahaSession); if (!job) return; try { job = await this.save({ ...job, status: 'running', updatedAt: new Date().toISOString() }); while (job.status === 'running') { if (!job.currentChatId) { const page = await this.page(job, undefined, Number(job.chatCursor ?? 0), 20); if (!page.items.length) { job = await this.save({ ...job, status: 'completed', completedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); break; } const chat = page.items[0]; const chatId = typeof chat.id === 'string' ? chat.id : null; if (!chatId) { job = await this.save({ ...job, chatCursor: String(Number(job.chatCursor ?? 0) + 1), updatedAt: new Date().toISOString() }); continue; } job = await this.save({ ...job, currentChatId: chatId, messageCursor: '0', updatedAt: new Date().toISOString() }); continue; } const page = await this.page(job, job.currentChatId, Number(job.messageCursor ?? 0), 50); for (const message of page.items) { const record = historyRecord(workspaceId, wahaSession, message); if (record) { await this.messages.ingest(record); job = { ...job, messagesProcessed: job.messagesProcessed + 1 }; } } if (page.hasMore) job = await this.save({ ...job, messageCursor: String(Number(job.messageCursor ?? 0) + 50), updatedAt: new Date().toISOString() }); else job = await this.save({ ...job, currentChatId: null, messageCursor: null, chatCursor: String(Number(job.chatCursor ?? 0) + 1), chatsProcessed: job.chatsProcessed + 1, updatedAt: new Date().toISOString() }); const latest = await this.jobs.get(workspaceId, wahaSession); if (!latest || latest.status === 'cancelled') break; job = latest; } } catch (error) { if (!job) return; await this.save({ ...job, status: 'failed', lastErrorSafe: safeError(error), updatedAt: new Date().toISOString() }); } }
  private async page(job: SyncJob, chatId: string | undefined, offset: number, limit: number): Promise<{ items: Record<string, unknown>[]; hasMore: boolean }> { const response = await this.worker.send({ correlationId: `history-sync-${randomUUID()}`, workspaceId: job.workspaceId, timeoutMs: 30_000, command: { type: 'history.page', payload: { wahaSession: job.wahaSession, ...(chatId ? { chatId } : {}), offset, limit } } }); if (!response.success) throw new Error(response.error.code); const page = (response.data as { historyPage?: { items?: Record<string, unknown>[]; hasMore?: boolean } }).historyPage; if (!page) throw new Error('Invalid history response'); return { items: page.items ?? [], hasMore: page.hasMore === true }; }
  private async save(job: SyncJob): Promise<SyncJob> { await this.jobs.save(job); this.publish(job); return job; }
  private publish(job: SyncJob): void { this.realtime.publish(job.workspaceId, 'conversation.sync.updated', { wahaSession: job.wahaSession, status: job.status, chatsProcessed: job.chatsProcessed, messagesProcessed: job.messagesProcessed }); }
}

export class SqliteWhatsAppHistorySyncStore implements Store { constructor(private readonly db: SqliteDatabase) {} async get(workspaceId: string, wahaSession: string) { const row = this.db.prepare('SELECT * FROM whatsapp_sync_jobs WHERE workspaceId=? AND wahaSession=?').get(workspaceId, wahaSession) as Record<string, unknown> | undefined; return row ? sqliteJob(row) : undefined; } async save(job: SyncJob) { this.db.prepare('INSERT INTO whatsapp_sync_jobs (id,workspaceId,wahaSession,status,currentChatId,chatCursor,messageCursor,chatsProcessed,messagesProcessed,startedAt,completedAt,lastErrorSafe,updatedAt) VALUES (@id,@workspaceId,@wahaSession,@status,@currentChatId,@chatCursor,@messageCursor,@chatsProcessed,@messagesProcessed,@startedAt,@completedAt,@lastErrorSafe,@updatedAt) ON CONFLICT(workspaceId,wahaSession) DO UPDATE SET status=excluded.status,currentChatId=excluded.currentChatId,chatCursor=excluded.chatCursor,messageCursor=excluded.messageCursor,chatsProcessed=excluded.chatsProcessed,messagesProcessed=excluded.messagesProcessed,completedAt=excluded.completedAt,lastErrorSafe=excluded.lastErrorSafe,updatedAt=excluded.updatedAt').run(job); } }
export class SupabaseWhatsAppHistorySyncStore implements Store { constructor(private readonly client: SupabaseClient) {} async get(workspaceId: string, wahaSession: string) { const { data, error } = await this.client.from('whatsapp_sync_jobs').select().eq('workspace_id', workspaceId).eq('waha_session', wahaSession).maybeSingle(); if (error) throw error; return data ? remoteJob(data) : undefined; } async save(job: SyncJob) { const { error } = await this.client.from('whatsapp_sync_jobs').upsert({ id: job.id, workspace_id: job.workspaceId, waha_session: job.wahaSession, status: job.status, current_chat_id: job.currentChatId, chat_cursor: job.chatCursor, message_cursor: job.messageCursor, chats_processed: job.chatsProcessed, messages_processed: job.messagesProcessed, started_at: job.startedAt, completed_at: job.completedAt, last_error_safe: job.lastErrorSafe, updated_at: job.updatedAt }, { onConflict: 'workspace_id,waha_session' }); if (error) throw error; } }
function sqliteJob(row: Record<string, unknown>): SyncJob { return row as unknown as SyncJob; }
function remoteJob(row: Record<string, any>): SyncJob { return { id: row.id, workspaceId: row.workspace_id, wahaSession: row.waha_session, status: row.status, currentChatId: row.current_chat_id, chatCursor: row.chat_cursor, messageCursor: row.message_cursor, chatsProcessed: row.chats_processed, messagesProcessed: row.messages_processed, startedAt: row.started_at, completedAt: row.completed_at, lastErrorSafe: row.last_error_safe, updatedAt: row.updated_at }; }
function safeError(error: unknown): string { return (error instanceof Error ? error.message : 'History synchronization failed').replace(/(api[_-]?key|authorization|token|secret|password)\s*[:=]\s*[^\s,;]+/gi, '$1=[REDACTED]').slice(0, 240); }
