import { randomUUID } from 'node:crypto';
import { AppError } from '../errors.js';
import type { RequestContext, Team, TeamMember, WorkspaceUser } from '@chatpro/contracts';
import type { RealtimeHub } from '../realtime.js';
import type { SqliteDatabase } from '../persistence/database.js';
import type { SupabaseClient } from '@supabase/supabase-js';

export type UserRole = WorkspaceUser['role'];
export type UserStatus = WorkspaceUser['status'];
export type DirectoryStore = {
  listUsers(workspaceId: string): Promise<WorkspaceUser[]>; getUser(workspaceId: string, id: string): Promise<WorkspaceUser | undefined>; saveUser(user: WorkspaceUser): Promise<WorkspaceUser>; 
  listTeams(workspaceId: string): Promise<Team[]>; getTeam(workspaceId: string, id: string): Promise<Team | undefined>; saveTeam(team: Omit<Team, 'memberCount'>): Promise<Team>;
  addMember(workspaceId: string, member: TeamMember): Promise<TeamMember>; removeMember(workspaceId: string, teamId: string, userId: string): Promise<boolean>; members(workspaceId: string, teamId: string): Promise<TeamMember[]>;
};
const roles: UserRole[] = ['owner', 'admin', 'manager', 'agent'];
const now = () => new Date().toISOString();
const canManageDirectory = (role: UserRole) => role === 'owner' || role === 'admin';
const canAssign = (role: UserRole) => roles.includes(role);

export class WorkspaceDirectoryService {
  constructor(private readonly store: DirectoryStore, private readonly realtime: RealtimeHub, private readonly developmentUserId?: string) {}
  async listUsers(context: RequestContext) { await this.ensureDevelopmentActor(context); return this.store.listUsers(context.workspaceId); }
  async listTeams(context: RequestContext) { await this.ensureDevelopmentActor(context); return this.store.listTeams(context.workspaceId); }
  async createUser(context: RequestContext, input: { email: string; displayName: string; avatarUrl?: string | null; role?: UserRole; status?: UserStatus }) { await this.requireDirectoryAdmin(context); const timestamp = now(); const user: WorkspaceUser = { id: randomUUID(), workspaceId: context.workspaceId, email: input.email.toLowerCase(), displayName: input.displayName, avatarUrl: input.avatarUrl ?? null, role: input.role ?? 'agent', status: input.status ?? 'invited', createdAt: timestamp, updatedAt: timestamp, lastSeenAt: null }; const saved = await this.store.saveUser(user); this.realtime.publish(context.workspaceId, 'workspace.user.created', { user: saved }); return saved; }
  async updateUser(context: RequestContext, id: string, input: Partial<Pick<WorkspaceUser, 'displayName' | 'avatarUrl' | 'role' | 'status'>>) { const actor = await this.requireDirectoryAdmin(context); const current = await this.requireUser(context.workspaceId, id); if (current.role === 'owner' && actor.role !== 'owner') throw new AppError(403, 'FORBIDDEN', 'Only an owner can manage another owner'); if (input.role === 'owner' && actor.role !== 'owner') throw new AppError(403, 'FORBIDDEN', 'Only an owner can grant owner access'); const saved = await this.store.saveUser({ ...current, ...input, updatedAt: now() }); this.realtime.publish(context.workspaceId, 'workspace.user.updated', { user: saved }); return saved; }
  async setUserStatus(context: RequestContext, id: string, status: Extract<UserStatus, 'active' | 'disabled'>) { return this.updateUser(context, id, { status }); }
  async createTeam(context: RequestContext, input: { name: string; description?: string | null; color?: string | null; isActive?: boolean }) { await this.requireDirectoryAdmin(context); const timestamp = now(); const created = await this.store.saveTeam({ id: randomUUID(), workspaceId: context.workspaceId, name: input.name, description: input.description ?? null, color: input.color ?? null, isActive: input.isActive ?? true, createdAt: timestamp, updatedAt: timestamp }); this.realtime.publish(context.workspaceId, 'workspace.team.created', { team: created }); return created; }
  async updateTeam(context: RequestContext, id: string, input: Partial<Pick<Team, 'name' | 'description' | 'color' | 'isActive'>>) { await this.requireDirectoryAdmin(context); const current = await this.requireTeam(context.workspaceId, id); const saved = await this.store.saveTeam({ ...current, ...input, updatedAt: now() }); this.realtime.publish(context.workspaceId, 'workspace.team.updated', { team: saved }); return saved; }
  async addMember(context: RequestContext, teamId: string, input: { userId: string; membershipRole?: TeamMember['membershipRole'] }) { const actor = await this.requireActor(context); const team = await this.requireTeam(context.workspaceId, teamId); if (!canManageDirectory(actor.role) && !(actor.role === 'manager' && (await this.store.members(context.workspaceId, teamId)).some(member => member.userId === actor.id && member.membershipRole === 'leader'))) throw new AppError(403, 'FORBIDDEN', 'You cannot manage this team'); const user = await this.requireUser(context.workspaceId, input.userId); if (user.status === 'disabled') throw new AppError(409, 'CONFLICT', 'Disabled users cannot be added to a team'); const member = await this.store.addMember(context.workspaceId, { teamId: team.id, userId: user.id, membershipRole: input.membershipRole ?? 'member', createdAt: now() }); this.realtime.publish(context.workspaceId, 'workspace.team.members.updated', { teamId, member }); return member; }
  async removeMember(context: RequestContext, teamId: string, userId: string) { const actor = await this.requireActor(context); if (!canManageDirectory(actor.role) && !(actor.role === 'manager' && (await this.store.members(context.workspaceId, teamId)).some(member => member.userId === actor.id && member.membershipRole === 'leader'))) throw new AppError(403, 'FORBIDDEN', 'You cannot manage this team'); await this.requireTeam(context.workspaceId, teamId); const removed = await this.store.removeMember(context.workspaceId, teamId, userId); if (!removed) throw new AppError(404, 'NOT_FOUND', 'Team member not found'); this.realtime.publish(context.workspaceId, 'workspace.team.members.updated', { teamId, userId, removed: true }); }
  async members(context: RequestContext, teamId: string) { await this.ensureDevelopmentActor(context); await this.requireTeam(context.workspaceId, teamId); return this.store.members(context.workspaceId, teamId); }
  async requireAssignableUser(context: RequestContext, userId: string | null) { const actor = await this.requireActor(context); if (!canAssign(actor.role)) throw new AppError(403, 'FORBIDDEN', 'You cannot assign conversations'); if (!userId) return; const user = await this.requireUser(context.workspaceId, userId); if (user.status !== 'active') throw new AppError(409, 'CONFLICT', 'Only active workspace users can receive new assignments'); }
  async requireAssignableTeam(context: RequestContext, teamId: string | null) { const actor = await this.requireActor(context); if (!canAssign(actor.role)) throw new AppError(403, 'FORBIDDEN', 'You cannot assign conversations'); if (!teamId) return; const team = await this.requireTeam(context.workspaceId, teamId); if (!team.isActive) throw new AppError(409, 'CONFLICT', 'Only active teams can receive new assignments'); }
  async requireRoutingAdmin(context: RequestContext) { return this.requireDirectoryAdmin(context); }
  private async requireDirectoryAdmin(context: RequestContext) { const actor = await this.requireActor(context); if (!canManageDirectory(actor.role)) throw new AppError(403, 'FORBIDDEN', 'Only owners and admins can manage workspace users and teams'); return actor; }
  private async requireActor(context: RequestContext) { await this.ensureDevelopmentActor(context); if (!context.userId) throw new AppError(401, 'UNAUTHORIZED', 'A workspace user is required'); const actor = await this.store.getUser(context.workspaceId, context.userId); if (!actor || actor.status !== 'active') throw new AppError(403, 'FORBIDDEN', 'The current workspace user is not active'); return actor; }
  private async ensureDevelopmentActor(context: RequestContext) { if (!this.developmentUserId || context.userId !== this.developmentUserId) return; if (await this.store.getUser(context.workspaceId, context.userId)) return; const timestamp = now(); await this.store.saveUser({ id: context.userId, workspaceId: context.workspaceId, email: `development+${context.workspaceId}@chatpro.local`, displayName: 'Desenvolvimento ChatPro', avatarUrl: null, role: 'owner', status: 'active', createdAt: timestamp, updatedAt: timestamp, lastSeenAt: timestamp }); }
  private async requireUser(workspaceId: string, id: string) { const user = await this.store.getUser(workspaceId, id); if (!user) throw new AppError(404, 'NOT_FOUND', 'Workspace user not found'); return user; }
  private async requireTeam(workspaceId: string, id: string) { const team = await this.store.getTeam(workspaceId, id); if (!team) throw new AppError(404, 'NOT_FOUND', 'Team not found'); return team; }
}

export class SqliteWorkspaceDirectoryStore implements DirectoryStore {
  constructor(private readonly db: SqliteDatabase) {}
  async listUsers(workspaceId: string) { return this.db.prepare('SELECT id, workspaceId, email, displayName, avatarUrl, role, status, createdAt, updatedAt, lastSeenAt FROM workspace_users WHERE workspaceId = ? ORDER BY displayName').all(workspaceId) as WorkspaceUser[]; }
  async getUser(workspaceId: string, id: string) { return this.db.prepare('SELECT id, workspaceId, email, displayName, avatarUrl, role, status, createdAt, updatedAt, lastSeenAt FROM workspace_users WHERE workspaceId = ? AND id = ?').get(workspaceId, id) as WorkspaceUser | undefined; }
  async saveUser(user: WorkspaceUser) { this.db.prepare('INSERT INTO workspace_users (id, workspaceId, email, displayName, avatarUrl, role, status, createdAt, updatedAt, lastSeenAt) VALUES (@id,@workspaceId,@email,@displayName,@avatarUrl,@role,@status,@createdAt,@updatedAt,@lastSeenAt) ON CONFLICT(id) DO UPDATE SET displayName=excluded.displayName, avatarUrl=excluded.avatarUrl, role=excluded.role, status=excluded.status, updatedAt=excluded.updatedAt, lastSeenAt=excluded.lastSeenAt').run(user); return (await this.getUser(user.workspaceId, user.id))!; }
  async listTeams(workspaceId: string) { return this.db.prepare('SELECT t.id,t.workspaceId,t.name,t.description,t.color,t.isActive,t.createdAt,t.updatedAt,count(m.userId) memberCount FROM teams t LEFT JOIN team_members m ON m.teamId=t.id WHERE t.workspaceId=? GROUP BY t.id ORDER BY t.name').all(workspaceId).map(row => ({ ...(row as Omit<Team, 'isActive'> & { isActive: number }), isActive: Boolean((row as { isActive: number }).isActive) })) as Team[]; }
  async getTeam(workspaceId: string, id: string) { return (await this.listTeams(workspaceId)).find(team => team.id === id); }
  async saveTeam(team: Omit<Team, 'memberCount'>) { this.db.prepare('INSERT INTO teams (id,workspaceId,name,description,color,isActive,createdAt,updatedAt) VALUES (@id,@workspaceId,@name,@description,@color,@isActive,@createdAt,@updatedAt) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,color=excluded.color,isActive=excluded.isActive,updatedAt=excluded.updatedAt').run({ ...team, isActive: team.isActive ? 1 : 0 }); return (await this.getTeam(team.workspaceId, team.id))!; }
  async addMember(workspaceId: string, member: TeamMember) { const team = await this.getTeam(workspaceId, member.teamId); const user = await this.getUser(workspaceId, member.userId); if (!team || !user) throw new AppError(404, 'NOT_FOUND', 'Team or user not found in workspace'); this.db.prepare('INSERT INTO team_members (teamId,userId,membershipRole,createdAt) VALUES (@teamId,@userId,@membershipRole,@createdAt) ON CONFLICT(teamId,userId) DO UPDATE SET membershipRole=excluded.membershipRole').run(member); return member; }
  async removeMember(workspaceId: string, teamId: string, userId: string) { const result = this.db.prepare('DELETE FROM team_members WHERE teamId=? AND userId=? AND EXISTS (SELECT 1 FROM teams WHERE id=? AND workspaceId=?)').run(teamId, userId, teamId, workspaceId); return result.changes > 0; }
  async members(workspaceId: string, teamId: string) { return this.db.prepare('SELECT m.teamId,m.userId,m.membershipRole,m.createdAt FROM team_members m JOIN teams t ON t.id=m.teamId WHERE t.workspaceId=? AND m.teamId=?').all(workspaceId, teamId) as TeamMember[]; }
}

export class SupabaseWorkspaceDirectoryStore implements DirectoryStore {
  constructor(private readonly client: SupabaseClient) {}
  async listUsers(workspaceId: string) { const { data, error } = await this.client.from('workspace_users').select('*').eq('workspace_id', workspaceId).order('display_name'); if (error) throw error; return (data ?? []).map(userFromRow); }
  async getUser(workspaceId: string, id: string) { const { data, error } = await this.client.from('workspace_users').select('*').eq('workspace_id', workspaceId).eq('id', id).maybeSingle(); if (error) throw error; return data ? userFromRow(data) : undefined; }
  async saveUser(user: WorkspaceUser) { const { error } = await this.client.from('workspace_users').upsert(userToRow(user)); if (error) throw error; return (await this.getUser(user.workspaceId, user.id))!; }
  async listTeams(workspaceId: string) { const { data, error } = await this.client.from('teams').select('*, team_members(count)').eq('workspace_id', workspaceId).order('name'); if (error) throw error; return (data ?? []).map(row => teamFromRow(row)); }
  async getTeam(workspaceId: string, id: string) { const { data, error } = await this.client.from('teams').select('*, team_members(count)').eq('workspace_id', workspaceId).eq('id', id).maybeSingle(); if (error) throw error; return data ? teamFromRow(data) : undefined; }
  async saveTeam(team: Omit<Team, 'memberCount'>) { const { error } = await this.client.from('teams').upsert(teamToRow(team)); if (error) throw error; return (await this.getTeam(team.workspaceId, team.id))!; }
  async addMember(workspaceId: string, member: TeamMember) { if (!(await this.getTeam(workspaceId, member.teamId)) || !(await this.getUser(workspaceId, member.userId))) throw new AppError(404, 'NOT_FOUND', 'Team or user not found in workspace'); const { error } = await this.client.from('team_members').upsert({ team_id: member.teamId, user_id: member.userId, membership_role: member.membershipRole, created_at: member.createdAt }); if (error) throw error; return member; }
  async removeMember(workspaceId: string, teamId: string, userId: string) { if (!(await this.getTeam(workspaceId, teamId))) return false; const { data, error } = await this.client.from('team_members').delete().eq('team_id', teamId).eq('user_id', userId).select('team_id'); if (error) throw error; return Boolean(data?.length); }
  async members(workspaceId: string, teamId: string) { if (!(await this.getTeam(workspaceId, teamId))) return []; const { data, error } = await this.client.from('team_members').select('*').eq('team_id', teamId); if (error) throw error; return (data ?? []).map(row => ({ teamId: row.team_id, userId: row.user_id, membershipRole: row.membership_role, createdAt: row.created_at })); }
}
const userFromRow = (row: any): WorkspaceUser => ({ id: row.id, workspaceId: row.workspace_id, email: row.email, displayName: row.display_name, avatarUrl: row.avatar_url, role: row.role, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at, lastSeenAt: row.last_seen_at });
const userToRow = (user: WorkspaceUser) => ({ id: user.id, workspace_id: user.workspaceId, email: user.email, display_name: user.displayName, avatar_url: user.avatarUrl, role: user.role, status: user.status, created_at: user.createdAt, updated_at: user.updatedAt, last_seen_at: user.lastSeenAt });
const teamFromRow = (row: any): Team => ({ id: row.id, workspaceId: row.workspace_id, name: row.name, description: row.description, color: row.color, isActive: row.is_active, memberCount: row.team_members?.[0]?.count ?? 0, createdAt: row.created_at, updatedAt: row.updated_at });
const teamToRow = (team: Omit<Team, 'memberCount'>) => ({ id: team.id, workspace_id: team.workspaceId, name: team.name, description: team.description, color: team.color, is_active: team.isActive, created_at: team.createdAt, updated_at: team.updatedAt });
