import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import type { SqliteDatabase } from './database.js';
import { AppError } from '../errors.js';
import type { DomainRepository } from './domain.repository.js';

const id = z.string().uuid(); const page = z.coerce.number().int().positive().default(1); const pageSize = z.coerce.number().int().positive().max(100).default(25);
const contactInput = z.object({ displayName: z.string().trim().min(1).max(160), phoneNumber: z.string().min(1), email: z.string().email().nullable().optional(), company: z.string().trim().max(160).nullable().optional(), tagIds: z.array(id).max(100).optional() });
const tagInput = z.object({ name: z.string().trim().min(1).max(80), color: z.string().regex(/^#[0-9a-fA-F]{6}$/).nullable().optional() });
const templateInput = z.object({ name: z.string().trim().min(1).max(120), content: z.string().min(1).max(10000) });
const leadInput = z.object({ stageId: id, contactId: id.nullable().optional(), title: z.string().trim().min(1).max(160) });
const campaignInput = z.object({ name: z.string().trim().min(1).max(160), templateId: id.nullable().optional(), scheduledAt: z.string().datetime().nullable().optional(), contactIds: z.array(id).max(10000).optional(), sessionId: z.string().trim().min(1).max(128).optional() });
const now = () => new Date().toISOString(); const uuid = () => randomUUID();
const fail = (status: number, code: 'NOT_FOUND'|'CONFLICT'|'VALIDATION_ERROR', message: string, details: Record<string, unknown> = {}) => { throw new AppError(status, code, message, details); };
const phone = (value: string) => { const value2 = value.replace(/\D/g, ''); if (value2.length < 8 || value2.length > 15) fail(400, 'VALIDATION_ERROR', 'Phone number must contain 8 to 15 digits'); return value2; };
const variables = (content: string) => [...new Set([...content.matchAll(/{{\s*([A-Za-z_][A-Za-z0-9_]*)\s*}}/g)].map(v => v[1]))];
/** SQLite adapter. SQL is deliberately confined to this provider implementation. */
class LegacySqliteDomainRepository {
  constructor(private readonly db: SqliteDatabase) {}
  private one(ws: string, table: string, key: string) { const row = this.db.prepare(`SELECT * FROM ${table} WHERE workspaceId=? AND id=?`).get(ws, key); if (!row) fail(404, 'NOT_FOUND', `${table.slice(0,-1)} not found`); return row as any; }
  private transaction<T>(work: () => T): T { return this.db.transaction(work)(); }
  private paginate(ws: string, sql: string, params: unknown[], p: unknown, s: unknown) { const pg = page.parse(p), size = pageSize.parse(s); const total = (this.db.prepare(`SELECT count(*) count FROM (${sql})`).get(...params) as any).count; return { items: this.db.prepare(`${sql} LIMIT ? OFFSET ?`).all(...params, size, (pg - 1) * size), page: pg, pageSize: size, total }; }
  contacts(ws: string, q: any) { const search = z.string().trim().max(120).optional().parse(q.search); const tagId = id.optional().parse(q.tagId); const optOut = z.enum(['true','false']).optional().parse(q.optOut); let sql = 'SELECT c.* FROM contacts c'; const where = ['c.workspaceId=?']; const args: unknown[] = [ws]; if (tagId) { sql += ' JOIN contact_tags ct ON ct.workspaceId=c.workspaceId AND ct.contactId=c.id'; where.push('ct.tagId=?'); args.push(tagId); } if (search) { where.push('(c.displayName LIKE ? OR c.phoneNumber LIKE ? OR c.email LIKE ?)'); args.push(`%${search}%`,`%${search}%`,`%${search}%`); } if (optOut) where.push(optOut === 'true' ? 'EXISTS (SELECT 1 FROM opt_out_history o WHERE o.workspaceId=c.workspaceId AND o.contactId=c.id)' : 'NOT EXISTS (SELECT 1 FROM opt_out_history o WHERE o.workspaceId=c.workspaceId AND o.contactId=c.id)'); return this.paginate(ws, `${sql} WHERE ${where.join(' AND ')} ORDER BY c.createdAt DESC`, args, q.page, q.pageSize); }
  contact(ws:string,key:string){return this.one(ws,'contacts',key)}
  createContact(ws: string, body: unknown) { const input = contactInput.parse(body), number = phone(input.phoneNumber); return this.transaction(() => { for (const tagId of input.tagIds ?? []) this.one(ws,'tags',tagId); const stamp=now(), contact={ id:uuid(), workspaceId:ws, displayName:input.displayName, phoneNumber:number, email:input.email??null, company:input.company??null, createdAt:stamp, updatedAt:stamp }; try { this.db.prepare('INSERT INTO contacts VALUES (@id,@workspaceId,@displayName,@phoneNumber,@email,@company,@createdAt,@updatedAt)').run(contact); } catch { fail(409,'CONFLICT','Phone number already exists in this workspace'); } for (const tagId of input.tagIds ?? []) this.db.prepare('INSERT INTO contact_tags VALUES (?,?,?,?)').run(ws,contact.id,tagId,stamp); return this.one(ws,'contacts',contact.id); }); }
  updateContact(ws:string, key:string, body:unknown) { const input=contactInput.partial().refine(v=>Object.keys(v).length>0).parse(body); this.one(ws,'contacts',key); return this.transaction(()=>{ if(input.tagIds) for(const tagId of input.tagIds)this.one(ws,'tags',tagId); const values:any={...input, phoneNumber:input.phoneNumber?phone(input.phoneNumber):undefined, updatedAt:now()}; delete values.tagIds; const sets=Object.keys(values).filter(k=>values[k]!==undefined).map(k=>`${k}=@${k}`).join(','); if(sets) try { this.db.prepare(`UPDATE contacts SET ${sets} WHERE workspaceId=@workspaceId AND id=@id`).run({...values,workspaceId:ws,id:key}); } catch { fail(409,'CONFLICT','Phone number already exists in this workspace'); } if(input.tagIds){this.db.prepare('DELETE FROM contact_tags WHERE workspaceId=? AND contactId=?').run(ws,key); for(const tagId of input.tagIds)this.db.prepare('INSERT INTO contact_tags VALUES (?,?,?,?)').run(ws,key,tagId,now());} return this.one(ws,'contacts',key);}); }
  deleteContact(ws:string,key:string){this.one(ws,'contacts',key); this.db.prepare('DELETE FROM contacts WHERE workspaceId=? AND id=?').run(ws,key);}
  importContacts(ws:string, body:unknown) { const rows=z.object({csv:z.string().min(1).max(5_000_000)}).parse(body).csv.trim().split(/\r?\n/); const [header,...data]=rows.map(r=>r.split(',').map(x=>x.trim())); const name=header.indexOf('displayName'), number=header.indexOf('phoneNumber'), email=header.indexOf('email'), company=header.indexOf('company'); if(name<0||number<0) fail(400,'VALIDATION_ERROR','CSV must contain displayName and phoneNumber headers'); const created=[]; const rejected:any[]=[]; for(let i=0;i<data.length;i++)try{created.push(this.createContact(ws,{displayName:data[i][name],phoneNumber:data[i][number],email:email<0?null:data[i][email]||null,company:company<0?null:data[i][company]||null}));}catch(e:any){rejected.push({line:i+2,message:e.message});} if(rejected.length) fail(400,'VALIDATION_ERROR','CSV contains invalid rows',{rejected}); return {created:created.length}; }
  exportContacts(ws:string){ const rows=this.db.prepare('SELECT displayName,phoneNumber,email,company FROM contacts WHERE workspaceId=? ORDER BY createdAt').all(ws) as any[]; const esc=(v:any)=>`"${String(v??'').replaceAll('"','""')}"`; return ['displayName,phoneNumber,email,company',...rows.map(r=>[r.displayName,r.phoneNumber,r.email,r.company].map(esc).join(','))].join('\n'); }
  tags(ws:string){return this.db.prepare('SELECT t.*, (SELECT count(*) FROM contact_tags ct WHERE ct.workspaceId=t.workspaceId AND ct.tagId=t.id)+(SELECT count(*) FROM lead_tags lt WHERE lt.workspaceId=t.workspaceId AND lt.tagId=t.id) as linkCount FROM tags t WHERE t.workspaceId=? ORDER BY t.name').all(ws);}
  createTag(ws:string,b:unknown){const x=tagInput.parse(b), stamp=now(), rec={id:uuid(),workspaceId:ws,...x,color:x.color??null,createdAt:stamp,updatedAt:stamp};try{this.db.prepare('INSERT INTO tags VALUES (@id,@workspaceId,@name,@color,@createdAt,@updatedAt)').run(rec);}catch{fail(409,'CONFLICT','Tag name already exists');}return rec;}
  updateTag(ws:string,key:string,b:unknown){const x=tagInput.partial().refine(v=>Object.keys(v).length).parse(b);this.one(ws,'tags',key);try{this.db.prepare(`UPDATE tags SET ${Object.keys(x).map(k=>`${k}=@${k}`).join(',')},updatedAt=@updatedAt WHERE workspaceId=@workspaceId AND id=@id`).run({...x,updatedAt:now(),workspaceId:ws,id:key});}catch{fail(409,'CONFLICT','Tag name already exists');}return this.one(ws,'tags',key);}
  deleteTag(ws:string,key:string){const row=this.one(ws,'tags',key);const links=(this.db.prepare('SELECT (SELECT count(*) FROM contact_tags WHERE workspaceId=? AND tagId=?)+(SELECT count(*) FROM lead_tags WHERE workspaceId=? AND tagId=?) n').get(ws,key,ws,key) as any).n;if(links)fail(409,'CONFLICT','Tag cannot be deleted while it has links',{linkCount:links});this.db.prepare('DELETE FROM tags WHERE workspaceId=? AND id=?').run(ws,key);return row;}
  templates(ws:string){return this.db.prepare('SELECT id,workspaceId,name,content,variablesJson variables,active,createdAt,updatedAt FROM templates WHERE workspaceId=? ORDER BY createdAt DESC').all(ws);}
  template(ws:string,key:string){return this.one(ws,'templates',key);}
  saveTemplate(ws:string,key:string|undefined,b:unknown){const x=templateInput.partial().refine(v=>Object.keys(v).length).parse(b);if(!key){const full=templateInput.parse(b),stamp=now(),rec={id:uuid(),workspaceId:ws,...full,variablesJson:JSON.stringify(variables(full.content)),createdAt:stamp,updatedAt:stamp};try{this.db.prepare('INSERT INTO templates (id,workspaceId,name,content,variablesJson,createdAt,updatedAt) VALUES (@id,@workspaceId,@name,@content,@variablesJson,@createdAt,@updatedAt)').run(rec);}catch{fail(409,'CONFLICT','Template name already exists');}return this.one(ws,'templates',rec.id);}const old:any=this.one(ws,'templates',key), content=x.content??old.content;try{this.db.prepare('UPDATE templates SET name=?,content=?,variablesJson=?,updatedAt=? WHERE workspaceId=? AND id=?').run(x.name??old.name,content,JSON.stringify(variables(content)),now(),ws,key);}catch{fail(409,'CONFLICT','Template name already exists');}return this.one(ws,'templates',key);}
  templateActive(ws:string,key:string,active:boolean){this.one(ws,'templates',key);this.db.prepare('UPDATE templates SET active=?,updatedAt=? WHERE workspaceId=? AND id=?').run(active?1:0,now(),ws,key);return this.one(ws,'templates',key);}
  deleteTemplate(ws:string,key:string){this.one(ws,'templates',key);this.db.prepare('DELETE FROM templates WHERE workspaceId=? AND id=?').run(ws,key);}
  preview(ws:string,key:string,b:unknown){const t:any=this.one(ws,'templates',key), data=z.object({data:z.record(z.union([z.string(),z.number(),z.boolean()]))}).parse(b).data;const missing=JSON.parse(t.variablesJson).filter((v:string)=>data[v]===undefined);if(missing.length)fail(400,'VALIDATION_ERROR','Missing template variables',{missing});return {content:t.content.replace(/{{\s*([A-Za-z_][A-Za-z0-9_]*)\s*}}/g,(_:string,v:string)=>String(data[v])),variables:JSON.parse(t.variablesJson)};}
  pipelines(ws:string){return this.db.prepare('SELECT * FROM pipelines WHERE workspaceId=? ORDER BY createdAt').all(ws);}
  savePipeline(ws:string,key:string|undefined,b:unknown){const x=z.object({name:z.string().trim().min(1).max(120)}).partial().refine(v=>Object.keys(v).length).parse(b);if(!key){const stamp=now(),r={id:uuid(),workspaceId:ws,name:z.object({name:z.string().trim().min(1).max(120)}).parse(b).name,createdAt:stamp,updatedAt:stamp};try{this.db.prepare('INSERT INTO pipelines VALUES (@id,@workspaceId,@name,@createdAt,@updatedAt)').run(r);}catch{fail(409,'CONFLICT','Pipeline name already exists');}return r;}this.one(ws,'pipelines',key);this.db.prepare('UPDATE pipelines SET name=?,updatedAt=? WHERE workspaceId=? AND id=?').run(x.name,now(),ws,key);return this.one(ws,'pipelines',key);}
  deletePipeline(ws:string,key:string){this.one(ws,'pipelines',key);const n=(this.db.prepare('SELECT count(*) n FROM leads l JOIN stages s ON s.workspaceId=l.workspaceId AND s.id=l.stageId WHERE s.workspaceId=? AND s.pipelineId=?').get(ws,key)as any).n;if(n)fail(409,'CONFLICT','Pipeline has linked leads');this.db.prepare('DELETE FROM pipelines WHERE workspaceId=? AND id=?').run(ws,key);}
  initPipeline(ws:string,b:unknown){const name=z.object({name:z.string().trim().min(1).max(120).default('Pipeline padrão')}).parse(b??{}).name;return this.transaction(()=>{const existing=(this.db.prepare('SELECT count(*) n FROM pipelines WHERE workspaceId=?').get(ws)as any).n;if(existing)fail(409,'CONFLICT','Workspace already has a pipeline');const p=this.savePipeline(ws,undefined,{name});['Novo','Em atendimento','Aguardando cliente','Proposta enviada','Concluído'].forEach((n,position)=>this.db.prepare('INSERT INTO stages VALUES (?,?,?,?,?,?,?)').run(uuid(),ws,p.id,n,position,now(),now()));return {pipeline:p,stages:this.stages(ws,p.id)};});}
  stages(ws:string,pipelineId:string){this.one(ws,'pipelines',pipelineId);return this.db.prepare('SELECT * FROM stages WHERE workspaceId=? AND pipelineId=? ORDER BY position').all(ws,pipelineId);}
  saveStage(ws:string,key:string|undefined,b:unknown){const x=z.object({pipelineId:id,name:z.string().trim().min(1).max(120),position:z.number().int().nonnegative()}).partial().refine(v=>Object.keys(v).length).parse(b);if(!key){const full=z.object({pipelineId:id,name:z.string().trim().min(1).max(120),position:z.number().int().nonnegative()}).parse(b);this.one(ws,'pipelines',full.pipelineId);const stamp=now(),r={id:uuid(),workspaceId:ws,...full,createdAt:stamp,updatedAt:stamp};try{this.db.prepare('INSERT INTO stages VALUES (@id,@workspaceId,@pipelineId,@name,@position,@createdAt,@updatedAt)').run(r);}catch{fail(409,'CONFLICT','Stage position is already used');}return r;}const old:any=this.one(ws,'stages',key);const r={...old,...x,updatedAt:now()};this.one(ws,'pipelines',r.pipelineId);try{this.db.prepare('UPDATE stages SET pipelineId=?,name=?,position=?,updatedAt=? WHERE workspaceId=? AND id=?').run(r.pipelineId,r.name,r.position,r.updatedAt,ws,key);}catch{fail(409,'CONFLICT','Stage position is already used');}return this.one(ws,'stages',key);}
  reorderStages(ws:string,pipelineId:string,b:unknown){const ids=z.object({stageIds:z.array(id).min(1)}).parse(b).stageIds;const stages:any[]=this.stages(ws,pipelineId)as any[];if(ids.length!==stages.length||new Set(ids).size!==ids.length||ids.some(x=>!stages.some(s=>s.id===x)))fail(400,'VALIDATION_ERROR','stageIds must contain every pipeline stage exactly once');this.transaction(()=>{ids.forEach((stageId,i)=>this.db.prepare('UPDATE stages SET position=?,updatedAt=? WHERE workspaceId=? AND id=?').run(i,now(),ws,stageId));});return this.stages(ws,pipelineId);}
  deleteStage(ws:string,key:string){this.one(ws,'stages',key);if((this.db.prepare('SELECT count(*) n FROM leads WHERE workspaceId=? AND stageId=?').get(ws,key)as any).n)fail(409,'CONFLICT','Stage has linked leads');this.db.prepare('DELETE FROM stages WHERE workspaceId=? AND id=?').run(ws,key);}
  leads(ws:string,q:any){const pipeline=id.optional().parse(q.pipelineId),stage=id.optional().parse(q.stageId),tag=id.optional().parse(q.tagId),search=z.string().trim().max(120).optional().parse(q.search);let sql='SELECT l.* FROM leads l JOIN stages s ON s.workspaceId=l.workspaceId AND s.id=l.stageId';const a:any[]=[ws],w=['l.workspaceId=?'];if(pipeline){w.push('s.pipelineId=?');a.push(pipeline)}if(stage){w.push('l.stageId=?');a.push(stage)}if(tag){sql+=' JOIN lead_tags lt ON lt.workspaceId=l.workspaceId AND lt.leadId=l.id';w.push('lt.tagId=?');a.push(tag)}if(search){w.push('l.title LIKE ?');a.push(`%${search}%`)}return this.paginate(ws,`${sql} WHERE ${w.join(' AND ')} ORDER BY l.updatedAt DESC`,a,q.page,q.pageSize);}
  saveLead(ws:string,key:string|undefined,b:unknown){const x=leadInput.partial().refine(v=>Object.keys(v).length).parse(b);if(!key){const full=leadInput.parse(b);this.one(ws,'stages',full.stageId);if(full.contactId)this.one(ws,'contacts',full.contactId);const stamp=now(),r={id:uuid(),workspaceId:ws,...full,contactId:full.contactId??null,createdAt:stamp,updatedAt:stamp};this.db.prepare('INSERT INTO leads VALUES (@id,@workspaceId,@stageId,@contactId,@title,@createdAt,@updatedAt)').run(r);return r;}const old:any=this.one(ws,'leads',key),r={...old,...x,updatedAt:now()};this.one(ws,'stages',r.stageId);if(r.contactId)this.one(ws,'contacts',r.contactId);this.db.prepare('UPDATE leads SET stageId=?,contactId=?,title=?,updatedAt=? WHERE workspaceId=? AND id=?').run(r.stageId,r.contactId,r.title,r.updatedAt,ws,key);return this.one(ws,'leads',key);}
  deleteLead(ws:string,key:string){this.one(ws,'leads',key);this.db.prepare('DELETE FROM leads WHERE workspaceId=? AND id=?').run(ws,key);}
  activity(ws:string,leadId:string,type:string,details:Record<string,unknown>={}){this.one(ws,'leads',leadId);const stamp=now(),r={id:uuid(),workspaceId:ws,leadId,type,detailsJson:JSON.stringify(details),occurredAt:stamp,createdAt:stamp,updatedAt:stamp};this.db.prepare('INSERT INTO activities VALUES (@id,@workspaceId,@leadId,@type,@detailsJson,@occurredAt,@createdAt,@updatedAt)').run(r);return {...r,details};}
  moveLead(ws:string,key:string,b:unknown){const stageId=z.object({stageId:id}).parse(b).stageId,old:any=this.one(ws,'leads',key);this.one(ws,'stages',stageId);this.transaction(()=>{this.db.prepare('UPDATE leads SET stageId=?,updatedAt=? WHERE workspaceId=? AND id=?').run(stageId,now(),ws,key);this.activity(ws,key,'lead.moved',{fromStageId:old.stageId,toStageId:stageId});});return this.one(ws,'leads',key);}
  leadTag(ws:string,key:string,tagId:string,add:boolean){this.one(ws,'leads',key);this.one(ws,'tags',tagId);if(add)this.db.prepare('INSERT OR IGNORE INTO lead_tags VALUES (?,?,?,?)').run(ws,key,tagId,now());else this.db.prepare('DELETE FROM lead_tags WHERE workspaceId=? AND leadId=? AND tagId=?').run(ws,key,tagId);return {leadId:key,tagId};}
  note(ws:string,key:string,b:unknown){this.one(ws,'leads',key);const body=z.object({body:z.string().trim().min(1).max(10000)}).parse(b).body,stamp=now(),r={id:uuid(),workspaceId:ws,leadId:key,body,createdAt:stamp,updatedAt:stamp};this.transaction(()=>{this.db.prepare('INSERT INTO lead_notes VALUES (@id,@workspaceId,@leadId,@body,@createdAt,@updatedAt)').run(r);this.activity(ws,key,'note.added',{noteId:r.id});});return r;}
  notes(ws:string,key:string){this.one(ws,'leads',key);return this.db.prepare('SELECT * FROM lead_notes WHERE workspaceId=? AND leadId=? ORDER BY createdAt DESC').all(ws,key)} activities(ws:string,key:string){this.one(ws,'leads',key);return this.db.prepare('SELECT id,workspaceId,leadId,type,detailsJson details,occurredAt,createdAt,updatedAt FROM activities WHERE workspaceId=? AND leadId=? ORDER BY occurredAt DESC').all(ws,key)}
  funnel(ws:string){return this.db.prepare('SELECT s.id stageId,s.name,s.position,count(l.id) total FROM stages s LEFT JOIN leads l ON l.workspaceId=s.workspaceId AND l.stageId=s.id WHERE s.workspaceId=? GROUP BY s.id ORDER BY s.position').all(ws)}
  optOut(ws:string,contactId:string,b:unknown){this.one(ws,'contacts',contactId);const x=z.object({reason:z.string().trim().max(500).nullable().optional(),source:z.string().trim().min(1).max(80).default('manual'),occurredAt:z.string().datetime().optional()}).parse(b??{}),stamp=now(),r={id:uuid(),workspaceId:ws,contactId,reason:x.reason??null,source:x.source,occurredAt:x.occurredAt??stamp,createdAt:stamp,updatedAt:stamp};this.db.prepare('INSERT INTO opt_out_history VALUES (@id,@workspaceId,@contactId,@reason,@source,@occurredAt,@createdAt,@updatedAt)').run(r);return r;}
  optOutStatus(ws:string,contactId:string){this.one(ws,'contacts',contactId);const history=this.db.prepare('SELECT * FROM opt_out_history WHERE workspaceId=? AND contactId=? ORDER BY occurredAt DESC').all(ws,contactId);return {contactId,optedOut:(history as any[]).length>0,history};}
  removeOptOut(ws:string,contactId:string){this.one(ws,'contacts',contactId);this.db.prepare('DELETE FROM opt_out_history WHERE workspaceId=? AND contactId=?').run(ws,contactId);return {contactId,optedOut:false};}
  optOutContacts(ws:string,q:any){return this.contacts(ws,{...q,optOut:'true'});}
  campaigns(ws:string,q:any={}){const status=z.enum(['draft','scheduled','ready','blocked','cancelled']).optional().parse(q.status);return this.paginate(ws,`SELECT * FROM campaigns WHERE workspaceId=?${status?' AND status=?':''} ORDER BY createdAt DESC`,status?[ws,status]:[ws],q.page,q.pageSize);}
  campaign(ws:string,key:string){return this.one(ws,'campaigns',key)}
  saveCampaign(ws:string,key:string|undefined,b:unknown){const x=campaignInput.partial().refine(v=>Object.keys(v).length).parse(b);if(!key){const full=campaignInput.parse(b),stamp=now(),r={id:uuid(),workspaceId:ws,name:full.name,templateId:full.templateId??null,status:'draft',scheduledAt:full.scheduledAt??null,createdAt:stamp,updatedAt:stamp};if(r.templateId)this.one(ws,'templates',r.templateId);return this.transaction(()=>{this.db.prepare('INSERT INTO campaigns VALUES (@id,@workspaceId,@name,@templateId,@status,@scheduledAt,@createdAt,@updatedAt)').run(r);for(const contactId of full.contactIds??[]){this.one(ws,'contacts',contactId);this.db.prepare('INSERT INTO campaign_recipients VALUES (?,?,?,?)').run(ws,r.id,contactId,stamp)}return r;});}const old:any=this.one(ws,'campaigns',key);if(old.status==='cancelled')fail(409,'CONFLICT','Cancelled campaign cannot be edited');if(x.templateId)this.one(ws,'templates',x.templateId);this.db.prepare('UPDATE campaigns SET name=?,templateId=?,scheduledAt=?,updatedAt=? WHERE workspaceId=? AND id=?').run(x.name??old.name,x.templateId===undefined?old.templateId:x.templateId,x.scheduledAt===undefined?old.scheduledAt:x.scheduledAt,now(),ws,key);if(x.contactIds){const contactIds=x.contactIds;this.transaction(()=>{this.db.prepare('DELETE FROM campaign_recipients WHERE workspaceId=? AND campaignId=?').run(ws,key);for(const contactId of contactIds){this.one(ws,'contacts',contactId);this.db.prepare('INSERT INTO campaign_recipients VALUES (?,?,?,?)').run(ws,key,contactId,now());}});}return this.one(ws,'campaigns',key);}
  deleteCampaign(ws:string,key:string){this.one(ws,'campaigns',key);this.db.prepare('DELETE FROM campaigns WHERE workspaceId=? AND id=?').run(ws,key)}
  validateCampaign(ws:string,key:string){const c:any=this.one(ws,'campaigns',key);const problems:string[]=[];if(!c.templateId)problems.push('templateId is required');else {const t:any=this.one(ws,'templates',c.templateId);if(!t.active)problems.push('template is inactive');if(!t.content.trim())problems.push('template content is empty');}const recipients=(this.db.prepare('SELECT count(*) n FROM campaign_recipients WHERE workspaceId=? AND campaignId=?').get(ws,key)as any).n;if(!recipients)problems.push('at least one recipient is required');return {valid:!problems.length,problems,recipients};}
  prepareCampaign(ws:string,key:string){const valid=this.validateCampaign(ws,key);const excluded=(this.db.prepare('SELECT count(*) n FROM campaign_recipients r WHERE r.workspaceId=? AND r.campaignId=? AND EXISTS (SELECT 1 FROM opt_out_history o WHERE o.workspaceId=r.workspaceId AND o.contactId=r.contactId)').get(ws,key)as any).n;const eligible=(this.db.prepare('SELECT count(*) n FROM campaign_recipients r WHERE r.workspaceId=? AND r.campaignId=? AND NOT EXISTS (SELECT 1 FROM opt_out_history o WHERE o.workspaceId=r.workspaceId AND o.contactId=r.contactId)').get(ws,key)as any).n;const status=valid.valid&&eligible>0?'ready':'blocked';this.db.prepare('UPDATE campaigns SET status=?,updatedAt=? WHERE workspaceId=? AND id=?').run(status,now(),ws,key);return {campaign:this.one(ws,'campaigns',key),eligibleRecipients:eligible,excludedOptOut:excluded,problems:[...valid.problems,...(eligible?'':['no eligible recipients'])]};}
  scheduleCampaign(ws:string,key:string,b:unknown){const scheduledAt=z.object({scheduledAt:z.string().datetime()}).parse(b).scheduledAt;this.one(ws,'campaigns',key);const prepared=this.prepareCampaign(ws,key);if((prepared.campaign as any).status==='blocked')return prepared;this.db.prepare('UPDATE campaigns SET status=?,scheduledAt=?,updatedAt=? WHERE workspaceId=? AND id=?').run('scheduled',scheduledAt,now(),ws,key);return this.one(ws,'campaigns',key)}
  cancelCampaign(ws:string,key:string){this.one(ws,'campaigns',key);this.db.prepare('UPDATE campaigns SET status=?,updatedAt=? WHERE workspaceId=? AND id=?').run('cancelled',now(),ws,key);return this.one(ws,'campaigns',key)}
  settings(ws:string){const row:any=this.db.prepare('SELECT * FROM workspace_settings WHERE workspaceId=?').get(ws);return row?{...row,settings:JSON.parse(row.settingsJson)}:{workspaceId:ws,settings:{}}}
  saveSettings(ws:string,b:unknown){const settings=z.object({workspaceName:z.string().trim().min(1).max(160).optional(),locale:z.string().trim().min(2).max(35).optional(),timezone:z.string().trim().min(1).max(80).optional(),defaultCountryCode:z.string().regex(/^\d{1,3}$/).optional(),operational:z.record(z.union([z.string(),z.number(),z.boolean(),z.null()])).optional()}).strict().parse(b);const current:any=this.settings(ws),merged={...(current.settings??{}),...settings},stamp=now();if(current.id)this.db.prepare('UPDATE workspace_settings SET settingsJson=?,updatedAt=? WHERE workspaceId=?').run(JSON.stringify(merged),stamp,ws);else this.db.prepare('INSERT INTO workspace_settings VALUES (?,?,?,?,?)').run(uuid(),ws,JSON.stringify(merged),stamp,stamp);return this.settings(ws)}
  dashboard(ws:string,sessions:any[]=[]){const scalar=(sql:string)=>(this.db.prepare(sql).get(ws)as any).n;return {contacts:scalar('SELECT count(*) n FROM contacts WHERE workspaceId=?'),optOutContacts:scalar('SELECT count(DISTINCT contactId) n FROM opt_out_history WHERE workspaceId=?'),tags:scalar('SELECT count(*) n FROM tags WHERE workspaceId=?'),templates:scalar('SELECT count(*) n FROM templates WHERE workspaceId=?'),leads:scalar('SELECT count(*) n FROM leads WHERE workspaceId=?'),leadsByStage:this.funnel(ws),recentActivities:this.db.prepare('SELECT id,leadId,type,detailsJson details,occurredAt FROM activities WHERE workspaceId=? ORDER BY occurredAt DESC LIMIT 10').all(ws),campaignsByStatus:this.db.prepare('SELECT status,count(*) total FROM campaigns WHERE workspaceId=? GROUP BY status').all(ws),sessionsByStatus:Object.entries((sessions as any[]).reduce((a,s)=>{a[s.status]=(a[s.status]??0)+1;return a;},{} as Record<string,number>)).map(([status,total])=>({status,total}))};}
}

/** Adapts the synchronous better-sqlite3 implementation without leaking it
 * across the domain boundary. Its internal transaction callbacks remain local. */
export function createSqliteDomainRepository(db: SqliteDatabase): DomainRepository {
  const legacy = new LegacySqliteDomainRepository(db) as unknown as Record<string, (...args: unknown[]) => unknown>;
  return new Proxy({}, {
    get: (_target, property) => {
      const method = legacy[String(property)];
      if (!method) return undefined;
      return async (...args: unknown[]) => method.apply(legacy, args);
    },
  }) as DomainRepository;
}
