import { randomUUID } from 'node:crypto';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { DomainRepository } from './domain.repository.js';

type Row = Record<string, unknown>;
type RpcError = { message: string; code?: string } | null;
const now = () => new Date().toISOString();
const snake = (value: Row) => Object.fromEntries(Object.entries(value).map(([key, item]) => [key.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`), item]));
const camel = (value: unknown): unknown => {
  if (Array.isArray(value)) return value.map(camel);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(Object.entries(value as Row).map(([key, item]) => [key.replace(/_([a-z])/g, (_, letter: string) => letter.toUpperCase()), camel(item)]));
};
const error = (value: RpcError) => { if (value) throw new Error(`Supabase persistence error${value.code ? ` (${value.code})` : ''}: ${value.message}`); };
const normalizePhone = (value: string) => { const normalized = value.replace(/\D/g, ''); if (normalized.length < 8 || normalized.length > 15) throw new Error('Phone number must contain 8 to 15 digits'); return normalized; };

/** Supabase implementation of the domain boundary. Compound mutations go through
 * versioned RPCs; reads and single-table changes keep using PostgREST tables. */
export class SupabaseDomainRepository implements DomainRepository {
  constructor(private readonly client: SupabaseClient) {}
  private async rpc(name: string, args: Row): Promise<unknown> { const { data, error: rpcError } = await this.client.rpc(name, args); error(rpcError); return camel(data); }
  private async rows(table: string, workspaceId: string): Promise<unknown[]> { const { data, error: queryError } = await this.client.from(table).select().eq('workspace_id', workspaceId).order('created_at'); error(queryError); return (data ?? []).map(camel); }
  private async one(table: string, workspaceId: string, id: string): Promise<unknown> { const { data, error: queryError } = await this.client.from(table).select().eq('workspace_id', workspaceId).eq('id', id).maybeSingle(); error(queryError); if (!data) throw new Error(`${table} not found in workspace`); return camel(data); }
  private async save(table: string, workspaceId: string, id: string | undefined, body: unknown): Promise<unknown> { const payload = snake(body as Row); if (id) { const { data, error: queryError } = await this.client.from(table).update({ ...payload, updated_at: now() }).eq('workspace_id', workspaceId).eq('id', id).select().maybeSingle(); error(queryError); if (!data) throw new Error(`${table} not found in workspace`); return camel(data); } const { data, error: queryError } = await this.client.from(table).insert({ id: randomUUID(), workspace_id: workspaceId, ...payload, created_at: now(), updated_at: now() }).select().single(); error(queryError); return camel(data); }
  private async remove(table: string, workspaceId: string, id: string): Promise<void> { const { error: queryError } = await this.client.from(table).delete().eq('workspace_id', workspaceId).eq('id', id); error(queryError); }
  private page(items: unknown[], query: Record<string, unknown>) { const page = Number(query.page ?? 1), pageSize = Math.min(Number(query.pageSize ?? 25), 100), start = (page - 1) * pageSize; return { items: items.slice(start, start + pageSize), page, pageSize, total: items.length }; }

  async contacts(w: string, q: Record<string, unknown>) { return this.page(await this.rows('contacts', w), q); }
  contact(w: string, id: string) { return this.one('contacts', w, id); }
  createContact(w: string, body: unknown) { const input = body as Row; return this.rpc('chatpro_create_contact', { p_workspace_id: w, p_contact: { ...input, phoneNumber: normalizePhone(String(input.phoneNumber)) }, p_tag_ids: input.tagIds ?? [] }); }
  updateContact(w: string, id: string, body: unknown) { const input = body as Row; const payload = { ...input, ...(typeof input.phoneNumber === 'string' ? { phoneNumber: normalizePhone(input.phoneNumber) } : {}) }; return this.rpc('chatpro_update_contact', { p_workspace_id: w, p_contact_id: id, p_contact: payload, p_tag_ids: Array.isArray(input.tagIds) ? input.tagIds : null }); }
  deleteContact(w: string, id: string) { return this.remove('contacts', w, id); }
  async importContacts(w: string, body: unknown) { const csv = String((body as Row).csv ?? ''); const lines = csv.trim().split(/\r?\n/); const [header, ...rows] = lines.map((line) => line.split(',').map((item) => item.trim())); const name = header.indexOf('displayName'), phone = header.indexOf('phoneNumber'); if (name < 0 || phone < 0) throw new Error('CSV must contain displayName and phoneNumber headers'); await Promise.all(rows.map((row) => this.createContact(w, { displayName: row[name], phoneNumber: row[phone] }))); return { created: rows.length }; }
  async exportContacts(w: string) { const rows = await this.rows('contacts', w) as Row[]; return ['displayName,phoneNumber,email,company', ...rows.map((row) => [row.displayName, row.phoneNumber, row.email, row.company].map((item) => `"${String(item ?? '').replaceAll('"', '""')}"`).join(','))].join('\n'); }
  tags(w: string) { return this.rows('tags', w); } createTag(w: string, b: unknown) { return this.save('tags', w, undefined, b); } updateTag(w: string, id: string, b: unknown) { return this.save('tags', w, id, b); } deleteTag(w: string, id: string) { return this.rpc('chatpro_delete_tag', { p_workspace_id: w, p_tag_id: id }); }
  templates(w: string) { return this.rows('templates', w); } template(w: string, id: string) { return this.one('templates', w, id); } saveTemplate(w: string, id: string | undefined, b: unknown) { return this.save('templates', w, id, b); } templateActive(w: string, id: string, active: boolean) { return this.save('templates', w, id, { active }); } deleteTemplate(w: string, id: string) { return this.remove('templates', w, id); }
  async preview(w: string, id: string, body: unknown) { const template = await this.template(w, id) as Row; const data = (body as Row).data as Row; const variables = (template.variablesJson ?? template.variables ?? []) as string[]; const missing = variables.filter((name) => data[name] === undefined); if (missing.length) throw new Error(`Missing template variables: ${missing.join(', ')}`); return { content: String(template.content).replace(/{{\s*([A-Za-z_][A-Za-z0-9_]*)\s*}}/g, (_, name: string) => String(data[name])), variables }; }
  pipelines(w: string) { return this.rows('pipelines', w); } savePipeline(w: string, id: string | undefined, b: unknown) { return this.save('pipelines', w, id, b); } async deletePipeline(w: string, id: string): Promise<void> { await this.rpc('chatpro_delete_pipeline', { p_workspace_id: w, p_pipeline_id: id }); } initPipeline(w: string, b: unknown) { return this.rpc('chatpro_initialize_pipeline', { p_workspace_id: w, p_name: (b as Row).name ?? 'Pipeline padrão' }); }
  async stages(w: string, pipelineId: string) { const { data, error: queryError } = await this.client.from('stages').select().eq('workspace_id', w).eq('pipeline_id', pipelineId).order('position'); error(queryError); return (data ?? []).map(camel); } saveStage(w: string, id: string | undefined, b: unknown) { return this.save('stages', w, id, b); } async reorderStages(w: string, pipelineId: string, b: unknown) { const ids = (b as Row).stageIds as string[]; await Promise.all(ids.map((id, position) => this.save('stages', w, id, { pipelineId, position }))); return this.stages(w, pipelineId); } async deleteStage(w: string, id: string): Promise<void> { await this.rpc('chatpro_delete_stage', { p_workspace_id: w, p_stage_id: id }); }
  async leads(w: string, q: Record<string, unknown>) { return this.page(await this.rows('leads', w), q); } saveLead(w: string, id: string | undefined, b: unknown) { return this.save('leads', w, id, b); } deleteLead(w: string, id: string) { return this.remove('leads', w, id); } moveLead(w: string, id: string, b: unknown) { return this.rpc('chatpro_move_lead', { p_workspace_id: w, p_lead_id: id, p_stage_id: (b as Row).stageId }); } leadTag(w: string, id: string, tagId: string, add: boolean) { return this.rpc('chatpro_set_lead_tag', { p_workspace_id: w, p_lead_id: id, p_tag_id: tagId, p_add: add }); } note(w: string, id: string, b: unknown) { return this.rpc('chatpro_add_note', { p_workspace_id: w, p_lead_id: id, p_body: (b as Row).body }); } async notes(w: string, id: string) { const { data, error: queryError } = await this.client.from('lead_notes').select().eq('workspace_id', w).eq('lead_id', id).order('created_at', { ascending: false }); error(queryError); return (data ?? []).map(camel); } async activities(w: string, id: string) { const { data, error: queryError } = await this.client.from('activities').select().eq('workspace_id', w).eq('lead_id', id).order('occurred_at', { ascending: false }); error(queryError); return (data ?? []).map(camel); } async funnel(w: string) { const stages = await this.rows('stages', w) as Row[], leads = await this.rows('leads', w) as Row[]; return stages.map((stage) => ({ stageId: stage.id, name: stage.name, position: stage.position, total: leads.filter((lead) => lead.stageId === stage.id).length })); }
  optOut(w: string, id: string, b: unknown) { return this.rpc('chatpro_record_opt_out', { p_workspace_id: w, p_contact_id: id, p_payload: b }); } async optOutStatus(w: string, id: string) { const { data, error: queryError } = await this.client.from('opt_out_history').select().eq('workspace_id', w).eq('contact_id', id).order('occurred_at', { ascending: false }); error(queryError); const history = (data ?? []).map(camel); return { contactId: id, optedOut: history.length > 0, history }; } removeOptOut(w: string, id: string) { return this.rpc('chatpro_remove_opt_out', { p_workspace_id: w, p_contact_id: id }); } optOutContacts(w: string, q: Record<string, unknown>) { return this.contacts(w, q); }
  async campaigns(w: string, q: Record<string, unknown>) { return this.page(await this.rows('campaigns', w), q); } campaign(w: string, id: string) { return this.one('campaigns', w, id); } saveCampaign(w: string, id: string | undefined, b: unknown) { const input = b as Row; return this.rpc('chatpro_save_campaign', { p_workspace_id: w, p_campaign_id: id ?? null, p_payload: input, p_contact_ids: Array.isArray(input.contactIds) ? input.contactIds : null }); } deleteCampaign(w: string, id: string) { return this.remove('campaigns', w, id); } async validateCampaign(w: string, id: string) { const campaign = await this.campaign(w, id) as Row; const problems: string[] = []; if (!campaign.templateId) problems.push('templateId is required'); return { valid: problems.length === 0, problems, recipients: 0 }; } prepareCampaign(w: string, id: string) { return this.rpc('chatpro_prepare_campaign', { p_workspace_id: w, p_campaign_id: id }); } async scheduleCampaign(w: string, id: string, b: unknown) { const prepared = await this.prepareCampaign(w, id) as Row; if ((prepared.campaign as Row).status === 'blocked') return prepared; return this.save('campaigns', w, id, { status: 'scheduled', scheduledAt: (b as Row).scheduledAt }); } cancelCampaign(w: string, id: string) { return this.save('campaigns', w, id, { status: 'cancelled' }); }
  async settings(w: string) { const { data, error: queryError } = await this.client.from('workspace_settings').select().eq('workspace_id', w).maybeSingle(); error(queryError); return data ? camel(data) : { workspaceId: w, settings: {} }; } saveSettings(w: string, b: unknown) { return this.rpc('chatpro_save_settings', { p_workspace_id: w, p_settings: b }); } async dashboard(w: string, sessions: unknown[]) { const [contacts, tags, templates, leads, campaigns] = await Promise.all(['contacts', 'tags', 'templates', 'leads', 'campaigns'].map((table) => this.rows(table, w))); return { contacts: contacts.length, optOutContacts: (await this.optOutContacts(w, {} ) as { total: number }).total, tags: tags.length, templates: templates.length, leads: leads.length, leadsByStage: await this.funnel(w), recentActivities: [], campaignsByStatus: campaigns, sessionsByStatus: sessions }; }
}

export const createSupabaseDomainRepository = (client: SupabaseClient): DomainRepository => new SupabaseDomainRepository(client);
