import { describe, expect, it } from 'vitest';
import { WahaProvider } from '../src/waha-provider.js';
import { WahaClientError, type WahaClientPort } from '../src/waha-client.js';

const context = { workspaceId: 'workspace-a', correlationId: 'correlation-a' };
class FakeWahaClient implements WahaClientPort {
  status = 'STOPPED'; qr = 'temporary-real-qr'; calls: string[] = []; location?: { latitude: number; longitude: number; title?: string }; vcards?: ReadonlyArray<Record<string, unknown>>;
  async health() {} async listSessions(): Promise<Array<{ name: string; status: string }>> { return []; } async createSession(name: string) { this.calls.push('create'); return { name, status: this.status }; } async startSession() { this.calls.push('start'); this.status = 'SCAN_QR_CODE'; } async getSession(name: string) { return { name, status: this.status }; } async getQr() { this.calls.push('qr'); return this.qr; } async stopSession() { this.calls.push('stop'); this.status = 'STOPPED'; } async logoutSession() { this.calls.push('logout'); this.status = 'LOGGED_OUT'; } async removeSession() { this.calls.push('remove'); } async sendText() { this.calls.push('sendText'); return { id: 'sent-message-a', pending: false }; } async sendAttachment() { this.calls.push('sendAttachment'); return { id: 'sent-file-a', pending: false }; } async getIdentity(_session: string, whatsappId: string) { this.calls.push('identity'); return { whatsappId, canonicalWhatsappId: whatsappId, phone: '5511999999999', name: 'Contato', pushName: 'Contato', shortName: 'Contato', profilePictureUrl: null }; } async getGroup(_session: string, chatId: string) { this.calls.push('group'); return { chatId, name: 'Grupo', pictureUrl: null, metadata: {}, participants: [{ whatsappId: '5511999999999@c.us', role: 'participant' }] }; } async sendLocation(_session: string, _chatId: string, location: { latitude: number; longitude: number; title?: string }) { this.calls.push('location'); this.location = location; return { id: 'sent-location-a', pending: false }; }
  async sendContactVcard(_session: string, _chatId: string, contacts: ReadonlyArray<Record<string, unknown>>) { this.calls.push('vcard'); this.vcards = contacts; return { id: 'sent-vcard-a', pending: false }; }
  async listChats() { return { items: [], unsupported: [], hasMore: false }; } async listMessages() { return { items: [], unsupported: [], hasMore: false }; }
}
describe('WahaProvider', () => {
  it('maps the asynchronous WAHA lifecycle without leaking its wire responses', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); const created = await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); expect(created).toMatchObject({ status: 'connecting', name: 'Primary' }); await provider.execute(context, { type: 'connectSession', sessionId: 'session-a' }); expect(await provider.execute(context, { type: 'getSession', sessionId: 'session-a' })).toMatchObject({ status: 'waiting_qr' }); const qr = await provider.execute(context, { type: 'getQr', sessionId: 'session-a' }); expect(qr).toMatchObject({ sessionId: 'session-a', qr: 'temporary-real-qr' }); expect(JSON.stringify(qr)).not.toContain('SCAN_QR_CODE'); await provider.execute(context, { type: 'disconnectSession', sessionId: 'session-a' }); await provider.execute(context, { type: 'logoutSession', sessionId: 'session-a' }); await provider.execute(context, { type: 'removeSession', sessionId: 'session-a' }); expect(client.calls).toEqual(['create', 'start', 'qr', 'stop', 'logout', 'remove']); });
  it('keeps a durable session record when WAHA is unavailable', async () => { const client = new FakeWahaClient(); client.createSession = async () => { throw new WahaClientError('unavailable'); }; client.getSession = async () => { throw new WahaClientError('unavailable'); }; const provider = new WahaProvider(client, 60_000); await expect(provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } })).resolves.toMatchObject({ id: 'session-a', status: 'connecting' }); await new Promise(resolve => setImmediate(resolve)); await expect(provider.execute(context, { type: 'getSession', sessionId: 'session-a' })).rejects.toMatchObject({ response: { error: { code: 'SERVICE_UNAVAILABLE' } } }); });
  it('reconciles one missing workspace link to the only compatible WAHA session without rewriting historical aliases', async () => { const client = new FakeWahaClient(); client.listSessions = async () => [{ name: 'chatpro-real', status: 'SCAN_QR_CODE' }, { name: 'chatpro-orphan', status: 'STOPPED' }]; client.getSession = async name => ({ name, status: name === 'chatpro-real' ? 'WORKING' : 'STOPPED' }); let saved: unknown; const provider = new WahaProvider(client, 60_000, { load: async () => [{ workspaceId: 'workspace-a', sessionId: 'session-a', name: 'Primary', wahaName: 'chatpro-missing' }], save: async entries => { saved = entries; } }); const listed = await provider.execute(context, { type: 'listSessions' }) as Array<{ id: string; wahaName?: string; managed?: boolean }>; expect(listed).toEqual(expect.arrayContaining([expect.objectContaining({ id: 'session-a', wahaName: 'chatpro-real', managed: true }), expect.objectContaining({ id: 'chatpro-orphan', managed: false })])); await provider.execute(context, { type: 'sendMessage', wahaSession: 'chatpro-missing', chatId: '5511999999999@c.us', text: 'Olá' }); expect(client.calls).toContain('sendText'); expect(saved).toMatchObject([{ wahaName: 'chatpro-real', aliases: ['chatpro-missing'] }]); });
  it('does not request a QR after WAHA has authenticated the session', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); client.status = 'WORKING'; await expect(provider.execute(context, { type: 'getQr', sessionId: 'session-a' })).rejects.toMatchObject({ response: { error: { code: 'CONFLICT', details: { status: 'connected' } } } }); expect(client.calls).not.toContain('qr'); });
  it('reconciles the status when an in-flight WAHA QR request times out', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); client.status = 'SCAN_QR_CODE'; client.getQr = async () => { client.calls.push('qr'); client.status = 'WORKING'; throw new WahaClientError('timeout'); }; await expect(provider.execute(context, { type: 'getQr', sessionId: 'session-a' })).rejects.toMatchObject({ response: { error: { code: 'CONFLICT', details: { status: 'connected' } } } }); expect(client.calls).toContain('qr'); expect((await provider.execute(context, { type: 'getSession', sessionId: 'session-a' }) as { status: string }).status).toBe('connected'); });
  it('reconciles the status just the same when the command budget, not WAHA, ended the QR request', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); client.status = 'SCAN_QR_CODE'; client.getQr = async () => { client.calls.push('qr'); client.status = 'WORKING'; throw new WahaClientError('deadline'); }; await expect(provider.execute(context, { type: 'getQr', sessionId: 'session-a' })).rejects.toMatchObject({ response: { error: { code: 'CONFLICT', details: { status: 'connected' } } } }); expect((await provider.execute(context, { type: 'getSession', sessionId: 'session-a' }) as { status: string }).status).toBe('connected'); });
  it('reconciles a session that WAHA may have created before the command budget ended the call', async () => { const client = new FakeWahaClient(); client.createSession = async () => { client.calls.push('create'); throw new WahaClientError('deadline'); }; client.getSession = async name => { client.calls.push('lookup'); return { name, status: 'WORKING' }; }; const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); await new Promise(resolve => setImmediate(resolve)); expect(client.calls).toEqual(['create', 'lookup']); expect((await provider.execute(context, { type: 'getSession', sessionId: 'session-a' }) as { status: string }).status).toBe('connected'); });
  it('routes every content kind through the same session guards and answers a typed gap', async () => {
    const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000);
    await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } });
    const session = 'chatpro-b60c5708e0c4a09d91258bd25a5a81a0c48104a9';
    const location = { kind: 'location' as const, latitude: -7.115, longitude: -34.861 };
    // Not connected yet: the content path must refuse for the same reason text
    // and attachments do, before reaching the provider at all.
    await expect(provider.execute(context, { type: 'sendContent', wahaSession: session, chatId: '1@c.us', content: location })).rejects.toMatchObject({ response: { error: { code: 'CONFLICT' } } });
    client.status = 'WORKING';
    expect(await provider.execute(context, { type: 'sendContent', wahaSession: session, chatId: '1@c.us', content: { ...location, title: 'Escritório' } })).toMatchObject({ id: 'sent-location-a' });
    expect(client.location).toEqual({ latitude: -7.115, longitude: -34.861, title: 'Escritório' });
    expect(client.calls).toContain('location');
    const cards = [{ fullName: 'Ada Lovelace', phoneNumber: '+55 85 92369359', organization: 'ChatPro' }, { fullName: 'Grace Hopper', phoneNumber: '+55 85 90000001' }];
    expect(await provider.execute(context, { type: 'sendContent', wahaSession: session, chatId: '1@c.us', content: { kind: 'vcard', contacts: cards } })).toMatchObject({ id: 'sent-vcard-a' });
    // The list travels whole: WAHA accepts more than one contact per message.
    expect(client.vcards).toEqual(cards);
    for (const content of [{ kind: 'poll' as const, name: 'Q', options: ['A', 'B'], multipleAnswers: false }]) {
      await expect(provider.execute(context, { type: 'sendContent', wahaSession: session, chatId: '1@c.us', content })).rejects.toMatchObject({ response: { error: { code: 'NOT_IMPLEMENTED', details: { kind: content.kind } } } });
    }
    await expect(provider.execute(context, { type: 'sendContent', wahaSession: 'chatpro-unknown', chatId: '1@c.us', content: location })).rejects.toMatchObject({ response: { error: { code: 'NOT_FOUND' } } });
  });
  it('does not stop remote sessions when the worker restarts', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); await provider.execute(context, { type: 'connectSession', sessionId: 'session-a' }); await provider.shutdown(); expect(client.calls).toEqual(['create', 'start']); expect(client.status).toBe('SCAN_QR_CODE'); });
  it('sends text only through a connected workspace WAHA session', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); client.status = 'WORKING'; const sent = await provider.execute(context, { type: 'sendMessage', wahaSession: 'chatpro-b60c5708e0c4a09d91258bd25a5a81a0c48104a9', chatId: '5511999999999@c.us', text: 'Olá' }); expect(sent).toMatchObject({ id: 'sent-message-a' }); expect(client.calls).toContain('sendText'); });
  it('preserves a WAHA invalid-recipient response instead of reporting it as unavailable', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); client.status = 'WORKING'; client.sendText = async () => { throw new WahaClientError('response', 404, 'Chat not found'); }; await expect(provider.execute(context, { type: 'sendMessage', wahaSession: 'chatpro-b60c5708e0c4a09d91258bd25a5a81a0c48104a9', chatId: 'missing@c.us', text: 'Olá' })).rejects.toMatchObject({ response: { error: { code: 'NOT_FOUND', details: { providerStatus: 404, providerMessage: 'Chat not found' } } } }); });
  it('keeps a real WAHA 5xx classified as unavailable', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); client.status = 'WORKING'; client.sendText = async () => { throw new WahaClientError('response', 500, 'Internal error'); }; await expect(provider.execute(context, { type: 'sendMessage', wahaSession: 'chatpro-b60c5708e0c4a09d91258bd25a5a81a0c48104a9', chatId: '5511999999999@c.us', text: 'Olá' })).rejects.toMatchObject({ response: { error: { code: 'SERVICE_UNAVAILABLE', details: { providerStatus: 500 } } } }); });
  it('retrieves group and participant data only through the connected WAHA session', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); client.status = 'WORKING'; const result = await provider.execute(context, { type: 'syncIdentity', wahaSession: 'chatpro-b60c5708e0c4a09d91258bd25a5a81a0c48104a9', chatId: '120363363444637332@g.us', senderWhatsappId: '5511999999999@c.us', refreshIdentity: true, refreshGroup: true }); expect(result).toMatchObject({ identity: { whatsappId: '5511999999999@c.us' }, group: { chatId: '120363363444637332@g.us', participants: [{ whatsappId: '5511999999999@c.us' }] } }); expect(client.calls).toEqual(expect.arrayContaining(['identity', 'group'])); });
});
