import { describe, expect, it } from 'vitest';
import { WahaProvider } from '../src/waha-provider.js';
import { WahaClientError, type WahaClientPort } from '../src/waha-client.js';

const context = { workspaceId: 'workspace-a', correlationId: 'correlation-a' };
class FakeWahaClient implements WahaClientPort {
  status = 'STOPPED'; qr = 'temporary-real-qr'; calls: string[] = [];
  async health() {} async listSessions() { return []; } async createSession(name: string) { this.calls.push('create'); return { name, status: this.status }; } async startSession() { this.calls.push('start'); this.status = 'SCAN_QR_CODE'; } async getSession(name: string) { return { name, status: this.status }; } async getQr() { this.calls.push('qr'); return this.qr; } async stopSession() { this.calls.push('stop'); this.status = 'STOPPED'; } async logoutSession() { this.calls.push('logout'); this.status = 'LOGGED_OUT'; } async removeSession() { this.calls.push('remove'); } async sendText() { this.calls.push('sendText'); return { id: 'sent-message-a' }; } async getIdentity(_session: string, whatsappId: string) { this.calls.push('identity'); return { whatsappId, canonicalWhatsappId: whatsappId, phone: '5511999999999', name: 'Contato', pushName: 'Contato', shortName: 'Contato', profilePictureUrl: null }; } async getGroup(_session: string, chatId: string) { this.calls.push('group'); return { chatId, name: 'Grupo', pictureUrl: null, metadata: {}, participants: [{ whatsappId: '5511999999999@c.us', role: 'participant' }] }; }
}
describe('WahaProvider', () => {
  it('maps the WAHA lifecycle without leaking its wire responses', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); const created = await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); expect(created).toMatchObject({ status: 'disconnected', name: 'Primary' }); await provider.execute(context, { type: 'connectSession', sessionId: 'session-a' }); expect(await provider.execute(context, { type: 'getSession', sessionId: 'session-a' })).toMatchObject({ status: 'waiting_qr' }); const qr = await provider.execute(context, { type: 'getQr', sessionId: 'session-a' }); expect(qr).toMatchObject({ sessionId: 'session-a', qr: 'temporary-real-qr' }); expect(JSON.stringify(qr)).not.toContain('SCAN_QR_CODE'); await provider.execute(context, { type: 'disconnectSession', sessionId: 'session-a' }); await provider.execute(context, { type: 'logoutSession', sessionId: 'session-a' }); await provider.execute(context, { type: 'removeSession', sessionId: 'session-a' }); expect(client.calls).toEqual(['create', 'start', 'qr', 'stop', 'logout', 'remove']); });
  it('normalizes unavailable WAHA and does not disclose credentials', async () => { const client = new FakeWahaClient(); client.createSession = async () => { throw new WahaClientError('unavailable'); }; const provider = new WahaProvider(client, 60_000); await expect(provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } })).rejects.toMatchObject({ response: { error: { code: 'SERVICE_UNAVAILABLE', message: 'WAHA provider is unavailable' } } }); });
  it('does not request a QR after WAHA has authenticated the session', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); client.status = 'WORKING'; await expect(provider.execute(context, { type: 'getQr', sessionId: 'session-a' })).rejects.toMatchObject({ response: { error: { code: 'CONFLICT', details: { status: 'connected' } } } }); expect(client.calls).not.toContain('qr'); });
  it('reconciles the status when an in-flight WAHA QR request times out', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); client.status = 'SCAN_QR_CODE'; client.getQr = async () => { client.calls.push('qr'); client.status = 'WORKING'; throw new WahaClientError('timeout'); }; await expect(provider.execute(context, { type: 'getQr', sessionId: 'session-a' })).rejects.toMatchObject({ response: { error: { code: 'CONFLICT', details: { status: 'connected' } } } }); expect(client.calls).toContain('qr'); expect((await provider.execute(context, { type: 'getSession', sessionId: 'session-a' }) as { status: string }).status).toBe('connected'); });
  it('does not stop remote sessions when the worker restarts', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); await provider.execute(context, { type: 'connectSession', sessionId: 'session-a' }); await provider.shutdown(); expect(client.calls).toEqual(['create', 'start']); expect(client.status).toBe('SCAN_QR_CODE'); });
  it('sends text only through a connected workspace WAHA session', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); client.status = 'WORKING'; const sent = await provider.execute(context, { type: 'sendMessage', wahaSession: 'chatpro-b60c5708e0c4a09d91258bd25a5a81a0c48104a9', chatId: '5511999999999@c.us', text: 'Olá' }); expect(sent).toMatchObject({ id: 'sent-message-a' }); expect(client.calls).toContain('sendText'); });
  it('preserves a WAHA invalid-recipient response instead of reporting it as unavailable', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); client.status = 'WORKING'; client.sendText = async () => { throw new WahaClientError('response', 404, 'Chat not found'); }; await expect(provider.execute(context, { type: 'sendMessage', wahaSession: 'chatpro-b60c5708e0c4a09d91258bd25a5a81a0c48104a9', chatId: 'missing@c.us', text: 'Olá' })).rejects.toMatchObject({ response: { error: { code: 'NOT_FOUND', details: { providerStatus: 404, providerMessage: 'Chat not found' } } } }); });
  it('retrieves group and participant data only through the connected WAHA session', async () => { const client = new FakeWahaClient(); const provider = new WahaProvider(client, 60_000); await provider.execute(context, { type: 'createSession', sessionId: 'session-a', input: { name: 'Primary' } }); client.status = 'WORKING'; const result = await provider.execute(context, { type: 'syncIdentity', wahaSession: 'chatpro-b60c5708e0c4a09d91258bd25a5a81a0c48104a9', chatId: '120363363444637332@g.us', senderWhatsappId: '5511999999999@c.us', refreshIdentity: true, refreshGroup: true }); expect(result).toMatchObject({ identity: { whatsappId: '5511999999999@c.us' }, group: { chatId: '120363363444637332@g.us', participants: [{ whatsappId: '5511999999999@c.us' }] } }); expect(client.calls).toEqual(expect.arrayContaining(['identity', 'group'])); });
});
