"use client";
import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { ConnectorApiClient, ConnectorApiError, type ConnectorInstanceStatus } from "@/lib/whatsapp-connector/client";
const INSTANCE_ID = "chatpro-main";
type ScreenStatus = "not_created" | "stopped" | "starting" | "qr_ready" | "connected" | "error";
const labels: Record<ScreenStatus, string> = { not_created: "Não criada", stopped: "Parada", starting: "Iniciando", qr_ready: "Aguardando QR", connected: "Conectada", error: "Erro" };
function toScreenStatus(status: ConnectorInstanceStatus): ScreenStatus { if (status === "stopped" || status === "stopping") return "stopped"; if (status === "starting") return "starting"; if (status === "qr_ready") return "qr_ready"; if (status === "connected") return "connected"; return "error"; }
function qrImageSource(value: string): string { return value.startsWith("data:image/") ? value : `data:image/png;base64,${value}`; }

export function WhatsAppInstance({ connectorApiUrl }: { connectorApiUrl: string }) {
  const client = useMemo(() => new ConnectorApiClient(connectorApiUrl), [connectorApiUrl]);
  const [status, setStatus] = useState<ScreenStatus>("not_created"); const [qrCode, setQrCode] = useState<string>(); const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false);
  useEffect(() => { void (async () => { try { const result = await client.getStatus(INSTANCE_ID); setStatus(toScreenStatus(result.status)); } catch (error) { if (error instanceof ConnectorApiError && error.code === "not_found") setStatus("not_created"); else { setStatus("error"); setMessage(error instanceof Error ? error.message : "Não foi possível consultar a instância WhatsApp."); } } })(); }, [client]);
  async function run(operation: () => Promise<void>) { setBusy(true); setMessage(undefined); try { await operation(); } catch (error) { setStatus("error"); setQrCode(undefined); setMessage(error instanceof Error ? error.message : "Não foi possível concluir a operação do WhatsApp."); } finally { setBusy(false); } }
  function create() { return run(async () => { await client.createInstance(INSTANCE_ID); setStatus("stopped"); setMessage("Instância criada e pronta para iniciar."); }); }
  function start() { return run(async () => { const result = await client.startInstance(INSTANCE_ID); setStatus(toScreenStatus(result.status)); setQrCode(undefined); setMessage("Instância iniciada. Consulte o status ou atualize o QR Code."); }); }
  function refreshStatus() { return run(async () => { const result = await client.getStatus(INSTANCE_ID); const next = toScreenStatus(result.status); setStatus(next); if (next === "connected" || next === "stopped") setQrCode(undefined); setMessage(`Status atualizado: ${labels[next]}.`); }); }
  function refreshQr() { return run(async () => { const result = await client.getQrCode(INSTANCE_ID); if (result.status !== "available" || !result.qrCode) { setStatus("qr_ready"); setQrCode(undefined); setMessage("O QR Code ainda não está disponível. Tente atualizar em instantes."); return; } setStatus("qr_ready"); setQrCode(result.qrCode); setMessage("QR Code atualizado. Ele é temporário e não é armazenado."); }); }
  function stop() { return run(async () => { const result = await client.stopInstance(INSTANCE_ID); setStatus(toScreenStatus(result.status)); setQrCode(undefined); setMessage("Instância parada."); }); }
  return <section className="mt-12 rounded-2xl border border-neutral-800 bg-neutral-900/50 p-6 sm:p-8" aria-labelledby="whatsapp-heading"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-400">WhatsApp</p><h2 id="whatsapp-heading" className="mt-2 text-2xl font-semibold">Instância local</h2><p className="mt-2 text-sm text-neutral-400">Gerencie uma única instância pelo conector local do ChatPro.</p></div><span className="w-fit rounded-full border border-neutral-700 px-3 py-1 text-sm text-neutral-200">{labels[status]}</span></div>{message ? <p role="status" className={`mt-5 rounded-lg border p-3 text-sm ${status === "error" ? "border-red-900 bg-red-950/40 text-red-200" : "border-neutral-700 bg-neutral-950/50 text-neutral-300"}`}>{message}</p> : null}<div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={create} disabled={busy || status !== "not_created"} className="rounded-lg bg-emerald-500 px-4 py-2 text-sm font-semibold text-neutral-950 disabled:cursor-not-allowed disabled:opacity-50">Criar instância</button><button type="button" onClick={start} disabled={busy || status === "not_created" || status === "connected"} className="rounded-lg border border-neutral-600 px-4 py-2 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50">Iniciar</button><button type="button" onClick={refreshStatus} disabled={busy || status === "not_created"} className="rounded-lg border border-neutral-600 px-4 py-2 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50">Consultar status</button><button type="button" onClick={refreshQr} disabled={busy || status === "not_created" || status === "connected"} className="rounded-lg border border-neutral-600 px-4 py-2 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50">Atualizar QR</button><button type="button" onClick={stop} disabled={busy || status === "not_created" || status === "stopped"} className="rounded-lg border border-red-900 px-4 py-2 text-sm font-semibold text-red-200 disabled:cursor-not-allowed disabled:opacity-50">Parar</button></div>{busy ? <p className="mt-4 text-sm text-neutral-400">Aguarde, processando operação local…</p> : null}{qrCode ? <div className="mt-6 w-fit rounded-xl bg-white p-3"><Image unoptimized src={qrImageSource(qrCode)} alt="QR Code temporário para conectar a instância WhatsApp" width={224} height={224} /></div> : null}</section>;
}
