import { createHash } from 'node:crypto';
import { createSessionRequestSchema, requestContextSchema, whatsAppSessionSchema, type RequestContext, type SessionStatus, type WhatsAppSession } from '@chatpro/contracts';
import { assertSafeIdentifier } from './identifiers.js'; import { WorkerOperationError, type WhatsAppWorkerPort, type WorkerCommand } from './ports.js'; import { WahaClientError, type WahaClientPort } from './waha-client.js'; import type { WahaSessionRegistryEntry } from './waha-session-registry.js';
const statusMap: Record<string, SessionStatus> = { STOPPED: 'stopped', STARTING: 'connecting', SCAN_QR_CODE: 'waiting_qr', WORKING: 'connected', FAILED: 'error', LOGGED_OUT: 'disconnected' }; type StoredSession = WhatsAppSession & { wahaName: string }; type Registry = { load(): Promise<WahaSessionRegistryEntry[]>; save(entries: WahaSessionRegistryEntry[]): Promise<void> };
export class WahaProvider implements WhatsAppWorkerPort {
  private readonly sessions = new Map<string, StoredSession>(); private restored = false;
  constructor(private readonly client: WahaClientPort, private readonly qrTtlMs: number, private readonly registry: Registry = { load: async () => [], save: async () => undefined }) {}
  async execute(context: RequestContext, command: WorkerCommand) { await this.restore(); if (command.type === 'listSessions') return Promise.all([...this.sessions.values()].filter(session => session.workspaceId === context.workspaceId).map(session => this.refresh(context, session))); if (command.type === 'createSession') return this.create(context, command.sessionId, command.input); const stored = this.require(context, command.sessionId); if (command.type === 'getSession') return this.refresh(context, stored); if (command.type === 'connectSession') { await this.call(context, () => this.client.startSession(stored.wahaName)); await this.refresh(context, stored); return; } if (command.type === 'disconnectSession') { await this.call(context, () => this.client.stopSession(stored.wahaName)); this.setStatus(stored, 'stopped'); return; } if (command.type === 'logoutSession') { await this.call(context, () => this.client.logoutSession(stored.wahaName)); this.setStatus(stored, 'disconnected'); return; } if (command.type === 'getQr') { const qr = await this.call(context, () => this.client.getQr(stored.wahaName)); return { sessionId: stored.id, workspaceId: stored.workspaceId, qr, expiresAt: new Date(Date.now() + this.qrTtlMs).toISOString() }; } await this.call(context, () => this.client.removeSession(stored.wahaName)); this.sessions.delete(this.key(context.workspaceId, stored.id)); await this.persist(); }
  async shutdown(): Promise<void> { /* WAHA sessions are durable runtime resources; stopping the worker must not alter their remote state. */ }
  private async create(context: RequestContext, sessionId: string, input: { name?: string }): Promise<WhatsAppSession> { const valid = requestContextSchema.parse(context); const id = assertSafeIdentifier(sessionId, 'sessionId', context.correlationId); const body = createSessionRequestSchema.parse(input); const key = this.key(valid.workspaceId, id); if (this.sessions.has(key)) throw new WorkerOperationError('CONFLICT', 'Session already exists', context.correlationId); const now = new Date().toISOString(); const stored: StoredSession = { ...whatsAppSessionSchema.parse({ id, workspaceId: valid.workspaceId, name: body.name ?? id, status: 'disconnected', createdAt: now, updatedAt: now }), wahaName: this.wahaName(valid.workspaceId, id) }; await this.call(context, () => this.client.createSession(stored.wahaName)); this.sessions.set(key, stored); await this.persist(); return stored; }
  private async restore(): Promise<void> { if (this.restored) return; for (const entry of await this.registry.load()) { const now = new Date().toISOString(); const stored: StoredSession = { ...whatsAppSessionSchema.parse({ id: entry.sessionId, workspaceId: entry.workspaceId, name: entry.name, status: 'disconnected', createdAt: now, updatedAt: now }), wahaName: entry.wahaName }; this.sessions.set(this.key(entry.workspaceId, entry.sessionId), stored); } this.restored = true; }
  private async persist(): Promise<void> { await this.registry.save([...this.sessions.values()].map(({ id, workspaceId, name, wahaName }) => ({ sessionId: id, workspaceId, name, wahaName }))); }
  private async refresh(context: RequestContext, stored: StoredSession): Promise<WhatsAppSession> { const external = await this.call(context, () => this.client.getSession(stored.wahaName)); this.setStatus(stored, statusMap[external.status.toUpperCase()] ?? 'error'); return stored; } private require(context: RequestContext, id: string): StoredSession { requestContextSchema.parse(context); const session = this.sessions.get(this.key(context.workspaceId, assertSafeIdentifier(id, 'sessionId', context.correlationId))); if (!session) throw new WorkerOperationError('NOT_FOUND', 'Session not found', context.correlationId); return session; } private key(workspaceId: string, sessionId: string): string { return `${workspaceId}:${sessionId}`; } private wahaName(workspaceId: string, sessionId: string): string { return `chatpro-${createHash('sha256').update(`${workspaceId}:${sessionId}`).digest('hex').slice(0, 40)}`; } private setStatus(session: StoredSession, status: SessionStatus): void { session.status = status; session.updatedAt = new Date().toISOString(); } private async call<T>(context: RequestContext, action: () => Promise<T>): Promise<T> { try { return await action(); } catch (error) { if (error instanceof WahaClientError) throw new WorkerOperationError(error.kind === 'timeout' ? 'TIMEOUT' : 'SERVICE_UNAVAILABLE', error.kind === 'timeout' ? 'WAHA request timed out' : 'WAHA provider is unavailable', context.correlationId); throw error; } }
}
