import { createHash } from 'node:crypto';
import { createSessionRequestSchema, requestContextSchema, whatsAppSessionSchema, type RequestContext, type SessionStatus, type WhatsAppSession } from '@chatpro/contracts';
import { assertSafeIdentifier } from './identifiers.js'; import { WorkerOperationError, type WhatsAppWorkerPort, type WorkerCommand } from './ports.js'; import { WahaClientError, type WahaClientPort } from './waha-client.js'; import type { WahaSessionRegistryEntry } from './waha-session-registry.js';
const statusMap: Record<string, SessionStatus> = { STOPPED: 'stopped', STARTING: 'connecting', AUTHENTICATED: 'connecting', SYNCING: 'connecting', SCAN_QR_CODE: 'waiting_qr', WORKING: 'connected', READY: 'connected', CONNECTED: 'connected', FAILED: 'error', LOGGED_OUT: 'disconnected' }; type StoredSession = WhatsAppSession & { wahaName: string }; type Registry = { load(): Promise<WahaSessionRegistryEntry[]>; save(entries: WahaSessionRegistryEntry[]): Promise<void> };
export class WahaProvider implements WhatsAppWorkerPort {
  private readonly sessions = new Map<string, StoredSession>(); private restored = false;
  constructor(private readonly client: WahaClientPort, private readonly qrTtlMs: number, private readonly registry: Registry = { load: async () => [], save: async () => undefined }) {}
  async execute(context: RequestContext, command: WorkerCommand) { await this.restore(); if (command.type === 'listSessions') return Promise.all([...this.sessions.values()].filter(session => session.workspaceId === context.workspaceId).map(session => this.refresh(context, session))); if (command.type === 'createSession') return this.create(context, command.sessionId, command.input); if (command.type === 'sendMessage') return this.sendText(context, command.wahaSession, command.chatId, command.text); if (command.type === 'syncIdentity') return this.syncIdentity(context, command); if (command.type === 'historyPage') return this.historyPage(context, command); const stored = this.require(context, command.sessionId); if (command.type === 'getSession') return this.refresh(context, stored); if (command.type === 'connectSession') { await this.call(context, () => this.client.startSession(stored.wahaName)); await this.refresh(context, stored); return; } if (command.type === 'disconnectSession') { await this.call(context, () => this.client.stopSession(stored.wahaName)); this.setStatus(stored, 'stopped'); return; } if (command.type === 'logoutSession') { await this.call(context, () => this.client.logoutSession(stored.wahaName)); this.setStatus(stored, 'disconnected'); return; } if (command.type === 'getQr') return this.qr(context, stored); await this.call(context, () => this.client.removeSession(stored.wahaName)); this.sessions.delete(this.key(context.workspaceId, stored.id)); await this.persist(); }
  async shutdown(): Promise<void> { /* WAHA sessions are durable runtime resources; stopping the worker must not alter their remote state. */ }
  private async create(context: RequestContext, sessionId: string, input: { name?: string }): Promise<WhatsAppSession> { const valid = requestContextSchema.parse(context); const id = assertSafeIdentifier(sessionId, 'sessionId', context.correlationId); const body = createSessionRequestSchema.parse(input); const key = this.key(valid.workspaceId, id); if (this.sessions.has(key)) throw new WorkerOperationError('CONFLICT', 'Session already exists', context.correlationId); const now = new Date().toISOString(); const stored: StoredSession = { ...whatsAppSessionSchema.parse({ id, workspaceId: valid.workspaceId, name: body.name ?? id, status: 'disconnected', createdAt: now, updatedAt: now }), wahaName: this.wahaName(valid.workspaceId, id) }; await this.call(context, () => this.client.createSession(stored.wahaName)); this.sessions.set(key, stored); await this.persist(); return stored; }
  private async restore(): Promise<void> { if (this.restored) return; for (const entry of await this.registry.load()) { const now = new Date().toISOString(); const stored: StoredSession = { ...whatsAppSessionSchema.parse({ id: entry.sessionId, workspaceId: entry.workspaceId, name: entry.name, status: 'disconnected', createdAt: now, updatedAt: now }), wahaName: entry.wahaName }; this.sessions.set(this.key(entry.workspaceId, entry.sessionId), stored); } this.restored = true; }
  private async persist(): Promise<void> { await this.registry.save([...this.sessions.values()].map(({ id, workspaceId, name, wahaName }) => ({ sessionId: id, workspaceId, name, wahaName }))); }
  private async qr(context: RequestContext, stored: StoredSession) {
    await this.refresh(context, stored);
    if (stored.status !== 'waiting_qr') throw this.qrUnavailable(context, stored);
    try {
      const qr = await this.client.getQr(stored.wahaName);
      return { sessionId: stored.id, workspaceId: stored.workspaceId, qr, expiresAt: new Date(Date.now() + this.qrTtlMs).toISOString() };
    } catch (error) {
      if (error instanceof WahaClientError && (error.kind === 'timeout' || error.status === 404 || error.status === 422)) {
        await this.refresh(context, stored);
        throw this.qrUnavailable(context, stored);
      }
      throw await this.call(context, async () => { throw error; });
    }
  }
  private async sendText(context: RequestContext, wahaSession: string, chatId: string, text: string) { requestContextSchema.parse(context); const stored = [...this.sessions.values()].find(session => session.workspaceId === context.workspaceId && session.wahaName === wahaSession); if (!stored) throw new WorkerOperationError('NOT_FOUND', 'WhatsApp session not found', context.correlationId); const current = await this.refresh(context, stored); if (current.status !== 'connected') throw new WorkerOperationError('CONFLICT', 'WhatsApp session is not connected', context.correlationId, { status: current.status }); const sent = await this.call(context, () => this.client.sendText(stored.wahaName, chatId, text)); return { ...(sent.id ? { id: sent.id } : {}), pending: sent.pending, timestamp: new Date().toISOString() }; }
  private async syncIdentity(context: RequestContext, command: Extract<WorkerCommand, { type: 'syncIdentity' }>) { requestContextSchema.parse(context); const stored = [...this.sessions.values()].find(session => session.workspaceId === context.workspaceId && session.wahaName === command.wahaSession); if (!stored) throw new WorkerOperationError('NOT_FOUND', 'WhatsApp session not found', context.correlationId); const current = await this.refresh(context, stored); if (current.status !== 'connected') throw new WorkerOperationError('CONFLICT', 'WhatsApp session is not connected', context.correlationId, { status: current.status }); const identityId = command.senderWhatsappId ?? command.chatId; const identity = command.refreshIdentity ? await this.call(context, () => this.client.getIdentity(stored.wahaName, identityId)) : null; const group = command.refreshGroup ? await this.call(context, () => this.client.getGroup(stored.wahaName, command.chatId)) : null; return { identity, group }; }
  private async historyPage(context: RequestContext, command: Extract<WorkerCommand, { type: 'historyPage' }>) { requestContextSchema.parse(context); const stored = [...this.sessions.values()].find(session => session.workspaceId === context.workspaceId && session.wahaName === command.wahaSession); if (!stored) throw new WorkerOperationError('NOT_FOUND', 'WhatsApp session not found', context.correlationId); const current = await this.refresh(context, stored); if (current.status !== 'connected') throw new WorkerOperationError('CONFLICT', 'WhatsApp session is not connected', context.correlationId, { status: current.status }); const page = command.chatId ? await this.call(context, () => this.client.listMessages(stored.wahaName, command.chatId!, command.offset, command.limit)) : await this.call(context, () => this.client.listChats(stored.wahaName, command.offset, command.limit)); return { kind: command.chatId ? 'messages' as const : 'chats' as const, ...page }; }
  private qrUnavailable(context: RequestContext, stored: StoredSession): WorkerOperationError { return new WorkerOperationError('CONFLICT', 'QR code is not available for the current session status', context.correlationId, { status: stored.status }); }
  private async refresh(context: RequestContext, stored: StoredSession): Promise<WhatsAppSession> { const external = await this.call(context, () => this.client.getSession(stored.wahaName)); this.setStatus(stored, statusMap[external.status.toUpperCase()] ?? 'error'); return stored; } private require(context: RequestContext, id: string): StoredSession { requestContextSchema.parse(context); const session = this.sessions.get(this.key(context.workspaceId, assertSafeIdentifier(id, 'sessionId', context.correlationId))); if (!session) throw new WorkerOperationError('NOT_FOUND', 'Session not found', context.correlationId); return session; } private key(workspaceId: string, sessionId: string): string { return `${workspaceId}:${sessionId}`; } private wahaName(workspaceId: string, sessionId: string): string { return `chatpro-${createHash('sha256').update(`${workspaceId}:${sessionId}`).digest('hex').slice(0, 40)}`; } private setStatus(session: StoredSession, status: SessionStatus): void { session.status = status; session.updatedAt = new Date().toISOString(); } private async call<T>(context: RequestContext, action: () => Promise<T>): Promise<T> { try { return await action(); } catch (error) { if (error instanceof WahaClientError) { const code = error.kind === 'timeout' ? 'TIMEOUT' : error.kind === 'unavailable' || (error.status !== undefined && error.status >= 500) ? 'SERVICE_UNAVAILABLE' : error.kind === 'contract' ? 'PROVIDER_CONTRACT_ERROR' : error.status === 400 ? 'VALIDATION_ERROR' : error.status === 404 ? 'NOT_FOUND' : error.status === 409 ? 'CONFLICT' : 'PROVIDER_CONTRACT_ERROR'; const message = error.kind === 'timeout' ? 'WAHA request timed out' : error.kind === 'unavailable' ? 'WAHA provider is unavailable' : error.kind === 'contract' ? 'WAHA response contract is invalid' : error.providerMessage ? `WAHA request failed (${error.status}): ${error.providerMessage}` : `WAHA request failed with status ${error.status ?? 'unknown'}`; throw new WorkerOperationError(code, message, context.correlationId, { ...(error.status ? { providerStatus: error.status } : {}), ...(error.providerMessage ? { providerMessage: error.providerMessage } : {}), ...error.details }); } throw error; } }
}
