import { describe, expect, it, vi } from 'vitest';
import { ApiClient, ApiError } from './client';
const response = (status: number, body?: unknown) => ({ status, ok: status >= 200 && status < 300, json: vi.fn().mockResolvedValue(body) }) as unknown as Response;
describe('ApiClient', () => {
  it('preserva o contexto do fetch nativo do navegador', async () => { const original = globalThis.fetch; const browserFetch = function(this: unknown) { if (this !== globalThis) throw new TypeError('Illegal invocation'); return Promise.resolve(response(200, [{ id: 'session' }])); } as typeof fetch; globalThis.fetch = browserFetch; try { await expect(new ApiClient().get('/api/v1/sessions')).resolves.toEqual([{ id: 'session' }]); } finally { globalThis.fetch = original; } });
  it('envia o workspace e o corpo para a API real', async () => { const fetcher = vi.fn().mockResolvedValue(response(200, { ok: true })); await new ApiClient({ fetcher, workspaceId: 'workspace-test' }).post('/api/v1/domain/contacts', { displayName: 'Ana' }); expect(fetcher.mock.calls[0][1].headers['x-workspace-id']).toBe('workspace-test'); expect(fetcher.mock.calls[0][1].body).toContain('Ana'); });
  it('mantÃ©m uma resposta 200 com JSON vÃ¡lido', async () => { await expect(new ApiClient({ fetcher: vi.fn().mockResolvedValue(response(200, { sessions: [] })) }).get('/api/v1/sessions')).resolves.toEqual({ sessions: [] }); });
  it('classifica falha de parse sem simular indisponibilidade', async () => { const invalid = { status: 200, ok: true, json: vi.fn().mockRejectedValue(new SyntaxError('invalid JSON')) } as unknown as Response; await expect(new ApiClient({ fetcher: vi.fn().mockResolvedValue(invalid) }).get('/api/v1/sessions')).rejects.toMatchObject({ code: 'REQUEST_FAILED', details: { phase: 'parse', status: 200 } }); });
  it('normaliza indisponibilidade e timeout', async () => { await expect(new ApiClient({ fetcher: vi.fn().mockRejectedValue(new TypeError('offline')) }).get('/health')).rejects.toMatchObject({ code: 'API_UNAVAILABLE' }); vi.useFakeTimers(); const fetcher = vi.fn((_url: RequestInfo | URL, init?: RequestInit) => new Promise<Response>((_, reject) => init?.signal?.addEventListener('abort', () => reject(new DOMException('', 'AbortError'))))); const pending = new ApiClient({ fetcher: fetcher as typeof fetch, timeoutMs: 1 }).get('/health'); const check = expect(pending).rejects.toMatchObject({ code: 'TIMEOUT' }); await vi.advanceTimersByTimeAsync(2); await check; vi.useRealTimers(); });
});
