import type { Activity, Campaign, Lead, PersistenceContact as Contact, PersistenceTemplate as Template, Pipeline, Stage, Tag } from '@chatpro/contracts';
import { ApiClient } from './client';
export type Page<T> = { items: T[]; page: number; pageSize: number; total: number };
export type Dashboard = { contacts:number; optOutContacts:number; tags:number; templates:number; leads:number; leadsByStage:Array<{stageId:string;name:string;position:number;total:number}>; recentActivities:Activity[]; campaignsByStatus:Array<{status:string;total:number}>; sessionsByStatus:Array<{status:string;total:number}> };
export type Settings = { workspaceId:string; settings: { workspaceName?:string; locale?:string; timezone?:string; defaultCountryCode?:string; operational?:Record<string,string|number|boolean|null> } };
export const query = (values: Record<string, string | number | boolean | undefined>) => { const p = new URLSearchParams(); Object.entries(values).forEach(([k,v]) => v !== undefined && v !== '' && p.set(k,String(v))); const text=p.toString(); return text ? `?${text}` : ''; };
export class DomainApi {
  constructor(private readonly http = new ApiClient()) {}
  dashboard=()=>this.http.get<Dashboard>('/api/v1/domain/dashboard'); tags=()=>this.http.get<Tag[]>('/api/v1/domain/tags'); createTag=(x:Pick<Tag,'name'|'color'>)=>this.http.post<Tag>('/api/v1/domain/tags',x); updateTag=(id:string,x:Partial<Pick<Tag,'name'|'color'>>)=>this.http.patch<Tag>(`/api/v1/domain/tags/${id}`,x); deleteTag=(id:string)=>this.http.delete(`/api/v1/domain/tags/${id}`);
  contacts=(q:Record<string,string|number|boolean|undefined>={})=>this.http.get<Page<Contact>>(`/api/v1/domain/contacts${query(q)}`); createContact=(x:unknown)=>this.http.post<Contact>('/api/v1/domain/contacts',x); updateContact=(id:string,x:unknown)=>this.http.patch<Contact>(`/api/v1/domain/contacts/${id}`,x); deleteContact=(id:string)=>this.http.delete(`/api/v1/domain/contacts/${id}`); importContacts=(csv:string)=>this.http.post<{created:Contact[];rejected:unknown[]}>('/api/v1/domain/contacts/import',{csv}); exportContacts=()=>this.http.get<string>('/api/v1/domain/contacts/export'); optOut=(id:string,body:unknown={})=>this.http.post(`/api/v1/domain/contacts/${id}/opt-out`,body); removeOptOut=(id:string)=>this.http.delete(`/api/v1/domain/contacts/${id}/opt-out`); optOutStatus=(id:string)=>this.http.get<{optedOut:boolean;history:unknown[]}>(`/api/v1/domain/contacts/${id}/opt-out`);
  templates=()=>this.http.get<(Template & {active:number|boolean})[]>('/api/v1/domain/templates'); saveTemplate=(id:string|undefined,x:unknown)=>id?this.http.patch<Template>(`/api/v1/domain/templates/${id}`,x):this.http.post<Template>('/api/v1/domain/templates',x); deleteTemplate=(id:string)=>this.http.delete(`/api/v1/domain/templates/${id}`); active=(id:string,yes:boolean)=>this.http.post<Template>(`/api/v1/domain/templates/${id}/${yes?'activate':'deactivate'}`); preview=(id:string,data:Record<string,string>)=>this.http.post<{content:string;variables:string[]}>(`/api/v1/domain/templates/${id}/preview`,{data});
  initialize=(name?:string)=>this.http.post<{pipeline:Pipeline;stages:Stage[]}>('/api/v1/domain/crm/initialize',name?{name}:{}); pipelines=()=>this.http.get<Pipeline[]>('/api/v1/domain/crm/pipelines'); stages=(id:string)=>this.http.get<Stage[]>(`/api/v1/domain/crm/pipelines/${id}/stages`); leads=(q:Record<string,string|number|boolean|undefined>={})=>this.http.get<Page<Lead>>(`/api/v1/domain/crm/leads${query(q)}`); saveLead=(id:string|undefined,x:unknown)=>id?this.http.patch<Lead>(`/api/v1/domain/crm/leads/${id}`,x):this.http.post<Lead>('/api/v1/domain/crm/leads',x); moveLead=(id:string,stageId:string)=>this.http.post<Lead>(`/api/v1/domain/crm/leads/${id}/move`,{stageId}); deleteLead=(id:string)=>this.http.delete(`/api/v1/domain/crm/leads/${id}`); notes=(id:string)=>this.http.get<Array<{id:string;body:string}>>(`/api/v1/domain/crm/leads/${id}/notes`); addNote=(id:string,body:string)=>this.http.post(`/api/v1/domain/crm/leads/${id}/notes`,{body}); activities=(id:string)=>this.http.get<Activity[]>(`/api/v1/domain/crm/leads/${id}/activities`); funnel=()=>this.http.get<Array<{stageId:string;name:string;total:number}>>('/api/v1/domain/crm/funnel');
  campaigns=(q:Record<string,string|number|boolean|undefined>={})=>this.http.get<Page<Campaign>>(`/api/v1/domain/campaigns${query(q)}`); saveCampaign=(id:string|undefined,x:unknown)=>id?this.http.patch<Campaign>(`/api/v1/domain/campaigns/${id}`,x):this.http.post<Campaign>('/api/v1/domain/campaigns',x); validate=(id:string)=>this.http.post<{valid:boolean;problems:string[];recipients:number}>(`/api/v1/domain/campaigns/${id}/validate`); prepare=(id:string)=>this.http.post<{eligibleRecipients:number;excludedOptOut:number;problems:string[]}>(`/api/v1/domain/campaigns/${id}/prepare`); schedule=(id:string,scheduledAt:string)=>this.http.post<Campaign>(`/api/v1/domain/campaigns/${id}/schedule`,{scheduledAt}); cancel=(id:string)=>this.http.post<Campaign>(`/api/v1/domain/campaigns/${id}/cancel`);
  settings=()=>this.http.get<Settings>('/api/v1/domain/settings'); saveSettings=(x:Settings['settings'])=>this.http.put<Settings>('/api/v1/domain/settings',x);
}
