import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { SqlitePersistenceDatabase } from '../src/persistence/database.js';
import { createSqliteDomainRepository } from '../src/persistence/sqlite-domain.repository.js';
import { DomainService } from '../src/services/domain.service.js';
const dirs:string[]=[]; const create=()=>{const dir=mkdtempSync(join(tmpdir(),'chatpro-domain-'));dirs.push(dir);const db=new SqlitePersistenceDatabase(join(dir,'db.sqlite'),join(process.cwd(),'migrations'));db.migrate();return {db,service:new DomainService(createSqliteDomainRepository(db.sqlite))}}; afterEach(()=>{dirs.splice(0).forEach(d=>rmSync(d,{recursive:true,force:true}));});
describe('domain services',()=>{
  it('handles contacts, tags, templates, opt-out and campaign preparation in isolation',async()=>{const {db,service}=create();try{expect(await service.dashboard('a')).toMatchObject({contacts:0,optOutContacts:0});const tag:any=await service.createTag('a',{name:'VIP',color:'#ffffff'});const c:any=await service.createContact('a',{displayName:'Ada',phoneNumber:'+55 (11) 99999-0000',tagIds:[tag.id]});expect(c.phoneNumber).toBe('5511999990000');await expect(service.createContact('a',{displayName:'Dup',phoneNumber:c.phoneNumber})).rejects.toThrow();expect((await service.contacts('b',{} )as any).total).toBe(0);await expect(service.deleteTag('a',tag.id)).rejects.toThrow();const template:any=await service.saveTemplate('a',undefined,{name:'Hello',content:'Oi {{name}}'});expect((await service.preview('a',template.id,{data:{name:'Ada'}})as any).content).toBe('Oi Ada');await service.optOut('a',c.id,{reason:'requested'});expect((await service.optOutStatus('a',c.id)as any).optedOut).toBe(true);const campaign:any=await service.saveCampaign('a',undefined,{name:'C',templateId:template.id,contactIds:[c.id]});expect(await service.prepareCampaign('a',campaign.id)).toMatchObject({eligibleRecipients:0,excludedOptOut:1,campaign:{status:'blocked'}});await service.removeOptOut('a',c.id);expect((await service.scheduleCampaign('a',campaign.id,{scheduledAt:'2030-01-01T00:00:00.000Z'})as any).status).toBe('scheduled');expect(await service.exportContacts('a')).toContain('Ada');}finally{db.close()}});
  it('initializes CRM explicitly and records lead movement and notes',async()=>{const {db,service}=create();try{const init:any=await service.initPipeline('a',{});expect(init.stages).toHaveLength(5);const lead:any=await service.saveLead('a',undefined,{stageId:init.stages[0].id,title:'Opportunity'});await service.moveLead('a',lead.id,{stageId:init.stages[1].id});await service.note('a',lead.id,{body:'Follow up'});expect(await service.activities('a',lead.id)).toHaveLength(2);const stage=(await service.funnel('a') as any[]).find(s=>s.stageId===init.stages[1].id);expect(stage.total).toBe(1);}finally{db.close()}});
});
