import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { SqlitePersistenceDatabase } from '../src/persistence/database.js';
import { DomainService } from '../src/services/domain.service.js';
const dirs:string[]=[]; const create=()=>{const dir=mkdtempSync(join(tmpdir(),'chatpro-domain-'));dirs.push(dir);const db=new SqlitePersistenceDatabase(join(dir,'db.sqlite'),join(process.cwd(),'migrations'));db.migrate();return {db,service:new DomainService(db.sqlite)}}; afterEach(()=>{dirs.splice(0).forEach(d=>rmSync(d,{recursive:true,force:true}));});
describe('domain services',()=>{
  it('handles contacts, tags, templates, opt-out and campaign preparation in isolation',()=>{const {db,service}=create();try{expect(service.dashboard('a')).toMatchObject({contacts:0,optOutContacts:0});const tag:any=service.createTag('a',{name:'VIP',color:'#ffffff'});const c:any=service.createContact('a',{displayName:'Ada',phoneNumber:'+55 (11) 99999-0000',tagIds:[tag.id]});expect(c.phoneNumber).toBe('5511999990000');expect(()=>service.createContact('a',{displayName:'Dup',phoneNumber:c.phoneNumber})).toThrow();expect(service.contacts('b',{}).total).toBe(0);expect(()=>service.deleteTag('a',tag.id)).toThrow();const template:any=service.saveTemplate('a',undefined,{name:'Hello',content:'Oi {{name}}'});expect(service.preview('a',template.id,{data:{name:'Ada'}}).content).toBe('Oi Ada');service.optOut('a',c.id,{reason:'requested'});expect(service.optOutStatus('a',c.id).optedOut).toBe(true);const campaign:any=service.saveCampaign('a',undefined,{name:'C',templateId:template.id,contactIds:[c.id]});expect(service.prepareCampaign('a',campaign.id)).toMatchObject({eligibleRecipients:0,excludedOptOut:1,campaign:{status:'blocked'}});service.removeOptOut('a',c.id);expect(service.scheduleCampaign('a',campaign.id,{scheduledAt:'2030-01-01T00:00:00.000Z'}).status).toBe('scheduled');expect(service.exportContacts('a')).toContain('Ada');expect(()=>service.importContacts('a',{csv:'displayName,phoneNumber\nBad,1'})).toThrow();}finally{db.close()}});
  it('initializes CRM explicitly and records lead movement and notes',()=>{const {db,service}=create();try{const init:any=service.initPipeline('a',{});expect(init.stages).toHaveLength(5);const lead:any=service.saveLead('a',undefined,{stageId:init.stages[0].id,title:'Opportunity'});service.moveLead('a',lead.id,{stageId:init.stages[1].id});service.note('a',lead.id,{body:'Follow up'});expect(service.activities('a',lead.id)).toHaveLength(2);const stage=(service.funnel('a') as any[]).find(s=>s.stageId===init.stages[1].id);expect(stage.total).toBe(1);expect(()=>service.deleteStage('a',init.stages[1].id)).toThrow();}finally{db.close()}});
});
