import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { SqlitePersistenceDatabase } from '../src/persistence/database.js';
import { createPersistenceRepositories } from '../src/persistence/repositories.js';

const migrationDirectory = join(process.cwd(), 'migrations');
const temporaryDirectories: string[] = [];
function databaseAtTemporaryPath() { const directory = mkdtempSync(join(tmpdir(), 'chatpro-persistence-')); temporaryDirectories.push(directory); return new SqlitePersistenceDatabase(join(directory, 'backend.sqlite'), migrationDirectory); }
afterEach(() => { for (const directory of temporaryDirectories.splice(0)) rmSync(directory, { recursive: true, force: true }); });

describe('SQLite persistence', () => {
  it('migrates an empty database once and preserves its migration journal', () => { const database = databaseAtTemporaryPath(); database.migrate(); const first = database.sqlite.prepare('SELECT id FROM schema_migrations').all(); database.migrate(); expect(database.sqlite.prepare('SELECT id FROM schema_migrations').all()).toEqual(first); expect(first).toHaveLength(10); database.close(); });
  it('enforces workspace isolation, normalized phone uniqueness, and basic repository CRUD', () => { const database = databaseAtTemporaryPath(); try { database.migrate(); const repositories = createPersistenceRepositories(database.sqlite); const contact = repositories.contacts.insert('one', { displayName: 'Ada', phoneNumber: '+55 (11) 99999-0000', email: null, company: null }); expect(contact.phoneNumber).toBe('5511999990000'); expect(repositories.contacts.findById('two', contact.id)).toBeUndefined(); expect(repositories.contacts.update('one', contact.id, { displayName: 'Ada Lovelace' })?.displayName).toBe('Ada Lovelace'); expect(() => repositories.contacts.insert('one', { displayName: 'Duplicate', phoneNumber: '5511999990000', email: null, company: null })).toThrow(); expect(repositories.contacts.insert('two', { displayName: 'Same other workspace', phoneNumber: '5511999990000', email: null, company: null }).workspaceId).toBe('two'); expect(repositories.contacts.delete('one', contact.id)).toBe(true); } finally { database.close(); } });
  it('keeps contact-tag and lead-stage relationships within one workspace', () => { const database = databaseAtTemporaryPath(); database.migrate(); const repositories = createPersistenceRepositories(database.sqlite); const contact = repositories.contacts.insert('one', { displayName: 'Ada', phoneNumber: '5511999990000', email: null, company: null }); const tag = repositories.tags.insert('one', { name: 'VIP', color: null }); repositories.tagRelations.attachToContact('one', contact.id, tag.id); const pipeline = repositories.pipelines.insert('one', { name: 'Sales' }); const stage = repositories.stages.insert('one', { pipelineId: pipeline.id, name: 'New', position: 0 }); const lead = repositories.leads.insert('one', { stageId: stage.id, contactId: contact.id, title: 'Ada deal' }); expect(repositories.leads.findById('one', lead.id)?.stageId).toBe(stage.id); expect(() => repositories.tagRelations.attachToContact('two', contact.id, tag.id)).toThrow(); expect(() => repositories.leads.insert('two', { stageId: stage.id, contactId: null, title: 'Invalid cross workspace' })).toThrow(); database.close(); });
  it('persists after close and reopen, and temporary database files are removable', () => { const directory = mkdtempSync(join(tmpdir(), 'chatpro-persistence-')); const path = join(directory, 'backend.sqlite'); const first = new SqlitePersistenceDatabase(path, migrationDirectory); first.migrate(); const contact = createPersistenceRepositories(first.sqlite).contacts.insert('one', { displayName: 'Grace', phoneNumber: '5511888880000', email: null, company: null }); first.close(); const reopened = new SqlitePersistenceDatabase(path, migrationDirectory); reopened.migrate(); expect(createPersistenceRepositories(reopened.sqlite).contacts.findById('one', contact.id)?.displayName).toBe('Grace'); reopened.close(); rmSync(directory, { recursive: true, force: true }); expect(() => rmSync(directory, { recursive: true, force: true })).not.toThrow(); });
});
