import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import request from 'supertest';
import { afterEach, describe, expect, it } from 'vitest';
import { createApp } from '../src/app.js';
const owner='00000000-0000-4000-8000-000000000001'; const headers={'x-workspace-id':'workspace-a','x-user-id':owner}; const directories:string[]=[]; const apps:Array<Awaited<ReturnType<typeof createApp>>>=[];
async function appFor(){const dir=mkdtempSync(join(tmpdir(),'chatpro-routing-'));directories.push(dir);const app=await createApp({port:0,nodeEnv:'test',workerTransportUrl:'http://127.0.0.1:1/internal/transport',workerTransportTimeoutMs:20,databaseProvider:'sqlite',databasePath:join(dir,'api.sqlite'),developmentUserId:owner});apps.push(app);return app;}
afterEach(()=>{apps.splice(0).forEach(app=>app.locals.persistenceDatabase.close());directories.splice(0).forEach(dir=>rmSync(dir,{recursive:true,force:true}));});
const seedConversation=(app:any,id:string)=>{const now=new Date().toISOString();app.locals.persistenceDatabase.sqlite.prepare("INSERT INTO conversations (id,workspaceId,wahaSession,chatId,contactId,status,lastMessage,lastMessageAt,unreadCount,createdAt,updatedAt) VALUES (?,?,? ,?,NULL,'open',NULL,?,0,?,?)").run(id,'workspace-a','session-a',`${id}@c.us`,now,now,now);};
describe('routing queues',()=>{
  it('alternates round robin deterministically and never double assigns',async()=>{const app=await appFor();const one=(await request(app).post('/api/v1/workspace/users').set(headers).send({email:'a@chatpro.local',displayName:'A',status:'active'}).expect(201)).body;const two=(await request(app).post('/api/v1/workspace/users').set(headers).send({email:'b@chatpro.local',displayName:'B',status:'active'}).expect(201)).body;const queue=(await request(app).post('/api/v1/workspace/queues').set(headers).send({name:'Entrada',strategy:'round_robin'}).expect(201)).body;await request(app).post(`/api/v1/workspace/queues/${queue.id}/members`).set(headers).send({userId:two.id}).expect(201);await request(app).post(`/api/v1/workspace/queues/${queue.id}/members`).set(headers).send({userId:one.id}).expect(201);const ids=['10000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000003'];ids.forEach(id=>seedConversation(app,id));const routed=[] as any[];for(const id of ids)routed.push((await request(app).post(`/api/v1/inbox/conversations/${id}/queue`).set(headers).send({queueId:queue.id}).expect(200)).body);const ordered=[one.id,two.id].sort();expect(routed.map(x=>x.assignedUserId)).toEqual([ordered[0],ordered[1],ordered[0]]);const race='10000000-0000-4000-8000-000000000004';seedConversation(app,race);await Promise.all([request(app).post(`/api/v1/inbox/conversations/${race}/queue`).set(headers).send({queueId:queue.id}),request(app).post(`/api/v1/inbox/conversations/${race}/queue`).set(headers).send({queueId:queue.id})]);const events=app.locals.persistenceDatabase.sqlite.prepare('SELECT result FROM routing_events WHERE conversationId=?').all(race) as Array<{result:string}>;expect(events.filter(x=>x.result==='assigned')).toHaveLength(1);});
  it('uses least loaded, enforces limits, and preserves manual assignment',async()=>{const app=await appFor();const one=(await request(app).post('/api/v1/workspace/users').set(headers).send({email:'load-a@chatpro.local',displayName:'A',status:'active'}).expect(201)).body;const two=(await request(app).post('/api/v1/workspace/users').set(headers).send({email:'load-b@chatpro.local',displayName:'B',status:'active'}).expect(201)).body;const queue=(await request(app).post('/api/v1/workspace/queues').set(headers).send({name:'Carga',strategy:'least_loaded',maxOpenConversationsPerAgent:1}).expect(201)).body;for(const user of [one,two])await request(app).post(`/api/v1/workspace/queues/${queue.id}/members`).set(headers).send({userId:user.id}).expect(201);const first='20000000-0000-4000-8000-000000000001',second='20000000-0000-4000-8000-000000000002',third='20000000-0000-4000-8000-000000000003';[first,second,third].forEach(id=>seedConversation(app,id));const firstRoute=(await request(app).post(`/api/v1/inbox/conversations/${first}/queue`).set(headers).send({queueId:queue.id})).body;const secondRoute=(await request(app).post(`/api/v1/inbox/conversations/${second}/queue`).set(headers).send({queueId:queue.id})).body;expect(firstRoute.assignedUserId).not.toBe(secondRoute.assignedUserId);expect((await request(app).post(`/api/v1/inbox/conversations/${third}/queue`).set(headers).send({queueId:queue.id})).body.reasonSafe).toBe('no_eligible_agent');await request(app).post(`/api/v1/inbox/conversations/${third}/assign`).set(headers).send({userId:one.id}).expect(200);expect((await request(app).post(`/api/v1/inbox/conversations/${third}/queue`).set(headers).send({queueId:queue.id})).body.reasonSafe).toBe('already_assigned');});
});
