import type { RequestHandler } from 'express';
import { createHash } from 'node:crypto';
import { z } from 'zod';
import { AppError } from '../errors.js';
import { DomainService } from '../services/domain.service.js';
import type { WhatsAppContactSyncService } from '../services/whatsapp-contact-sync.service.js';
const routeId=(value:string|string[]|undefined,name:string)=>{if(typeof value!=='string'||!value)throw new AppError(400,'VALIDATION_ERROR',`Invalid ${name}`);return value;};
const contactSyncRequest = z.object({ wahaSession: z.string().trim().min(1).max(200).optional() });
export class DomainController {
  constructor(private readonly domain: DomainService, private readonly sessions: { list(context: any): Promise<any[]> }, private readonly contactSync?: WhatsAppContactSyncService) {}
  contacts:RequestHandler=(r,s)=>s.json(this.domain.contacts(r.context!.workspaceId,r.query)); contact:RequestHandler=(r,s)=>s.json(this.domain.contact(r.context!.workspaceId,routeId(r.params.contactId,'contactId'))); contactTags:RequestHandler=(r,s)=>s.json(this.domain.contactTags(r.context!.workspaceId,routeId(r.params.contactId,'contactId'))); createContact:RequestHandler=(r,s)=>s.status(201).json(this.domain.createContact(r.context!.workspaceId,r.body)); updateContact:RequestHandler=(r,s)=>s.json(this.domain.updateContact(r.context!.workspaceId,routeId(r.params.contactId,'contactId'),r.body)); deleteContact:RequestHandler=(r,s)=>{this.domain.deleteContact(r.context!.workspaceId,routeId(r.params.contactId,'contactId'));s.status(204).end()}; importContacts:RequestHandler=(r,s)=>s.status(201).json(this.domain.importContacts(r.context!.workspaceId,r.body)); exportContacts:RequestHandler=(r,s)=>s.type('text/csv').send(this.domain.exportContacts(r.context!.workspaceId));
  tags:RequestHandler=(r,s)=>s.json(this.domain.tags(r.context!.workspaceId)); createTag:RequestHandler=(r,s)=>s.status(201).json(this.domain.createTag(r.context!.workspaceId,r.body)); updateTag:RequestHandler=(r,s)=>s.json(this.domain.updateTag(r.context!.workspaceId,routeId(r.params.tagId,'tagId'),r.body)); deleteTag:RequestHandler=(r,s)=>{this.domain.deleteTag(r.context!.workspaceId,routeId(r.params.tagId,'tagId'));s.status(204).end()};
  templates:RequestHandler=(r,s)=>s.json(this.domain.templates(r.context!.workspaceId)); template:RequestHandler=(r,s)=>s.json(this.domain.template(r.context!.workspaceId,routeId(r.params.templateId,'templateId'))); createTemplate:RequestHandler=(r,s)=>s.status(201).json(this.domain.saveTemplate(r.context!.workspaceId,undefined,r.body)); updateTemplate:RequestHandler=(r,s)=>s.json(this.domain.saveTemplate(r.context!.workspaceId,routeId(r.params.templateId,'templateId'),r.body)); deleteTemplate:RequestHandler=(r,s)=>{this.domain.deleteTemplate(r.context!.workspaceId,routeId(r.params.templateId,'templateId'));s.status(204).end()}; activate:RequestHandler=(r,s)=>s.json(this.domain.templateActive(r.context!.workspaceId,routeId(r.params.templateId,'templateId'),true)); deactivate:RequestHandler=(r,s)=>s.json(this.domain.templateActive(r.context!.workspaceId,routeId(r.params.templateId,'templateId'),false)); preview:RequestHandler=(r,s)=>s.json(this.domain.preview(r.context!.workspaceId,routeId(r.params.templateId,'templateId'),r.body));
  pipelines:RequestHandler=(r,s)=>s.json(this.domain.pipelines(r.context!.workspaceId)); createPipeline:RequestHandler=(r,s)=>s.status(201).json(this.domain.savePipeline(r.context!.workspaceId,undefined,r.body)); updatePipeline:RequestHandler=(r,s)=>s.json(this.domain.savePipeline(r.context!.workspaceId,routeId(r.params.pipelineId,'pipelineId'),r.body)); deletePipeline:RequestHandler=(r,s)=>{this.domain.deletePipeline(r.context!.workspaceId,routeId(r.params.pipelineId,'pipelineId'));s.status(204).end()}; initialize:RequestHandler=(r,s)=>s.status(201).json(this.domain.initPipeline(r.context!.workspaceId,r.body)); stages:RequestHandler=(r,s)=>s.json(this.domain.stages(r.context!.workspaceId,routeId(r.params.pipelineId,'pipelineId'))); createStage:RequestHandler=(r,s)=>s.status(201).json(this.domain.saveStage(r.context!.workspaceId,undefined,{...r.body,pipelineId:r.params.pipelineId})); updateStage:RequestHandler=(r,s)=>s.json(this.domain.saveStage(r.context!.workspaceId,routeId(r.params.stageId,'stageId'),r.body)); reorder:RequestHandler=(r,s)=>s.json(this.domain.reorderStages(r.context!.workspaceId,routeId(r.params.pipelineId,'pipelineId'),r.body)); deleteStage:RequestHandler=(r,s)=>{this.domain.deleteStage(r.context!.workspaceId,routeId(r.params.stageId,'stageId'));s.status(204).end()};
  leads:RequestHandler=(r,s)=>s.json(this.domain.leads(r.context!.workspaceId,r.query)); createLead:RequestHandler=(r,s)=>s.status(201).json(this.domain.saveLead(r.context!.workspaceId,undefined,r.body)); updateLead:RequestHandler=(r,s)=>s.json(this.domain.saveLead(r.context!.workspaceId,routeId(r.params.leadId,'leadId'),r.body)); deleteLead:RequestHandler=(r,s)=>{this.domain.deleteLead(r.context!.workspaceId,routeId(r.params.leadId,'leadId'));s.status(204).end()}; move:RequestHandler=(r,s)=>s.json(this.domain.moveLead(r.context!.workspaceId,routeId(r.params.leadId,'leadId'),r.body)); addLeadTag:RequestHandler=(r,s)=>s.status(201).json(this.domain.leadTag(r.context!.workspaceId,routeId(r.params.leadId,'leadId'),routeId(r.params.tagId,'tagId'),true)); removeLeadTag:RequestHandler=(r,s)=>s.json(this.domain.leadTag(r.context!.workspaceId,routeId(r.params.leadId,'leadId'),routeId(r.params.tagId,'tagId'),false)); note:RequestHandler=(r,s)=>s.status(201).json(this.domain.note(r.context!.workspaceId,routeId(r.params.leadId,'leadId'),r.body)); notes:RequestHandler=(r,s)=>s.json(this.domain.notes(r.context!.workspaceId,routeId(r.params.leadId,'leadId'))); activities:RequestHandler=(r,s)=>s.json(this.domain.activities(r.context!.workspaceId,routeId(r.params.leadId,'leadId'))); funnel:RequestHandler=(r,s)=>s.json(this.domain.funnel(r.context!.workspaceId));
  optOut:RequestHandler=(r,s)=>s.status(201).json(this.domain.optOut(r.context!.workspaceId,routeId(r.params.contactId,'contactId'),r.body)); removeOptOut:RequestHandler=(r,s)=>s.json(this.domain.removeOptOut(r.context!.workspaceId,routeId(r.params.contactId,'contactId'))); optOutStatus:RequestHandler=(r,s)=>s.json(this.domain.optOutStatus(r.context!.workspaceId,routeId(r.params.contactId,'contactId'))); optOutContacts:RequestHandler=(r,s)=>s.json(this.domain.optOutContacts(r.context!.workspaceId,r.query));
  campaigns:RequestHandler=(r,s)=>s.json(this.domain.campaigns(r.context!.workspaceId,r.query)); campaign:RequestHandler=(r,s)=>s.json(this.domain.campaign(r.context!.workspaceId,routeId(r.params.campaignId,'campaignId'))); createCampaign:RequestHandler=(r,s)=>s.status(201).json(this.domain.saveCampaign(r.context!.workspaceId,undefined,r.body)); updateCampaign:RequestHandler=(r,s)=>s.json(this.domain.saveCampaign(r.context!.workspaceId,routeId(r.params.campaignId,'campaignId'),r.body)); deleteCampaign:RequestHandler=(r,s)=>{this.domain.deleteCampaign(r.context!.workspaceId,routeId(r.params.campaignId,'campaignId'));s.status(204).end()}; validateCampaign:RequestHandler=(r,s)=>s.json(this.domain.validateCampaign(r.context!.workspaceId,routeId(r.params.campaignId,'campaignId'))); prepare:RequestHandler=(r,s)=>s.json(this.domain.prepareCampaign(r.context!.workspaceId,routeId(r.params.campaignId,'campaignId'))); schedule:RequestHandler=(r,s)=>s.json(this.domain.scheduleCampaign(r.context!.workspaceId,routeId(r.params.campaignId,'campaignId'),r.body)); cancel:RequestHandler=(r,s)=>s.json(this.domain.cancelCampaign(r.context!.workspaceId,routeId(r.params.campaignId,'campaignId')));
  settings:RequestHandler=(r,s)=>s.json(this.domain.settings(r.context!.workspaceId)); saveSettings:RequestHandler=(r,s)=>s.json(this.domain.saveSettings(r.context!.workspaceId,r.body)); dashboard:RequestHandler=async(r,s)=>{let sessions:any[]=[];try{sessions=await this.sessions.list(r.context!)}catch{ /* Dashboard remains local when the optional session layer is unavailable. */ }s.json(this.domain.dashboard(r.context!.workspaceId,sessions));};
  startContactSync:RequestHandler=async(r,s)=>{if(!this.contactSync)throw new AppError(503,'SERVICE_UNAVAILABLE','Contact synchronization is unavailable');const input=contactSyncRequest.parse(r.body??{});const session=input.wahaSession??await this.connectedWahaSession(r.context!);s.status(202).json(await this.contactSync.start(r.context!.workspaceId,session));};
  contactSyncStatus:RequestHandler=async(r,s)=>{if(!this.contactSync)throw new AppError(503,'SERVICE_UNAVAILABLE','Contact synchronization is unavailable');const wahaSession=z.string().trim().min(1).max(200).parse(r.query.wahaSession);const job=await this.contactSync.status(r.context!.workspaceId,wahaSession);if(!job)throw new AppError(404,'NOT_FOUND','Contact sync job not found');s.json(job);};
  cancelContactSync:RequestHandler=async(r,s)=>{if(!this.contactSync)throw new AppError(503,'SERVICE_UNAVAILABLE','Contact synchronization is unavailable');const wahaSession=contactSyncRequest.parse(r.body??{}).wahaSession;if(!wahaSession)throw new AppError(400,'VALIDATION_ERROR','wahaSession is required');const job=await this.contactSync.cancel(r.context!.workspaceId,wahaSession);if(!job)throw new AppError(404,'NOT_FOUND','Contact sync job not found');s.json(job);};
  /** Mesma regra do `POST /inbox/sync/start`: o nome vivo da sessão vem do
   *  worker (`wahaName`), e o hash derivado de `workspaceId:session.id` é só o
   *  último recurso — refazer o hash aqui já apontou um job para o alias morto
   *  de uma sessão renomeada (ver inbox.controller.ts). */
  private async connectedWahaSession(context: NonNullable<import('express').Request['context']>): Promise<string> { const session = (await this.sessions.list(context))?.find(item => item.status === 'connected'); if (!session) throw new AppError(409, 'CONFLICT', 'No connected WhatsApp session found'); return session.wahaName ?? `chatpro-${createHash('sha256').update(`${context.workspaceId}:${session.id}`).digest('hex').slice(0, 40)}`; }
}
