import type { RequestHandler } from 'express';
import { log } from '../logging.js';
import { WahaWebhookValidationError, parseWebhook, verifyWahaWebhook, webhookRecord, type WahaWebhookStore } from '../services/waha-webhook.service.js';
import type { RealtimeHub } from '../realtime.js';
import type { WhatsAppIdentitySyncService } from '../services/whatsapp-identity-sync.service.js';
export class WahaWebhookController {
  constructor(private readonly store: WahaWebhookStore, private readonly realtime: RealtimeHub, private readonly options: { hmacKey?: string; workspaceId?: string }, private readonly identitySync?: WhatsAppIdentitySyncService, private readonly onOutboundMessage?: (workspaceId: string, externalMessageId: string) => Promise<void>) {}
  receive: RequestHandler = async (req, res, next) => { try {
    verifyWahaWebhook(req.rawBody ?? Buffer.alloc(0), { hmac: req.header('x-webhook-hmac') ?? undefined, algorithm: req.header('x-webhook-hmac-algorithm') ?? undefined, timestamp: req.header('x-webhook-timestamp') ?? undefined }, this.options.hmacKey);
    if (!this.options.workspaceId) throw new WahaWebhookValidationError(503, 'WAHA webhook workspace is not configured');
    const event = parseWebhook(req.body); const result = await this.store.ingest(webhookRecord(event, this.options.workspaceId)); if (!result.duplicate) { if (event.event === 'message' || event.event === 'message.any') { const direction = event.payload.fromMe === true ? 'message.sent' : 'message.received'; const chatId = event.payload.fromMe === true ? firstString(event.payload.to, event.payload.chatId, nestedString(event.payload.key, 'remoteJid')) : firstString(event.payload.chatId, event.payload.from, nestedString(event.payload.key, 'remoteJid')); const messageId = firstString(event.payload.id, nestedString(event.payload.key, 'id')); this.realtime.publish(this.options.workspaceId, direction, { wahaSession: event.session, messageId }); this.realtime.publish(this.options.workspaceId, 'conversation.updated', { wahaSession: event.session, chatId }); if (event.payload.fromMe === true && messageId) await this.onOutboundMessage?.(this.options.workspaceId, messageId); if (chatId) this.identitySync?.enqueue({ workspaceId: this.options.workspaceId, wahaSession: event.session, chatId, ...(firstString(event.payload.participant, nestedString(event.payload.key, 'participant')) ? { senderWhatsappId: firstString(event.payload.participant, nestedString(event.payload.key, 'participant')) } : {}) }); } if (event.event === 'session.status') this.realtime.publish(this.options.workspaceId, 'session.status.changed', { sessionId: event.session, status: event.payload.status ?? 'unknown', changedAt: new Date(event.timestamp).toISOString() }); }
    log('info', 'WAHA webhook accepted', { eventType: event.event, session: event.session, duplicate: result.duplicate }); res.status(result.duplicate ? 200 : 202).json({ accepted: true, duplicate: result.duplicate });
  } catch (error) { if (error instanceof WahaWebhookValidationError) return res.status(error.status).json({ error: { code: error.status === 401 ? 'UNAUTHORIZED' : 'SERVICE_UNAVAILABLE', message: error.message } }); next(error); } };
}
function firstString(...values: unknown[]): string | undefined { return values.find(value => typeof value === 'string' && value.trim()) as string | undefined; }
function nestedString(value: unknown, key: string): string | undefined { return value && typeof value === 'object' && typeof (value as Record<string, unknown>)[key] === 'string' ? (value as Record<string, unknown>)[key] as string : undefined; }
