import { Router } from 'express';
import { CatalogController } from '../controllers/catalog.controller.js';
import { workspaceContext } from '../middleware/context.js';
import { DomainController } from '../controllers/domain.controller.js';
import { InboxController } from '../controllers/inbox.controller.js';
import { WorkspaceDirectoryController } from '../controllers/workspace-directory.controller.js';
import { RoutingController } from '../controllers/routing.controller.js';
export function createV1Router(controller: CatalogController, domain?: DomainController, inbox?: InboxController, directory?: WorkspaceDirectoryController, routing?: RoutingController): Router {
  const router = Router(); router.use(workspaceContext);
  router.get('/sessions', controller.sessions); router.post('/sessions', controller.createSession); router.get('/sessions/:sessionId/status', controller.getSession); router.get('/sessions/:sessionId/qr', controller.qr); router.post('/sessions/:sessionId/connect', controller.connect); router.post('/sessions/:sessionId/stop', controller.disconnect); router.post('/sessions/:sessionId/logout', controller.logout); router.delete('/sessions/:sessionId', controller.removeSession);
  router.get('/contacts', controller.contacts);
  router.get('/templates', controller.templates); router.post('/templates', controller.createTemplate); router.put('/templates/:templateId', controller.updateTemplate); router.delete('/templates/:templateId', controller.removeTemplate);
  if (inbox) { router.get('/inbox/conversations', inbox.listConversations); router.get('/inbox/conversations/:conversationId/messages', inbox.listMessages); router.get('/inbox/conversations/:conversationId/context', inbox.getContext); router.patch('/inbox/conversations/:conversationId/context', inbox.updateContext); router.post('/inbox/conversations/:conversationId/assign', inbox.assign); router.post('/inbox/conversations/:conversationId/unassign', inbox.unassign); router.patch('/inbox/conversations/:conversationId/status', inbox.updateStatus); router.patch('/inbox/conversations/:conversationId/priority', inbox.updatePriority); router.get('/inbox/conversations/:conversationId/activity', inbox.activity); router.post('/inbox/conversations/:conversationId/messages', inbox.sendMessage); router.post('/inbox/conversations/:conversationId/attachments', inbox.attachmentUpload, inbox.createAttachment); router.get('/inbox/outbox/:jobId', inbox.getOutbox); router.post('/inbox/outbox/:jobId/cancel', inbox.cancelOutbox); router.post('/inbox/conversations/:conversationId/read', inbox.markRead); router.post('/inbox/sync/start', inbox.startSync); router.get('/inbox/sync/status', inbox.syncStatus); router.post('/inbox/sync/cancel', inbox.cancelSync); }
  if (routing) { router.post('/inbox/conversations/:id/queue', routing.moveConversation); router.post('/inbox/conversations/:id/redistribute', routing.redistribute); router.get('/inbox/routing-jobs/:id',routing.job); router.post('/inbox/routing-jobs/:id/cancel',routing.cancelJob); }
  if (directory) { router.get('/workspace/users', directory.users); router.post('/workspace/users', directory.createUser); router.patch('/workspace/users/:id', directory.updateUser); router.post('/workspace/users/:id/disable', directory.disableUser); router.post('/workspace/users/:id/enable', directory.enableUser); router.get('/workspace/teams', directory.teams); router.post('/workspace/teams', directory.createTeam); router.patch('/workspace/teams/:id', directory.updateTeam); router.get('/workspace/teams/:id/members', directory.members); router.post('/workspace/teams/:id/members', directory.addMember); router.delete('/workspace/teams/:id/members/:userId', directory.removeMember); }
  if (routing) { router.get('/workspace/queues', routing.queues); router.post('/workspace/queues', routing.createQueue); router.patch('/workspace/queues/:id', routing.updateQueue); router.get('/workspace/queues/:id/members', routing.members); router.post('/workspace/queues/:id/members', routing.saveMember); router.delete('/workspace/queues/:id/members/:userId', routing.removeMember); router.post('/workspace/queues/:id/distribute', routing.distribute); }
  if (domain) {
    router.get('/domain/contacts/export',domain.exportContacts); router.post('/domain/contacts/import',domain.importContacts); router.get('/domain/contacts',domain.contacts); router.post('/domain/contacts',domain.createContact); router.get('/domain/contacts/:contactId',domain.contact); router.patch('/domain/contacts/:contactId',domain.updateContact); router.delete('/domain/contacts/:contactId',domain.deleteContact);
    router.get('/domain/tags',domain.tags); router.post('/domain/tags',domain.createTag); router.patch('/domain/tags/:tagId',domain.updateTag); router.delete('/domain/tags/:tagId',domain.deleteTag);
    router.get('/domain/templates',domain.templates); router.post('/domain/templates',domain.createTemplate); router.get('/domain/templates/:templateId',domain.template); router.patch('/domain/templates/:templateId',domain.updateTemplate); router.delete('/domain/templates/:templateId',domain.deleteTemplate); router.post('/domain/templates/:templateId/activate',domain.activate); router.post('/domain/templates/:templateId/deactivate',domain.deactivate); router.post('/domain/templates/:templateId/preview',domain.preview);
    router.post('/domain/crm/initialize',domain.initialize); router.get('/domain/crm/pipelines',domain.pipelines); router.post('/domain/crm/pipelines',domain.createPipeline); router.patch('/domain/crm/pipelines/:pipelineId',domain.updatePipeline); router.delete('/domain/crm/pipelines/:pipelineId',domain.deletePipeline); router.get('/domain/crm/pipelines/:pipelineId/stages',domain.stages); router.post('/domain/crm/pipelines/:pipelineId/stages',domain.createStage); router.put('/domain/crm/pipelines/:pipelineId/stages/order',domain.reorder); router.patch('/domain/crm/stages/:stageId',domain.updateStage); router.delete('/domain/crm/stages/:stageId',domain.deleteStage);
    router.get('/domain/crm/leads',domain.leads); router.post('/domain/crm/leads',domain.createLead); router.patch('/domain/crm/leads/:leadId',domain.updateLead); router.delete('/domain/crm/leads/:leadId',domain.deleteLead); router.post('/domain/crm/leads/:leadId/move',domain.move); router.post('/domain/crm/leads/:leadId/tags/:tagId',domain.addLeadTag); router.delete('/domain/crm/leads/:leadId/tags/:tagId',domain.removeLeadTag); router.post('/domain/crm/leads/:leadId/notes',domain.note); router.get('/domain/crm/leads/:leadId/notes',domain.notes); router.get('/domain/crm/leads/:leadId/activities',domain.activities); router.get('/domain/crm/funnel',domain.funnel);
    router.post('/domain/contacts/:contactId/opt-out',domain.optOut); router.delete('/domain/contacts/:contactId/opt-out',domain.removeOptOut); router.get('/domain/contacts/:contactId/opt-out',domain.optOutStatus); router.get('/domain/opt-outs',domain.optOutContacts);
    router.get('/domain/campaigns',domain.campaigns); router.post('/domain/campaigns',domain.createCampaign); router.get('/domain/campaigns/:campaignId',domain.campaign); router.patch('/domain/campaigns/:campaignId',domain.updateCampaign); router.delete('/domain/campaigns/:campaignId',domain.deleteCampaign); router.post('/domain/campaigns/:campaignId/validate',domain.validateCampaign); router.post('/domain/campaigns/:campaignId/prepare',domain.prepare); router.post('/domain/campaigns/:campaignId/schedule',domain.schedule); router.post('/domain/campaigns/:campaignId/cancel',domain.cancel);
    router.get('/domain/settings',domain.settings); router.put('/domain/settings',domain.saveSettings); router.get('/domain/dashboard',domain.dashboard);
  }
  return router;
}
